### ISSUE TITLE
You can hear next piece sound with next queue disabled

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#103]
### Description
Tetr.io includes a feature, where upon a new tetromino appearing, an unique sound plays depending on what first piece it is in NEXT queue. However, you can still hear that unique sound with NEXT queue disabled. This can make a player predict what piece will be played next purely by listening to sounds.

### Reproduction
1. Start a custom game with NEXT queue disabled
2. Listen to tetromino appearing sounds

### Expected behavior
You shouldn't be able to hear what piece it is next. You should be able to either hear the piece you are dealt at that immediate moment, a neutral/random sound or nothing at all.

### Additional stuff
Referring to my suggestions above
> [19:40] osk: could make it a seperate room setting too

**Comment by o5k** [comment]
Fixed in next version.
