### ISSUE TITLE
Use different sound for T-spin single/double/triple

### ISSUE THREAD

**Issue by LastExceed** [o5k/tetrio-issues#107]
I find it confusing that they all have the same sound even though they send different amounts of garbage

**Comment by Wirtualnosc** [comment]
I don't mind that, but I think distinguishing between T-spin and minis would be a nice addition. Sometimes I recognize myself getting attacked by sounds and hearing a T-spin sound without an incoming attack does feel weird.

**Comment by o5k** [comment]
Not planned for the current soundsheet - maybe later when soundpacks are a feature.
