### ISSUE TITLE
Ability to quickly view opponent's TL Ranking during Tetra League match

### ISSUE THREAD

**Issue by rajun274** [o5k/tetrio-issues#1090]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

During the opening splash screen of the Tetra League match, you can see the opponent's ranking. But after that screen (say you were away from your computer for a few seconds), there's no guarantee you can easily see the opponent's ranking. First, the user's name at the top is not clickable. Second, there's sometimes a message in the chat that says, "[Opponent] joined the room". The opponent's name is clickable, but that message seems to only exist in 50% of the games. I could try to quickly open a new browser tab and go to their profile, but there's not enough time between games to do that.

### Describe the solution you'd like

There are heaps of solutions. They can be bucketed into 2 categories:

Category 1: Click to view the info (your current implementation). Solutions:

1. At the start of a TL game, always post a message that contains the opponent's username. Upon click, the opponent's profile would be displayed in a popup.
2. Make the username at the top of the Tetra League game pages clickable.

The problem with this category is I need to quickly click on something to view info, then quickly click out to dismiss the popup, all before the next game starts.

Category 2: Embed the info directly on the game page. Solutions:

1. Put the user's TL rank next to their name at the top of the Tetra League game page.
2. Display an infocard of the oppoonent's profile directly on the game page. Put it on the left side of the page, above the chat widget.

The benefits of this category is I can view the information at a glance. I could see complaints from other users that (2) is visually distracting. You can go a step further and enable/display the opponent's infocard with a setting in Options.

### Describe alternatives you've considered

See above.

**Comment by ZaptorZap** [comment]
Alternatively you can also use the ingame social panel to look them up without exiting the window.
![image](https://user-images.githubusercontent.com/64891705/222058751-19b08c1e-6bb9-4756-b30f-94232cf64e6e.png)
This doesn't work if you've got a friend with a username that **includes** their whole username though.

**Comment by rajun274** [comment]
@ZaptorZap Sorry, I don't understand. When I play Tetra League matches, the social panel is hidden. 
![3qyaVsTXdcvtGHC](https://user-images.githubusercontent.com/37415662/222271188-25b17ac1-7e58-4025-bce0-facdf78e15de.png)

**Comment by ZaptorZap** [comment]
Hit `TAB` by default, it's a hotkey that opens up the social panel without needing the exact button.

**Comment by rajun274** [comment]
Ah gotcha! That does work, although having to type the opponent's whole username correctly in a small window of time can be difficult.

**Comment by ZenoCoding** [comment]
You can click on the opponent's name in the chat to view their profile.

**Comment by ZaptorZap** [comment]
> Second, there's **sometimes** a message in the chat that says, "[Opponent] joined the room". The opponent's name is clickable, but that message seems to only exist in **50%** of the games.

Well known and already mentioned.

**Comment by o5k** [comment]
Added in next patch.

**Comment by rajun274** [comment]
Amazing, thank you @ZaptorZap and @o5k !!
