### ISSUE TITLE
Can't connect to server after new update

### ISSUE THREAD

**Issue by 12john27** [o5k/tetrio-issues#110]
After the new update, my IP was no longer able to connect to the server 
<img width="908" alt="Screen Shot 2020-03-07 at 5 43 53 PM" src="https://user-images.githubusercontent.com/44176100/76154136-d3097b00-609c-11ea-9618-cc611d2cddb8.png">

**Comment by o5k** [comment]
Check if your IP has changed. If so, please DM me your new IP.
