### ISSUE TITLE
I lose elo every time I win a game

### ISSUE THREAD

**Issue by Frozoneballs** [o5k/tetrio-issues#1108]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

MAC

### Browser and version

Most recent chrome

### Describe the bug/issue

I dont know the reason for the issue, every time I win I lose a massive amount of elo

### Expected behavior

I would like my elo refunded and added onto my original elo of 5.3k 

### Screenshots

<img width="1512" alt="Screenshot 2023-04-12 at 8 42 29 AM" src="https://user-images.githubusercontent.com/130520524/231321623-adbbdc59-24c5-4c16-908e-583ea6d4286a.png">
<img width="1512" alt="Screenshot 2023-04-12 at 8 27 12 AM" src="https://user-images.githubusercontent.com/130520524/231321624-aa56e584-f42c-4dca-8eb1-86a42f6ba118.png">
![Uploading Screenshot 2023-04-12 at 9.02.20 AM.png…]()
![Uploading Screenshot 2023-04-12 at 8.18.55 AM.png…]()

**Comment by tabik0** [comment]
This has been happening to me as well, I just lost 1114 TR after winning a game; 3-2

**Comment by rydertk** [comment]
Same, I feel you greenjc12
![Desktop Screenshot 2023 04 11 - 15 23 20 65](https://user-images.githubusercontent.com/124866780/231324043-37ad87e6-f5c7-4a89-8d48-ff2cebc6c883.png)

**Comment by MengoMP4** [comment]
Same problem for me. If possible, I would like to regain my original ranking as going back from 600 to 3k would be taking time and be boring as id play with lower levels players, hence not making it fair for my opponent and not challenging for myself. 
![Capture d’écran (17)](https://user-images.githubusercontent.com/130521443/231324134-3a8bc0ee-b855-419c-bc31-d1a89e425156.png)

**Comment by Frozoneballs** [comment]
> Fixed!

I did not get my elo back though, it is currently sitting at 3.3k, 2k lower prior to the bug
