### ISSUE TITLE
Cursor flashing during Sprint

### ISSUE THREAD

**Issue by BurningPain** [o5k/tetrio-issues#111]
### Describe the bug/issue
If I restart in a sprint run my cursor disappears and reappers for a moment (as seen in the video)

### Reproducing
https://youtu.be/qEm-X-pC0V0

### Expected behavior
Either the cursor not being there at all or being there at all time. Flashing like this is distracting.

### Your setup
Version of windows: Windows 8.1
Version of browser: Chrome 80

**Comment by o5k** [comment]
Fixed in next patch.
