### ISSUE TITLE
Hover sounds play when hovering over subelements

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#112]
### Description
Hover a cursor over a player element in game room (or your profile summary in top right corner). Notice how hover sound plays when hovering over each subelement, as opposed to playing once when you hover over the element itself.

### Reproduction
just read 1st sentence in the description duh

### Expected behavior
Hover only plays once and doesn't play again until you unhover and hover over the player element again.

**Comment by o5k** [comment]
Turns out I was really close to fixing this last time but made one stupid error

Truly fixed in next patch.
