### ISSUE TITLE
Unexpected warning upon closing a tab

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#117]
### Description
A warning popup will appear if you close a tab right after cancelling a custom game.

### Reproduction
1. Start a custom game
2. Cancel it
3. Try to close the tab

### Expected behavior
The warning popup shouldn't appear.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/76155096-4cc25880-60df-11ea-86cc-40b9fd64303c.png)

**Comment by o5k** [comment]
Fixed in next patch.
