### ISSUE TITLE
Ghost Garbage Lines Sent

### ISSUE THREAD

**Issue by nathanjslim** [o5k/tetrio-issues#1193]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10 x64 

### Browser and version

Chrome (118.0.5993.117)

### Describe the bug/issue

Playing TL and within 10 seconds of the round starting, lines/garbage were being sent to the opponent without actually clearing lines from my side. 

Tetr.io reply file attached here. 
https://file.io/VV2FYqVwkiR4

### Reproducing

Not sure how the bug occurred so not sure how to reproduce.

### Expected behavior

n/a

### Screenshots

https://file.io/VV2FYqVwkiR4

### Console logs

https://file.io/VV2FYqVwkiR4

**Comment by ZaptorZap** [comment]
This is typically indicative of extreme network lag **during the match**. This causes the replay exclusively to desynchronize, as both players had different timecodes for when they sent garbage. It's a replay issue only, and does not occur during live play. If you review the line clears you eventually made, they will add up to what was sent seconds prior.

This has been a known issue for a while but there's not much of an easy fix. Of course, replays _try_ to account for lag, but when it's insurmountable, this is what happens.
