### ISSUE TITLE
Window confirm leave still doesn't work

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#121]
I did an oof, please don't hurt me osk D:
The code was fine while I tested it...

**Confirm leave, part 2** _(electric boogaloo)_

```js
window.addEventListener("beforeunload",  (e) => {
    e.preventDefault();
    e.returnValue = "";
});

```
I can't guarantee this code will work for tetrio either but it seems like it, might wanna do your own research..

**Comment by o5k** [comment]
It works on my machine? It should only execute when you're actually ingame yourself - not in menus or anything.

**Comment by LayneTheEpic** [comment]
That's my fault, we discussed it on discord
