### ISSUE TITLE
Darker background behind ingame chat

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#124]
Can we have a dark background behind ingame chat? This already is a thing in lobbies.

Lobby chat has a darker background:
![image](https://user-images.githubusercontent.com/6901295/76170097-aa55b400-6176-11ea-8a1d-a7590eabe736.png)

Ingame background doesn't have it and it makes it harder to read text sometimes when on full 100% background visibility:
![image](https://user-images.githubusercontent.com/6901295/76170108-c0637480-6176-11ea-9c60-9c62a2b390f7.png)

**Comment by o5k** [comment]
Since chat can overlap the game, I'll probably make it have an optional gradient background then.

**Comment by o5k** [comment]
Added in next patch.
