### ISSUE TITLE
Game crashed due to low ping

### ISSUE THREAD

**Issue by pmpkata** [o5k/tetrio-issues#1251]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Desktop Client

### Describe the bug/issue

CONNECTION ERROR
a connection error has occured and the connection was closed unexpectedly.
check your internet connection and configuration.

REASON: ping timeout
if you are certain this error is not on your side, please report it.

SOCKET ID: 5ca9b1bee86ed740
WORKER: LUCIA
SPOOL: NA-EAST-MAYURI

Low Ping caused game to crash.

I am attaching the results of a speedtest I just did, I shouldn't be awarded a loss due to a bug on your game.

### Expected behavior

I expected to play through my best of 7 set in tetrio.

### Screenshots

![SpeedTestResults January 14th 2023](https://github.com/tetrio/issues/assets/55934305/ebf18600-179e-41ab-b818-23c4bda02ac8)

### Console logs

I was using the Desktop version.

**Comment by o5k** [comment]
Sorry, but connection errors are outside of the scope of this issue tracker. This is because such issue reports (aside from usually being very low-quality) generally do not help debug any issues. Instead, we employ multiple internal analytics tools tracking disconnect rates and reasons.
