### ISSUE TITLE
"Support TETR.IO" link skips login screen in browser

### ISSUE THREAD

**Issue by KonSola5** [o5k/tetrio-issues#1254]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 121.0.1

### Describe the bug/issue

When you navigate to https://l.tetr.io/support or [https://tetr.io/#S:](https://tetr.io/#S:), the login screen is skipped, despite being opened in browser, not in Electron app.

### Reproducing

1. Go to https://osk.sh/.
2. Click the "SUPPORT ME" in the "ABOUT" section.
3. Notice that you don't need to click "JOIN" manually, TETR.IO automatically logs you in.

### Expected behavior

TETR.IO should not log on automatically in browser.

### Screenshots

https://github.com/tetrio/issues/assets/125081901/6631f930-8ec9-4cc5-8900-2c80b28e41a7

**Comment by o5k** [comment]
This is intended behaviour currently, but will probably be changed when tetrio-desktop integration becomes better (I want to have some proper IPC between browser and desktop.. similar to how Discord and Discord-Web can talk to eachother)
