### ISSUE TITLE
Awarded loss AND win from ONE tetra league match (1 game counted as TWO) 

### ISSUE THREAD

**Issue by bravebanana5324** [o5k/tetrio-issues#1258]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Opera GX 

### Describe the bug/issue

I was playing a TETRA league match and I won the game, and I just went past the win screen animation 

However, the moment after that, my computer randomly disconnected from my wifi for a second. 

5 seconds later, when it reconnected, I clicked back into tetra league and it showed that I forfeited a ranked match. (The match that I had just won) 

Now, I know that I've only played 2 games, lost the first one, and won the second one, but for some reason it showed that I played 2 games and 3 games AT THE SAME TIME, so it counted my 2nd game where I disconnected at the end as 2 games, and awarded me both a win AND a loss for that match. 

After I waited 2 minutes and reloaded the tab, both my profile and my tetra league showed that I played 3 matches... 

### Reproducing

Not sure how to reproduce the behavior, other than to win but disconnect the moment you win, and you might be awarded a win and loss at the same time for a single game...

### Expected behavior

I expected for the game to show me that I had 2 games, 1 win and 1 loss... but it instead showed that I had 2 and 3 games at the same time, and also awarded me a both a loss AND win for ONE game. 

### Screenshots

![image](https://github.com/tetrio/issues/assets/158996952/a9fdce2e-0b6e-420b-941c-650f11158423)

![image](https://github.com/tetrio/issues/assets/158996952/fa909f24-6e86-4ba4-b507-995d8de82d3f)

### Additional context

I think the game counted the game as a win, (since I did win, fair and square) but I also disconnected at the moment I won, so it also thought I disconnected, which leads to both a loss from disconnecting and a win from winning.

**Comment by ZaptorZap** [comment]
Did "going past the win screen animation" involve requeuing into Tetra League? If so, this sounds like you got a matchup **before** the server legitimately declared your connection as dead, but after your client had indeed disconnected. This is known as **match cancellation**, and is an expected mechanic of the matchmaker. That's not to say the mechanic couldn't use some improvements...but it's not as broken as winning and losing the same match.

**Comment by bravebanana5324** [comment]
No, I KO'd the opponent, and the victory animation played, then right before it would go to the screen where you can click replay and rewatch the match, I was disconnected. (I disconnected before I went back to the tetra league home screen, so I don't think I could have possibly queued into another match) 

After that, I reconnected and reloaded the page, clicking back into tetra league, and the amount of games I played on my profile and tetra league were different. (As seen in the first screenshot) 

After thinking about this for 2 minutes, I reloaded the page again and the different amount of games had fixed itself (As seen in the second screenshot) Even though I had not pressed 'enter matchmaking' at all or queued into any games since I started my second game.

**Comment by bravebanana5324** [comment]
I wish tetrio would add a game history feature so that you could see your past games and who you won/lost against, that would definitely clear this up

**Comment by ZaptorZap** [comment]
TETR.IO already does have that—yours is shown [**here**](https://ch.tetr.io/s/league_userrecent_65c052e2ade6d287b844ed44). The issue is—canceled matches aren't written to your ten game history, so I highly doubt this issue is perceivable from the record anyways. That's what makes the issue problematic to diagnose…

**Comment by bravebanana5324** [comment]
Oh that sucks. I've already played more than 10 games since then anyways, but it's fine since it's just one game and it didn't even really affect my TR anyways. Thanks for your help.

**Comment by p1nkl0bst3r** [comment]
I think it did show up, see the 3rd from the bottom https://api.p1nkl0bst3r.xyz/tlmatches/65c052e2ade6d287b844ed44
