### ISSUE TITLE
Problems with the delay for spectator input after dying

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#126]
### Description
There are two problems:
- The delay applies for switching boards with keyboard input as a spectator. Each time a board is switched, the delay is activated again
- When you press a key during the delay, you can hear the sound effect, but nothing happens

### Reproduction
Go to multiplayer game as a spectator and spam movement keys

### Expected behavior
No sound should be heard and ideally you should be able to switch between boards with less/no delay.

**Comment by o5k** [comment]
Fixed in next patch,
