### ISSUE TITLE
Leveling up in Zen in Discreet mode does not reset the gravity

### ISSUE THREAD

**Issue by KonSola5** [o5k/tetrio-issues#1260]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Firefox 122.0.1

### Describe the bug/issue

When leveling up in Zen in Discreet mode, using a preset gravity setting, the gravity does not get reset.

### Reproducing

1. Play Zen.
2. Enable Discreet leveling mode and Relaxed/Engaging/Spicy gravity.
3. Play through the whole level.
4. Notice that on the next level, the gravity does not get reset to the starting gravity for the preset.
5. After placing a piece in the next level, undo.
6. Notice that the gravity did reset.

### Expected behavior

The gravity should be reset, like it does with Leveling ON.

### Screenshots

All of the videos were recorded with Spicy gravity.
# Beginning of the level (for comparison)
https://github.com/tetrio/issues/assets/125081901/922cc8b1-59c6-4262-abe3-714ffca5eb7c

# Level up
https://github.com/tetrio/issues/assets/125081901/3c1c0cc0-5535-4aaf-8b05-c31446efd264

**Comment by o5k** [comment]
Fixed in next patch.
