### ISSUE TITLE
I don't receive the emil when I forgot my password.

### ISSUE THREAD

**Issue by Simsiano** [o5k/tetrio-issues#1261]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 8.1 Pro

### Browser and version

Chrome 109.0.5414.168

### Describe the bug/issue

I don't receive any password when I click the forgot password option.
Yes, the email is correct and I checked the spam inbox.

### Expected behavior

I should receive the email.

**Comment by ZaptorZap** [comment]
The email system appears to be functional for me, so I'm closing this issue. As always, please check your spam folders—if your email has a period in it, you may want to ensure that's also included when you request your password reset.
![image](https://github.com/tetrio/issues/assets/64891705/eebcd055-b312-4551-9a24-9fc40b3dea3a)

Sorry, but beyond this vague information, this repository isn't for account support. Please email [support@tetr.io](https://tetr.io/about/support/) about such issues.
