### ISSUE TITLE
Tetra League rank cutoff API

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [o5k/tetrio-issues#1262]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I have a program that automatically updates the current rank score line every hour
But I think that requesting all users' data every hour may cause a huge waste of server resources, and I just calculate the position of the current score line.

### Describe the solution you'd like

Provides an API that can be used to get the current score line, like this (?

```JSON
{
    "x": 24718.84,
    "u": 23445.11,
    ... and more
}
```

### Describe alternatives you've considered

Get all users' data and calculate possible score using known percentages

**Comment by p1nkl0bst3r** [comment]
I have an api with that data https://api.p1nkl0bst3r.xyz/rankcutoff

**Comment by AzuraHorizons** [comment]
Should probably be closed as complete, alongside #1016 / #1240 / #871 following the beta update
