### ISSUE TITLE
Custom Game Countdown doesnt have a limit, resulting in the countdown sound overlapping every other sound even when exiting

### ISSUE THREAD

**Issue by TheMcChicken** [o5k/tetrio-issues#1265]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome OS V121

### Browser and version

Chrome 121

### Describe the bug/issue

Starting a custom game with Countdown Count to an absurdly high number will cause the game to never start, and exiting makes the sound just keep playing until its either finished or the tab is closed. (also the countdown visual in-game caps at ~100 quadrillion, or going too high causes the game to display (digit)E+(digit))

### Reproducing

When you start a custom game, go to Meta, set Countdown Count to an absurdly high number, and when you start the game, it results in the Countdown sound playing forever until the tab is closed. If countdown interval is set to a very low number, it makes a buzzing sound.

### Expected behavior

A limit of around up to 180 seconds, or the countdown sound to stop when exiting the game.

### Screenshots

https://github.com/tetrio/issues/assets/106632528/f7bc5021-e725-4a1f-ae2f-72c38040a957

**Comment by KonSola5** [comment]
Still an issue.

**Comment by AzuraHorizons** [comment]
can confirm this still happens
