### ISSUE TITLE
Certain Music Plays at Wrong Areas

### ISSUE THREAD

**Issue by TheMcChicken** [o5k/tetrio-issues#1267]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome OS v122

### Browser and version

Chrome 122

### Describe the bug/issue

The Menu Music has been playing in areas where it shouldn't be. (Eg: Tetra Channel Music playing in a Replay and the Quick Play lobby music playing in-game.)

### Reproducing

Just go to any menu, and play a game/watch a replay. Sometimes the Previous Menus music will keep playing.

### Expected behavior

The Music to Stop when going in-game, and the correct music to play.

**Comment by Dimentio** [comment]
Any way to reproduce?
