### ISSUE TITLE
Occassional sound blast

### ISSUE THREAD

**Issue by aytuggiray** [o5k/tetrio-issues#1269]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Microsoft Windows 10

### Browser and version

Chrome Version 122.0.6261.112 (Official Build) (64-bit)

### Describe the bug/issue

While playing 4 wide multiplayer lobbies, I experienced occasional sound blast as if I received or sent 100 blocks at the same time and it sounds like an explosion. It also happened while playing custom solo games with column size 4 but can't remember how it happened.

It happened during the game and not spectating.

### Expected behavior

Expected game to deliver sounds properly and not experience a sound issue that felt like a jump scare even though the volume is at 1%.

### Console logs

bootstrap.js?hv=09548daa.9CkbDp3J5.Z4IDDaYdu:2 Bootstrapping for hardver 09548daa.9CkbDp3J5.Z4IDDaYdu
 undefined
moon.kagari.moe/matomo.js:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
VM14:43 webgl backend was already registered. Reusing existing backend factory.
window.console.warn @ VM14:43
VM14:43 cpu backend was already registered. Reusing existing backend factory.
window.console.warn @ VM14:43
VM14:43 Platform browser has already been set. Overwriting the platform with [object Object].
window.console.warn @ VM14:43
VM14:42 TETR.IO
VM14:42 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
5Third-party cookie will be blocked. Learn more in the Issues tab.
VM14:42 Up to date. Local version 6.4.3-production | Commit 09548daa@master (3/10/2024, 2:56:16 AM) | Server cycle 9CkbDp3J5 | Build Z4IDDaYdu (3/10/2024, 2:56:34 AM)
VM14:42 auth-return-lb mounted, now 1 mounts
VM14:43 Ceriad provider could not be loaded.
window.console.warn @ VM14:43
VM14:42 auth-return-lb unmounted, now 0 mounts
api.enthusiastgaming.net/scripts/cdn.enthusiast.gg/script/eg-aps/production/eg-aps-bootstrap.bundle.js?site=tetr.io:1 
        
        
       Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
282The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
VM14:42 PixiJS 6.1.3 - WebGL 2
VM14:42 - Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 -CPU: 16-coreMemory: ~8 GBConnection: 10 Mbps, 50ms RTT [4g]
VM14:42 Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 SUPER (0x00001F06) Direct3D11 vs_5_0 ps_5_0, D3D11)
VM14:42 InitialConnect > Obtaining Ribbon endpoint...
VM14:42 InitialConnect > Obtained Ribbon endpoint /ribbon/chibimoth and 24 spools, fallback available.
VM14:42 InitialConnect > Getting a spool...
VM14:42 InitialConnect > Spool > Spooling started
VM14:42 InitialConnect > Spool >    62+5ms eu-kuroko [FR] v4 // 0.125, 0.109375, 0.03125
VM14:42 InitialConnect > Spool >    72+0ms eu-mikoto [NL] v4 // 0.171875, 0.140625, 0.09375
VM14:42 InitialConnect > Spool >    78+49ms uk-ikaros [GB] v4 // 0, 0.015625, 0
VM14:42 InitialConnect > Spool > Spooled eu-kuroko!
VM14:42 InitialConnect > Obtained spool eu-kuroko (eu-kuroko.spool.tetr.io) [FR].
VM14:42 Ribbon 26c3e9501295b220 opened
VM14:43 Ribbon 26c3e9501295b220 changing endpoint (new endpoint: wss://eu-kuroko.spool.tetr.io/ribbon/nishikujou)
window.console.warn @ VM14:43
VM14:42 Ribbon 26c3e9501295b220 closed (ribbon lost)
VM14:42 Ribbon 26c3e9501295b220 resuming
VM14:42 Ribbon 26c3e9501295b220 resumed
VM14:43 Ribbon 26c3e9501295b220 changing endpoint (new endpoint: wss://eu-kuroko.spool.tetr.io/ribbon/akane)
window.console.warn @ VM14:43
VM14:42 Ribbon 26c3e9501295b220 closed (ribbon lost)
VM14:42 Ribbon 26c3e9501295b220 resuming
VM14:42 Ribbon 26c3e9501295b220 resumed
VM14:43 Ribbon 26c3e9501295b220 changing endpoint (new endpoint: wss://eu-kuroko.spool.tetr.io/ribbon/pani)
window.console.warn @ VM14:43
VM14:42 Ribbon 26c3e9501295b220 closed (ribbon lost)
VM14:42 Ribbon 26c3e9501295b220 resuming
VM14:42 Ribbon 26c3e9501295b220 resumed
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/shimako and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    27+6ms eu-kuroko [FR] v4 // 0.015625, 0.078125, 0.015625
VM14:42 AmbientRespool > Spool >    27+0ms eu-mikoto [NL] v4 // 0.078125, 0.125, 0.09375
VM14:42 AmbientRespool > Spool >    31+15ms uk-ikaros [GB] v4 // 0, 0.03125, 0
VM14:42 AmbientRespool > Spool > Spooled eu-mikoto!
VM14:42 AmbientRespool > Obtained spool eu-mikoto (eu-mikoto.spool.tetr.io) [NL].
VM14:42 AmbientRespool > Obtained new token, no significant ping advantage 64ms → 53ms.
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/nishikujou and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    27+1ms eu-mikoto [NL] v4 // 0.0625, 0.078125, 0.078125
VM14:42 AmbientRespool > Spool >    26+6ms eu-kuroko [FR] v4 // 0.046875, 0.0625, 0.015625
VM14:42 AmbientRespool > Spool >    31+3ms uk-ikaros [GB] v4 // 0, 0.015625, 0
VM14:42 AmbientRespool > Spool > Spooled eu-kuroko!
VM14:42 AmbientRespool > Obtained spool eu-kuroko (eu-kuroko.spool.tetr.io) [FR].
VM14:42 AmbientRespool > Obtained new token, already on best available spool.
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/gil and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    27+0ms eu-mikoto [NL] v4 // 0.0625, 0.125, 0.09375
VM14:42 AmbientRespool > Spool >    26+5ms eu-kuroko [FR] v4 // 0.03125, 0.0625, 0.015625
VM14:42 AmbientRespool > Spool >    31+4ms uk-ikaros [GB] v4 // 0.015625, 0.046875, 0
VM14:42 AmbientRespool > Spool > Spooled eu-mikoto!
VM14:42 AmbientRespool > Obtained spool eu-mikoto (eu-mikoto.spool.tetr.io) [NL].
VM14:42 AmbientRespool > Obtained new token, no significant ping advantage 64ms → 54ms.
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/inoue and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    27+6ms eu-kuroko [FR] v4 // 0.015625, 0.046875, 0.015625
VM14:42 AmbientRespool > Spool >    27+0ms eu-mikoto [NL] v4 // 0.015625, 0.078125, 0.078125
VM14:42 AmbientRespool > Spool >    32+38ms uk-ikaros [GB] v4 // 0.0625, 0.0625, 0
VM14:42 AmbientRespool > Spool > Spooled eu-mikoto!
VM14:42 AmbientRespool > Obtained spool eu-mikoto (eu-mikoto.spool.tetr.io) [NL].
VM14:42 AmbientRespool > Obtained new token, no significant ping advantage 63ms → 55ms.
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/shimako and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    27+7ms eu-kuroko [FR] v4 // 0.015625, 0.046875, 0.015625
VM14:42 AmbientRespool > Spool >    28+1ms eu-mikoto [NL] v4 // 0.046875, 0.046875, 0.0625
VM14:42 AmbientRespool > Spool >    31+3ms uk-ikaros [GB] v4 // 0.015625, 0.046875, 0
VM14:42 AmbientRespool > Spool > Spooled eu-mikoto!
VM14:42 AmbientRespool > Obtained spool eu-mikoto (eu-mikoto.spool.tetr.io) [NL].
VM14:42 AmbientRespool > Obtained new token, no significant ping advantage 64ms → 57ms.
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/kotori and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    26+5ms eu-kuroko [FR] v4 // 0, 0.03125, 0
VM14:42 AmbientRespool > Spool >    27+0ms eu-mikoto [NL] v4 // 0.046875, 0.0625, 0.078125
VM14:42 AmbientRespool > Spool >    32+3ms uk-ikaros [GB] v4 // 0.015625, 0.046875, 0
VM14:42 AmbientRespool > Spool > Spooled eu-kuroko!
VM14:42 AmbientRespool > Obtained spool eu-kuroko (eu-kuroko.spool.tetr.io) [FR].
VM14:42 AmbientRespool > Obtained new token, already on best available spool.
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/kotarou and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    26+5ms eu-kuroko [FR] v4 // 0.109375, 0.046875, 0
VM14:42 AmbientRespool > Spool >    27+0ms eu-mikoto [NL] v4 // 0.15625, 0.078125, 0.078125
VM14:42 AmbientRespool > Spool >    31+27ms uk-ikaros [GB] v4 // 0.015625, 0.046875, 0
VM14:42 AmbientRespool > Spool > Spooled eu-mikoto!
VM14:42 AmbientRespool > Obtained spool eu-mikoto (eu-mikoto.spool.tetr.io) [NL].
VM14:42 AmbientRespool > Obtained new token, no significant ping advantage 62ms → 54ms.
VM14:42 AmbientRespool > Starting ambient respool.
VM14:42 AmbientRespool > Obtaining Ribbon endpoint...
VM14:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/gil and 24 spools, fallback available.
VM14:42 AmbientRespool > Getting a spool...
VM14:42 AmbientRespool > Spool > Spooling started
VM14:42 AmbientRespool > Spool >    28+0ms eu-mikoto [NL] v4 // 0.234375, 0.125, 0.09375
VM14:42 AmbientRespool > Spool >    29+6ms eu-kuroko [FR] v4 // 0, 0.015625, 0
VM14:42 AmbientRespool > Spool >    32+3ms uk-ikaros [GB] v4 // 0.015625, 0.046875, 0
VM14:42 AmbientRespool > Spool > Spooled eu-mikoto!
VM14:42 AmbientRespool > Obtained spool eu-mikoto (eu-mikoto.spool.tetr.io) [NL].
VM14:42 AmbientRespool > Obtained new token, no significant ping advantage 65ms → 55ms.

**Comment by ahiijny** [comment]
Happened to me in tetra league today too. Seems relatively rare, I think this was the only time I've encountered it so far.

Happens at around 0:08:

https://github.com/tetrio/issues/assets/5766317/4d6b5c79-808c-47b6-9a45-86c103d3f582

**Comment by aytuggiray** [comment]
Yeah, my issue was quite similar as well. Mine was more like a burst of 100 blocks all at the same time. Thank you for providing a video evidence of the issue which my message lacked.

Even though you've mentioned when it will happen, it still scared me! Haha

**Comment by mouzedrift** [comment]
https://www.twitch.tv/your_connection/clip/TawdryFaintPenguinTinyFace-9n1tRRZEbZrIhEO7 heres another one. really annoying bug

**Comment by Dimentio** [comment]
Is this still happening since the last patchnote?
