### ISSUE TITLE
Banner Unclickable

### ISSUE THREAD

**Issue by SaundersCox** [o5k/tetrio-issues#1271]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Version 120.0.6099.111 (Official Build) (64-bit)

### Describe the bug/issue

Cannot click the banner (Modern Tetris Showdown 4 advertisement) within the majority of the region of the image.
Only the region within the red rectangle is clickable:
![image](https://github.com/tetrio/issues/assets/34501844/9545b372-dc8d-40d7-bc27-83f9ec725f95)

### Reproducing

1. Load HOME Screen
2. Attempt to click within the banner outside the red rectangle in the provided image

### Expected behavior

The entire banner should be clickable

### Screenshots

![image](https://github.com/tetrio/issues/assets/34501844/58e88ba9-f66a-4d62-b727-8c1881c90d13)

### Console logs
<details>
d.turn.com/r/dd/id/L21rdC84MTYvY2lkLzE3NDc3OTM0OTIvdC8y/kv/ID1=1250849d-9023-488e-95e5-0dafe40c455c:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
FZt5psomz79DGe~O1V5PkX7S8-NVJIdw0INR-k~Duu9c36GyIDyElf4y8fa2~-9InNSq4BCadyu-8tQSiIkaVleT~Yh8GI4ocNSeo4~API4DJEsYNIMg2sPMMXvjcckTUFy53ZYw3gzv35jSAchydRkSr2XFgqe-kzzlKTlv1VT7-TlAc0PcX7nFzbKlHypwbpU3AWUAJgUx%20006C9886-8966-463A-A7D7-2CDA744B592A&rnd=RND:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
FZt5psomz79DGe~O1V5PkX7S8-NVJIdw0INR-k~Duu9c36GyIDyElf4y8fa2~-9InNSq4BCadyu-8tQSiIkaVleT~Yh8GI4ocNSeo4~API4DJEsYNIMg2sPMMXvjcckTUFy53ZYw3gzv35jSAchydRkSr2XFgqe-kzzlKTlv1VT7-TlAc0PcX7nFzbKlHypwbpU3AWUAJgUx%20006C9886-8966-463A-A7D7-2CDA744B592A&rnd=RND:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
VM11:42 home-lb unmounted, now 0 mounts
VM11:42 solo-lb mounted, now 1 mounts
VM11:42 solo-lb unmounted, now 0 mounts
VM11:42 soloresults-lb mounted, now 1 mounts
 SyntaxError
VM11:42 soloresults-lb unmounted, now 0 mounts
VM11:42 soloresults-lb mounted, now 1 mounts
choices.truste.com/ca?pid=tradedesk01&aid=tradedesk01&cid=hhuhhro_2hqfihf_qz3cu27t&c=%%TTD_PRIVACY_TAG_CAMPAIGN_MACRO%%&js=pmw0&w=728&h=90&sid=0&dsarequired=${DSAREQUIRED}&dsabehalf=${DSABEHALF}&dsapaid=${DSAPAID}&dsaparams=${DSAPARAMS}:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
VM11:42 soloresults-lb unmounted, now 0 mounts
VM11:42 home-lb mounted, now 1 mounts
VM11:42 AmbientRespool > Starting ambient respool.
VM11:42 AmbientRespool > Obtaining Ribbon endpoint...
VM11:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/shimako and 28 spools, fallback available.
VM11:42 AmbientRespool > Getting a spool...
VM11:42 AmbientRespool > Spool > Spooling started
VM11:42 AmbientRespool > Spool >     7+40ms na-east-kurisu [US] v4 // 0.265625, 0.140625, 0.125
VM11:42 AmbientRespool > Spool >    13+53ms na-east-mayuri [US] v4 // 0.25, 0.125, 0.09375
VM11:42 AmbientRespool > Spool >    17+47ms na-mid-maho [CA] v4 // 0.03125, 0.125, 0.15625
VM11:42 AmbientRespool > Spool > Spooled na-east-kurisu!
VM11:42 AmbientRespool > Obtained spool na-east-kurisu (na-east-kurisu.spool.tetr.io) [US].
VM11:42 AmbientRespool > Obtained new token, already on best available spool.
957Third-party cookie will be blocked. Learn more in the Issues tab.
 SyntaxError
54The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
VM11:43 [Ceriad] Captured abusive ceriad in ID div-gpt-ad-tet-3. Ceriad source: about:blank. It shall be obliterated.
window.console.warn @ VM11:43
tetr.io/:1 Access to XMLHttpRequest at 'https://kagari.network/ceriad-abusereport?src=about%3Ablank&id=div-gpt-ad-tet-3' from origin 'https://tetr.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
kagari.network/ceriad-abusereport?src=about%3Ablank&id=div-gpt-ad-tet-3:1 
        
        
       Failed to load resource: net::ERR_FAILED
VM11:42 AmbientRespool > Starting ambient respool.
VM11:42 AmbientRespool > Obtaining Ribbon endpoint...
VM11:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/inoue and 28 spools, fallback available.
VM11:42 AmbientRespool > Getting a spool...
VM11:42 AmbientRespool > Spool > Spooling started
VM11:42 AmbientRespool > Spool >     7+40ms na-east-kurisu [US] v4 // 0.21875, 0.1875, 0.140625
VM11:42 AmbientRespool > Spool >    11+53ms na-east-mayuri [US] v4 // 0.09375, 0.109375, 0.078125
VM11:42 AmbientRespool > Spool >    14+47ms na-mid-maho [CA] v4 // 0.265625, 0.1875, 0.171875
VM11:42 AmbientRespool > Spool > Spooled na-east-kurisu!
VM11:42 AmbientRespool > Obtained spool na-east-kurisu (na-east-kurisu.spool.tetr.io) [US].
VM11:42 AmbientRespool > Obtained new token, already on best available spool.
5321 log entries are not shown.
</details>

**Comment by visiblyisabelle** [comment]
looks like unsetting the banner's `z-index` sorts this, should be a fairly straightforward fix

**Comment by o5k** [comment]
Hotfixed - F5 to receive the fix.
