### ISSUE TITLE
"Pause reply after end" doesn't always show last move

### ISSUE THREAD

**Issue by rajun274** [o5k/tetrio-issues#1276]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

HP Elite Dragonfly 13.5 2022 (16GB) Chromebook

### Browser and version

Chrome Version 121.0.6167.212 (Official Build) (64-bit)

### Describe the bug/issue

"Pause reply after end" doesn't always show the very last move that a player does, probably because of some timing issue.

### Reproducing

Steps to reproduce:
1. Go to this replay file, which is pointing to the 3rd match: https://tetr.io/#R:MmREYZZ1I@3
2. The default watch mode is "Exit replay after end".
3. Watch player DERKMEH until the very end. You'll see that their last moves are LEFT and then HARD DROP: 
![exit_reply_after_end](https://github.com/tetrio/issues/assets/37415662/6eb460cc-fa3f-4dcd-943c-6192ad48dcf0)
4. Go back to that match, but change the watch mode to "Pause reply after end".
5. Again, watch player DERKMEH until the very end. When the player pauses, the game omits the LEFT: 
![pause_reply_after_end](https://github.com/tetrio/issues/assets/37415662/e8107aea-70b1-40cd-af9b-6fe696460185)

Note that in my reproduction, it's quite obvious why DERKMEH loses regardless of which watch mode you do. But I reckon that in a scenario where the player misdrops an I piece into a 4-wide well that's in the middle of the board, and they watch the replay and reproduce this bug, it will confuse the player as to why they lost.

### Expected behavior

When the video pauses when watching in mode "Pause reply after end", it should show the very last move that all players do.

### Console logs

Likely not needed.

**Comment by p1nkl0bst3r** [comment]
related: https://github.com/tetrio/issues/issues/605#issuecomment-763182935
