### ISSUE TITLE
No chat box border animation when opened in lobby

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#128]
### Description
While in game, using the shortcut/clicking the chatbox displays an animation of the border getting a faint halo with a nice transition. In lobbies (tested in Quick Play alone), the border is just solid white with no transition.

### Reproducing
1. Join a game lobby (tested in Quick Play solely)
2. Click on/use shortcut to open chatbox
3. Observe the border change (compared to in game)

### Expected behavior
The chatbox should have a _consistent_ "selected" animation, while in game and in lobbies aren't the same.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.66

**Comment by o5k** [comment]
Fixed in next patch.
