### ISSUE TITLE
TETR.IO Desktop Application

### ISSUE THREAD

**Issue by Oak6** [o5k/tetrio-issues#1280]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

macOS Sonoma 14.4

### Browser and version

Opera GX

### Describe the bug/issue

TETR.IO cant be opened because Apple cannot check it for malicious software
<img width="254" alt="Screenshot 2024-04-04 at 3 11 52 PM" src="https://github.com/tetrio/issues/assets/166074642/effb438c-bdb5-498b-a81d-f08eeecc2368">

### Reproducing

1. Download the TETR.IO app
2. Move it to applications folder
3. Open the application

### Expected behavior

A popup saying apple cant verify

### Screenshots

<img width="254" alt="Screenshot 2024-04-04 at 3 11 52 PM" src="https://github.com/tetrio/issues/assets/166074642/a720bdfc-45c2-46d1-bc08-0642c85fac44">

**Comment by ZaptorZap** [comment]
Please review [**the FAQ**](https://tetrio.github.io/faq/troubleshooting.html#machelp).
