### ISSUE TITLE
instant death bug

### ISSUE THREAD

**Issue by StevieSmiley** [o5k/tetrio-issues#1282]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

win 11

### Browser and version

application 

### Describe the bug/issue

Apparent random instant death that may be dependent on lines being sent.

### Reproducing

1. set are to 30 ( more than 1 )
2. set garbage are to 50 ( also more than 1 )
3. set garbage entry to continuous
4. playing the game will result in seemingly instant death  

### Expected behavior

expected are setting to slow the game mechanic
 while garbage are and garbage entry at continuous to generate lines slowly

### Console logs

VM11:43 The tag element with id=div-gpt-ad-tet-6 wasn't found and couldn't be created as well!
window.console.warn @ VM11:43
VM11:42 roomresults-mega unmounted, now 0 mounts
VM11:42 roomresults-mega mounted, now 1 mounts
VM11:42 roomresults-mega unmounted, now 0 mounts
VM11:42 roomresults-mega mounted, now 1 mounts
VM11:42 roomresults-mega unmounted, now 0 mounts
VM11:42 AmbientRespool > Starting ambient respool.
VM11:42 AmbientRespool > Obtaining Ribbon endpoint...
VM11:42 AmbientRespool > Obtained Ribbon endpoint /ribbon/sakuya and 26 spools, fallback available.
VM11:42 AmbientRespool > Getting a spool...
VM11:42 AmbientRespool > Spool > Spooling started
VM11:42 AmbientRespool > Spool >    17+71ms na-west-sonya [US] v4 // 0.15625, 0.046875, 0.046875
VM11:42 AmbientRespool > Spool >    19+71ms na-west-agiri [US] v4 // 0.1875, 0.09375, 0.03125
VM11:42 AmbientRespool > Spool >    37+58ms na-east-mayuri [US] v4 // 0.078125, 0.046875, 0.046875
VM11:42 AmbientRespool > Spool > Spooled na-east-mayuri!
VM11:42 AmbientRespool > Obtained spool na-east-mayuri (na-east-mayuri.spool.tetr.io) [US].
VM11:42 AmbientRespool > Obtained new token, no significant ping advantage 165ms → 191ms.
VM11:42 roomresults-mega mounted, now 1 mounts
VM11:42 roomresults-mega unmounted, now 0 mounts
VM11:42 lobby-lb mounted, now 1 mounts
VM11:43 The tag element with id=div-gpt-ad-tet-14 wasn't found and couldn't be created as well!
window.console.warn @ VM11:43
1185Third-party cookie will be blocked. Learn more in the Issues tab.
VM11:42 lobby-lb unmounted, now 0 mounts
22The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
VM11:42 lobby-lb mounted, now 1 mounts
VM11:42 lobby-lb unmounted, now 0 mounts
VM11:42 roomresults-lb mounted, now 1 mounts
VM11:43 The tag element with id=div-gpt-ad-tet-6 wasn't found and couldn't be created as well!
window.console.warn @ VM11:43
ee @ smart.js:4
n.render @ smart.js:4
(anonymous) @ VM17:1
(anonymous) @ VM17:1
n.cmd.push @ smart.js:4
e.addToTheExecutableQueue @ VM17:1
e.render @ VM17:1
(anonymous) @ VM17:1
n.cmd.push @ smart.js:4
e.addToTheExecutableQueue @ VM17:1
(anonymous) @ VM17:1
e.renderAds @ VM17:1
(anonymous) @ VM17:1
VM11:42 roomresults-lb unmounted, now 0 mounts
48933 log entries are not shown.
VM11:42 roomresults-lb mounted, now 1 mounts
VM11:42 roomresults-lb unmounted, now 0 mounts
VM11:42 roomresults-lb mounted, now 1 mounts

**Comment by Talon125** [comment]
### Relevant Replay Files
1. [replay_wrongDeathBug-20240407.ttrm.txt](https://github.com/tetrio/issues/files/14895683/replay_wrongDeathBug-20240407.ttrm.txt)
2. [replay_wrongDeathBug_2-20240407.ttrm.txt](https://github.com/tetrio/issues/files/14895684/replay_wrongDeathBug_2-20240407.ttrm.txt)
3. [replay_wrongDeathBug_3-20240407.ttrm.txt](https://github.com/tetrio/issues/files/14895685/replay_wrongDeathBug_3-20240407.ttrm.txt)

---

After further testing, death seems to occur when when a line of garbage and the next piece spawn at around the same time.

In the 2nd and 3rd replays, the Entry Delay (ARE) is set to 60 and the Garbage ARE is set to 30, which seems to guarantee death with pending garbage.

**Comment by StevieSmiley** [comment]
found an additional death occurrence using Line clear ARE instead of Entry delay ( are )  didnt save the replays at the time however.

**Comment by Talon125** [comment]
> In the 2nd and 3rd replays, the Entry Delay (ARE) is set to 60 and the Garbage ARE is set to 30, which seems to guarantee death with pending garbage.

Also works if the Entry Delay (ARE) is set to 2 frames and the Garbage ARE is set to 1 frame; i.e. ARE being double that of Garbage ARE guarantees death.

> found an additional death occurrence using Line clear ARE instead of Entry delay ( are ) didnt save the replays at the time however.

The bug (death) definitely seems to occur when garbage and a piece spawn at the same time. IHS has no effect. Dying while having stock acts normally.

**Comment by Talon125** [comment]
Can confirm that this bug still occurs.

**Comment by Talon125** [comment]
> found an additional death occurrence using Line clear ARE instead of Entry delay ( are ) didnt save the replays at the time however.

Also found to occur with the following settings:

ARE: 6  
Line Clear ARE: 0

ARE: 60  
Line Clear ARE: 0

ARE: 300  
Line Clear ARE: 0

So, it seems now that ARE must be 6 or higher for the bug to occur. Line Clear ARE is now irrelevant.

To reiterate, this happens with Garbage Entry set to Continuous.

**Comment by Dimentio** [comment]
Should be fixed next update!
