### ISSUE TITLE
The Game Is Too Loud

### ISSUE THREAD

**Issue by doktorocelot** [o5k/tetrio-issues#1283]
# The game is very loud.

The extremely loud volume causes most players to turn their volumes down to something like 5%. This needs to be addressed.

Let's balance the game to make 100% closer to what someone would want on most systems when they are playing without needing to listen to anything else, such as a Discord call (-26 – -18 LUFs or so). This way, people can bring the volume down from there if they want a quieter experience, or up to 200% if they need a little more boost for their setup.

**Comment by o5k** [comment]
:love:
