### ISSUE TITLE
Keeps crashing when start solo 40 lines and biltz

### ISSUE THREAD

**Issue by jacktang22** [o5k/tetrio-issues#1286]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

ios17 ipad gen 8

### Browser and version

Chrome 123.0.6312.52 (Official Build) stable (64-bit) 

### Describe the bug/issue

One day after not playing for like a month i found ouut that it keeps crashing. It just blanks out and refreshes. I’ve tried to clear browsing cookies and site data and like everything but still doesn’t work. Maybe the ipad RAM is not good enough. Can the team fix this?

### Expected behavior

start the game

### Screenshots

it just reloaded

### Console logs

it crashed and reloaded

**Comment by visiblyisabelle** [comment]
iOS/iPadOS WebKit browsers aren't supported, and crashes of this nature tend to be due to performance limitations. Without any further information to diagnose the problem (such as console logs - which admittedly are difficult to obtain on mobile devices), we'll have to assume this is the case.
