### ISSUE TITLE
Issue with player field after switching to Tetr.io from another tab

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#129]
### Describe the bug/issue
Player board seem to gain an unusal vertical velocity when not focused (ie, in another tab). It seems like the line clear momentum stacks, similar to how in-game sounds would stack when in another tab.

### Reproducing
1. Die in a game Tetr.io and spectate another player
2. Open a new tab and spend about 30 seconds on it
3. Click back to Tetr.io
4. Watch board fly downwards

### Expected behavior
Other than bounciness from piece placement, the board shouldn't move.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**:  Chromium-Edge 80.0.361.66

**Comment by o5k** [comment]
Fixed in next patch.
