### ISSUE TITLE
Tetr.io using CPU instead of GPU

### ISSUE THREAD

**Issue by Calemy** [o5k/tetrio-issues#1291]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

-

### Describe the bug/issue

I have an igpu (my intel graphics) and a dedicated gpu (nvidia geforce rtx 3060 mobile) and no matter what i do it always uses my igpu

### Reproducing

> Graphics Settings
> Add & Select Tetr.io
> High Performance

### Expected behavior

the program switches to the dedicated gpu

### Screenshots

![grafik](https://github.com/tetrio/issues/assets/45440100/5d13899f-41a3-4172-8796-ac94b5b0c72d)

### Additional context

"easy" way to fix it would be a hardware acceleration option.

**Comment by ZaptorZap** [comment]
Have you read and tried https://tetrio.github.io/faq/troubleshooting.html#dgpu yet?

**Comment by muffinized** [comment]
ok so hardware acceleration just means that the app will luse gpu (ANY gpu) so go in graphics settings in windows settings and set priority that way

**Comment by ZaptorZap** [comment]
That's what they did:
> Graphics Settings
Add & Select Tetr.io
High Performance

This aligns with the [guide](https://tetrio.github.io/faq/troubleshooting.html#dgpu) described in the FAQ…

It'd probably help to see what the game shows when you press `F8`.

**Comment by Calemy** [comment]
I apologize for the late response but this is what i found out.

![grafik](https://github.com/tetrio/issues/assets/45440100/e3e3257e-4743-4f77-9ee2-225b2f7598d3)
it seems to show that it's using the dgpu but in reality it uses the igpu and the dgpu just copies the output frames
![grafik](https://github.com/tetrio/issues/assets/45440100/f2ece6c5-fc1b-417c-913e-b5e3fc527093)
![grafik](https://github.com/tetrio/issues/assets/45440100/f6ac525f-a62f-4ef4-9ad2-fe9044ccd6aa)
![grafik](https://github.com/tetrio/issues/assets/45440100/d4e55f55-c21c-46c4-997b-291e2cce8db8)
