### ISSUE TITLE
Ranked game did not produce 7-bag

### ISSUE THREAD

**Issue by RBYUN** [o5k/tetrio-issues#1294]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Tetrio Desktop

### Describe the bug/issue

I was in zen mode while in queue for a ranked game. If you look at each game, you'll see that the game was not 7-bag. I'm unsure if I can reproduce this.
https://tetr.io/#R:_dTUjx7Ik

### Expected behavior

I expected 7-bag

### Screenshots

![image](https://github.com/tetrio/issues/assets/5624934/e58005ad-fab8-4cf5-a570-724dbfe56aaf)

**Comment by visiblyisabelle** [comment]
enjoy the new balance patch!

(in all seriousness, this is a deliberate and not-necessarily-permanent change)

**Comment by RBYUN** [comment]
Honestly it's a fun way to add spice to everyday tetris

**Comment by Pyrolistical** [comment]
a change this major should have been in the patch notes

**Comment by ZaptorZap** [comment]
This change isn't permanent. It's also clearly shown as active before entering matchmaking now. The bag itself **is** described in [this patchnote](https://tetr.io/about/patchnotes/#chlog_6_4_4).
