### ISSUE TITLE
Game Not Loading

### ISSUE THREAD

**Issue by awesomedog213** [o5k/tetrio-issues#1296]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

MacOS 14.4.1

### Browser and version

Brave 1.65.126

### Describe the bug/issue

Everything works fine, I log in, and go to open a solo zen game and a background loads, there are sound effects and everything, music starts playing. But there is no game board, no blocks. I can hear the blocks falling but I can't see anything. I've tried turning off all trackers and blockers, I switched to Chrome, I even tried the desktop version for mac. Same results. Anyone know what's going on?

### Reproducing

1. Go to Tetr.io on Chrome browser
2. Log in or continue as guest
3. Click on Solo
4. Click on Zen
5. Click Start
6. See error

### Expected behavior

Usually, everything loads, a background appears, and blocks fall down the screen. In other words, the game appears and works.

### Screenshots

![Screenshot 2024-05-05 at 8 08 46 AM](https://github.com/tetrio/issues/assets/121458961/d4eb1b31-db2f-4cd5-8741-a9568ecee143)
Note: Name of song playing also appears, but it disappeared by the time I took the screenshot

### Console logs

![Screenshot 2024-05-05 at 8 15 56 AM](https://github.com/tetrio/issues/assets/121458961/790a16a4-4b76-4497-b3fe-0415258cc8c5)

**Comment by MxJynx** [comment]
your problem is the WEBGL mode, the chache, the graphics, and the rendering, set your settings to this and it should work (it worked for me on mac ^-^)
<img width="1711" alt="Screenshot 2024-05-07 at 1 56 06 PM" src="https://github.com/tetrio/issues/assets/158309345/f08be9c9-9543-4864-b296-65c5e1972700">
