### ISSUE TITLE
Regarding the User Okoku banned from the tetrio servers over 1 year ago

### ISSUE THREAD

**Issue by Phobos556** [o5k/tetrio-issues#1297]
Hello, dear tetrio team, i love your game more than any other game
Though over 1 year ago i misbehaved in this game and have gotten permanently banned.
Ive always been searching for any replacementof tetrio but i never found any game like it, that´s why i sincerely request an unban appeal since i have supported your game very much and waited a long time.

You are probably asking yourself why you should unban me,
I was never toxic around the tetris community, but rather a very vital part around some groups.
I learned of my mistakes considering Ban evading and multiaccounting since i no longer support any of those behaviours and am strictly against them.
I consider myself as a good tetris player and dedicate a LOT of time into such.

I hope my points are noticed and i get given another chance,
sincerely,
okoku

**Comment by ZaptorZap** [comment]
Sorry, but this repository isn't for ban appeals. For that, please visit https://tetr.io/about/support as you were instructed to in the ban dialog. Since cases such as these involve sensitive details, I'll be locking the thread now.
