### ISSUE TITLE
Zen Score Boost Tactic

### ISSUE THREAD

**Issue by B5Jet** [o5k/tetrio-issues#1303]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

TETRIO app

### Describe the bug/issue

It is a method of leveling up Zen and level through cheese layer.

### Reproducing

Go to Solo then Zen click start, now hover your pointer over Zen and scroll down to cheese layer. At this section turn messiness to 0 and cheese layer to 4. Now the tactic is set up you need to get an I piece and hold it, then top out and put it down  you will get an all clear. I know its not that fast and still takes time but it affects your player level and Zen level.

### Expected behavior

I thought it would just give a Tetris 

### Screenshots

![image](https://github.com/tetrio/issues/assets/170680936/952af6de-9d4f-4e11-8c1c-7b64cbba9d1e)

### Additional context

This is not a bug bet a tactic that maybe should be fixed. This works on TETRIO app but for me it just froze on the website.

**Comment by ZaptorZap** [comment]
Zen score does not impact the experience points you get from playing Zen mode. Zen score in general should always be taken with a grain of salt: it's trivially overwritten with flatly false data, and osk doesn't intend to solve that particular issue in the immediate future.

Zen is what **you** make of it, so if you know it's all a farce, then I don't know what you're getting out of the tedium of this strategy. At the end of the day, people don't brag about Zen scores that often.

**Comment by B5Jet** [comment]
But your player level will level up because of the Zen Tactic faster than usual .

**Comment by ZaptorZap** [comment]
It.......won't. I would ask for concrete proof, but if you ventured to get it, you would realize that the experience given from playing Zen is linear.
