### ISSUE TITLE
The replay was different

### ISSUE THREAD

**Issue by syx2567** [o5k/tetrio-issues#1304]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Microsoft Edge(ver.124.0.2478.67)

### Describe the bug/issue

Look at the third match of [this replay](https://tetr.io/#R:cL4gqPEk4),when I first watched it,it was normal.But when I watch it again,it got strange.In this match I'm sure I won,but it shows that I made much mistakes and lost.

### Reproducing

1.Go to [this replay](https://tetr.io/#R:cL4gqPEk4)
2.watch the 3rd match
3.watch it again

### Expected behavior

When you watch the replay,it should be same as the reality,no matter it is the first time or second time.

### Screenshots

https://github.com/tetrio/issues/assets/170935996/9a75e7a5-bebf-40db-961e-dec910ca5b0c

**Comment by p1nkl0bst3r** [comment]
duplicate of #886
