### ISSUE TITLE
Minor bug: Duplicate piece when hold key and multiple other keys were pressed simultaneously

### ISSUE THREAD

**Issue by hanqinilnix** [o5k/tetrio-issues#1307]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Chrome Version 125.0.6422.142 (Official Build) (64-bit)

### Describe the bug/issue

I-piece goes missing, while I managed to duplicate T-piece. 

### Reproducing

1. Press `Hold` key and `Hard Drop` key and other keys at the same time. (I think)

### Expected behavior

Expect I-piece to appear instead of duplicating T-piece.

### Screenshots

https://github.com/tetrio/issues/assets/77395961/cbc94c53-2529-448d-bbfa-ddee871e3344

**Comment by ZaptorZap** [comment]
You didn't duplicate anything. If you held and hard dropped conventionally slowly, you'd be able to tell that the I piece spawned in the center four rows. In this case, you simply held before hard dropping with a very small window, and the I piece cleared a row before being visible(there are particles and the field visually shifts downwards, indicating a line clear). The T piece simply went to your hold box, as expected when you hold.
