### ISSUE TITLE
weird ads

### ISSUE THREAD

**Issue by TrumpetsRule** [o5k/tetrio-issues#1308]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

macOS High Sierra 10.13.6

### Browser and version

firefox

### Describe the bug/issue

I see weird ads in the menu screen and even in the middle of tetra league matches and it blocks my view so i cant see what im holding, it messes me up.

### Reproducing

all i did was open tetrio and click around a little and some ads appeared, but i don't know if its just me or not.

### Expected behavior

Well I've been playing on tetrio for a few weeks now and this has never happened until today. I expected the game to run with no ads at all.

### Screenshots

![Screen Shot 2024-06-12 at 4 37 38 PM](https://github.com/tetrio/issues/assets/172544683/956d1324-1678-49fc-aae7-a62bc5a8657c)

### Console logs

im on mac i don't know how to do that

### Additional context

it also happens when im in game, and thats what bothers me the most because i can't see what im holding while in game.

**Comment by GL1TCHTheCoder** [comment]
been having this issue on chromebook. try using an adblocker?

**Comment by MrEgad** [comment]
This is happening to me to. It needs to be coded to not interfere with gameplay, or playing on this site is useless.

**Comment by GL1TCHTheCoder** [comment]
playing on pc is fine but like ads interfiering with gameplay is not ok.

**Comment by GL1TCHTheCoder** [comment]
playing on pc is fine but like ads interfiering with gameplay is not ok.
