### ISSUE TITLE
Problem Due to ads

### ISSUE THREAD

**Issue by thepanone** [o5k/tetrio-issues#1311]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Google Chrome

### Describe the bug/issue

When I was playing a game the ads forced me into a scam website which forcefully made me forfeit the game. Also the ads blocked a lot of the screen.

### Reproducing

Play with ads probably.

### Expected behavior

to be able to play with the ads on the side and not forcing me to go to a new website.

### Additional context

it was due to the ads

**Comment by ZaptorZap** [comment]
Do you use the default controls, hitting space often? This might be an extension of focus issues we've been receiving lately, where pressing `Space` may have automatically navigated towards whatever ad stole focus.
