### ISSUE TITLE
"out of focus" glitch

### ISSUE THREAD

**Issue by sgwells23** [o5k/tetrio-issues#1318]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

macbook air

### Browser and version

google 

### Describe the bug/issue

i will be playing and the screen will say out of focus. i will click into the center of the screen, with nothing else open, and it will not let me move or play. I dont know what else to do and i have to reload the screen. this knocks down my rating and i am faulted for something that is a system issue. going form a a- to a b because of how often this issue occurs. i will try opening an new screen and clicking back into tetr.io and still nothing. pls pls help sos

### Expected behavior

to help or restore my score lol 

### Screenshots

help

### Console logs

help

### Additional context

help

**Comment by ZaptorZap** [comment]
These issues have recently cropped up again (#994) but that likely wasn't what this issue report was for. Regardless, I'm closing it to try and tackle the issue of duplicates at the moment.
