### ISSUE TITLE
End of Season 1

### ISSUE THREAD

**Issue by Wonderslime** [o5k/tetrio-issues#1321]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I think that the choice to end Season 1 by granting a badge for FINAL ranking/tiering is not the right approach.  It has resulted in really weird shakeups and strangely high thresholds as people try to push to end the season at the rank they want, while totally disincentivizing continuing to play once that threshold has been reached.  

### Describe the solution you'd like

In future seasons, a "final badge" should be given for the HIGHEST achieved rank over the season, which is in-line with data kept on the Tetra Channel anyway, and which would absolutely continue to incentivize play to the end.  Surely there will still be some kind of rush, but it would be at least inconsequential (you can't "lose" something that you have gained and know that you can hold onto).  

### Describe alternatives you've considered

Certainly different options are possible, and I don't know if my idea would cause some other consequences, but I can't foresee anything major.

### Additional context

As someone who was in mid-U rank, I dropped to SS after the threshold moved close to TR 23600 (!!) and people with over 100 APM became a regular sight in SS - insanity.  I won a couple of games to eke back into U, but absolutely I have zero reason to continue to play, especially in the chaos here at the end.  I think this is a very common occurrence, and the number of people acting similarly is probably exactly what is causing the thresholds to grow as absurdly high as they have.  I believe the solution above might be a smarter/better-thought-out idea going forward.

**Comment by o5k** [comment]
ive posted about this before a bit but
this only really can work if seasons are 1 month or shorter. what "X-rank" means changes a lot over the course of 4 years! take for example, very early into S1, there were cases where 12500TR would equal S+! condensing 4 years of history into a single rank makes no sense, and it would feel very off for one person to have fought to barely manage U at the end of the season, while someone else just happened to get it while it was easier 3 years ago
even with short seasons theres an issue to this; people might play all the way at the start of the season and just happen to be more attuned to the season's changes, causing them to be overranked at the start until people catch up
all in all it doesn't really make competitive sense
