### ISSUE TITLE
Tetr.io exit warning goes ontop of everything.

### ISSUE THREAD

**Issue by WalkTheEarth** [o5k/tetrio-issues#1322]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Tiny10

### Browser and version

Firefox 128.0

### Describe the bug/issue

the exit warning goes ontop of the account thing.

### Reproducing

1. go to main menu
2. click account
3. press exit button (windows)
4. success

### Expected behavior

I expect it to close the account page and then put the exit warning on top.

### Screenshots

https://youtu.be/pUub_xL5cHE

### Console logs

n/a

**Comment by ZaptorZap** [comment]
This is definitely not clearly unintended behavior. The point of the exit confirmation is to confirm your exit. The point of the close button is to close the application completely. Why would the `Close Window` button proceed to close in-game elements?

**Comment by WalkTheEarth** [comment]
imo, the account thing should also be blurred a bit. yk?
