### ISSUE TITLE
Disconnect

### ISSUE THREAD

**Issue by Emily-Pz** [o5k/tetrio-issues#1325]
The new quickplay 2 keeps on disconnecting somewhat randomly. I can't finish 90% of the games I start because connection just dies mid-game on one session, and then it works just fine for another while (I still get absolutely pelted by garbage but that's a whole other can of worms), before starting to disconnect all over again.

**Comment by o5k** [comment]
We're looking into serverside issues. However, if you have any sorts of logs, screenshot, or information of any kind, that would be appreciated...

**Comment by WindowsFan2006** [comment]
Glad i'm not the only one that happens to me...
I have AMD Radeon, with 4GB of RAM.
However, on Desktop, unresponsive screen and disconnects constantly.
This also led to an error throwing reason "MAY NOT RECONNECT".
