### ISSUE TITLE
App opens but will not load after maintenance

### ISSUE THREAD

**Issue by boiiseuskera** [o5k/tetrio-issues#1326]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 127.0.6533.72

### Describe the bug/issue

The desktop app would open, but get stuck in "Checking for updates" no matter how long you wait, I waited two hours for it to load and it still didn't
The browser would let me log in my account but it would also get stuck in a loading screen even if I opened a replay.
![gamewontload](https://github.com/user-attachments/assets/6c5b5e31-9f59-493f-bfe2-3735ba9dca78)
I also tried reinstalling but that wouldn't fix it

### Reproducing

1. Open app
2. Get stuck in a loading screen
Browser:
1. Open tab
2. Log in
3. Get stuck in a loading screen

### Expected behavior

I expected the app to just well, open but it didn't and it wouldn't even let me log in my account in the browser.

### Screenshots

![gamewontload](https://github.com/user-attachments/assets/6cb420df-edb9-446e-99ac-366537d3cc71)
It got stuck on this screen no matter how long I waited.

### Console logs

Access to fetch at 'https://fid.agkn.com/f?apiKey=2104320612&r=https%3A%2F%2Ftetr.io%2F' from origin 'https://tetr.io' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
fid.agkn.com/f?apiKey=2104320612&r=https%3A%2F%2Ftetr.io%2F:1 
        
        
       Failed to load resource: net::ERR_FAILED
topics_frame.html?bidder=openx:16 Called iframe: pa.openx.net Array(0) 
Number of topics:  0
topics_frame.html?bidder=pubmatic:20 Called iframe: ads.pubmatic.com Array(0) 
Number of topics:  0
prebid-server.rubiconproject.com/cookie_sync:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
/api/users/me:1 
        
        
       Failed to load resource: the server responded with a status of 431 ()
VM11:57 Uncaught TypeError: Cannot read properties of null (reading 'split')
    at u.onload (eval at <anonymous> (bootstrap.js?hv=00833ee0.636882b2c23b.404ebb873724:1:1), <anonymous>:57:422932)
VM11:57 [GPT] Attempted to load GPT multiple times.
https://goo.gle/gpt-message#152
window.console.warn @ VM11:57
tetr.io/:1 Access to fetch at 'https://fid.agkn.com/f?apiKey=2104320612&r=https%3A%2F%2Ftetr.io%2F' from origin 'https://tetr.io' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.
fid.agkn.com/f?apiKey=2104320612&r=https%3A%2F%2Ftetr.io%2F:1 
        
        
       Failed to load resource: net::ERR_FAILED
cs.lkqd.net/cs?partnerId=59&redirect=https%3A%2F%2Fcm.g.doubleclick.net%2Fpixel%3Fgoogle_nid%3Dlkqd_dbm%26google_hm%3D%24%24rawlkqduserid%7Cbase64%24%24:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
match.justpremium.com/match/gg?ex_uid=e_66ee928e-7867-4485-b53d-ac9029f77a86:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
sync.e-volution.ai/3b2daa038df3c30052752dd6f56bb9f0.gif?puid=6104345939381478785&gdpr=&gdpr_consent=&us_privacy=${CCPA_CONSENT}:1 
        
        
       Failed to load resource: the server responded with a status of 400 (Bad Request)
28The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
sync.search.spotxchange.com/partner?adv_id=7025&gdpr=1&gdpr_consent=CQCajUAQCajUAEsACBENA_FoAP_gAEPgACiQJqMB5C5GQSBh8Gp3QZskeYUG9pBwYkAgAhQBA8ABSDoSNJgQwCAwAAiCACAIGQIAoHIAIAEACACEBECAYoAEogBEIECQIDECAIBEAAABACBAAARoEwNhEQAAgmIEIgQRwAANUUIMWEyASoBCglABLCAwAACQApcICEBQSAMSkMAIZGxcpILIABCDAEhIAlAPBAIpKBBMIAAADEEgwTUYDyFyIgmDD4NCugzZIcwot7SAgxIBAACgDBoACkHQkaRAhoEBgABEEAEgQMgABQOAAQAIAABAICIECgQAIRACIAIAgQGIAAQCIAEACAECAAACQBgbCIgADAMQIQAgzgACYgIQIsJkAkQAFBKACUEAAAAEgFQYAMICEkAIhAYAQyIiViQSQAQECAAAABCAeCARKUKAYQAAIGQRAgAA.cAAAD_gAAAA&addtl_consent=1~3002.3055.2343.1638.2652.2839.3292.1782.2767.495.2465.2322.445.1423.3005.1092.2559.2854.3012.3163.3126.2867.803.1558.2572.904.149.494.192.2651.2874.228.415.2687.2695.1415.1832.1307.559.2328.2400.358.2220.3025.3155.3234.3299.3330.1525.1712.2690.4531.7235.2920.2316.2805.540.1985.2510.1842.3244.3172.979.2949.2798.3251.9731.1215.424.2768.1301.2056.1186.2358.2919.3070.2481.2517.2898.3128.2373.108.259.899.1697.1944.2145.211.2411.89.1031.3253.2052.2577.3109.1786.2088.2656.2770.2922.2964.3230.3194.2669.397.2137.311.2677.3130.2569.491.2461.2684.2950.2878.117.1591.1205.2183.1579.2425.1097.2787.3010.3089.3017.3331.2571.486.1270.2133.55.2816.4131.2628.981.2822.2074.2642.1808.2527.2650.3290.2535.737.2427.2312.2542.2729.2844.3189.2887.1866&redir=https%3A%2F%2Fcm.g.doubleclick.net%2Fpixel%3Fgoogle_nid%3Dspotxchange_dbm%26google_hm%3D%24SPOTX_BASE64_USER_ID:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
sync.search.spotxchange.com/partner?adv_id=7025&gdpr=1&gdpr_consent=CQCajUAQCajUAEsACBENA_FoAP_gAEPgACiQJqMB5C5GQSBh8Gp3QZskeYUG9pBwYkAgAhQBA8ABSDoSNJgQwCAwAAiCACAIGQIAoHIAIAEACACEBECAYoAEogBEIECQIDECAIBEAAABACBAAARoEwNhEQAAgmIEIgQRwAANUUIMWEyASoBCglABLCAwAACQApcICEBQSAMSkMAIZGxcpILIABCDAEhIAlAPBAIpKBBMIAAADEEgwTUYDyFyIgmDD4NCugzZIcwot7SAgxIBAACgDBoACkHQkaRAhoEBgABEEAEgQMgABQOAAQAIAABAICIECgQAIRACIAIAgQGIAAQCIAEACAECAAACQBgbCIgADAMQIQAgzgACYgIQIsJkAkQAFBKACUEAAAAEgFQYAMICEkAIhAYAQyIiViQSQAQECAAAABCAeCARKUKAYQAAIGQRAgAA.cAAAD_gAAAA&addtl_consent=1~3002.3055.2343.1638.2652.2839.3292.1782.2767.495.2465.2322.445.1423.3005.1092.2559.2854.3012.3163.3126.2867.803.1558.2572.904.149.494.192.2651.2874.228.415.2687.2695.1415.1832.1307.559.2328.2400.358.2220.3025.3155.3234.3299.3330.1525.1712.2690.4531.7235.2920.2316.2805.540.1985.2510.1842.3244.3172.979.2949.2798.3251.9731.1215.424.2768.1301.2056.1186.2358.2919.3070.2481.2517.2898.3128.2373.108.259.899.1697.1944.2145.211.2411.89.1031.3253.2052.2577.3109.1786.2088.2656.2770.2922.2964.3230.3194.2669.397.2137.311.2677.3130.2569.491.2461.2684.2950.2878.117.1591.1205.2183.1579.2425.1097.2787.3010.3089.3017.3331.2571.486.1270.2133.55.2816.4131.2628.981.2822.2074.2642.1808.2527.2650.3290.2535.737.2427.2312.2542.2729.2844.3189.2887.1866&uid=CAESEKIlLlYa3ZSgl9tJJPEs7bo&google_cver=1:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
moatad.js:140 [Violation] Permissions policy violation: accelerometer is not allowed in this document.
b.xc.ynds @ moatad.js:140
 [Violation] Permissions policy violation: accelerometer is not allowed in this document.
b.xc.ynds @ moatad.js:140
moatad.js:140 The deviceorientation events are blocked by permissions policy. See https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md#sensor-features
b.xc.ynds @ moatad.js:140
 The deviceorientation events are blocked by permissions policy. See https://github.com/w3c/webappsec-permissions-policy/blob/master/features.md#sensor-features

**Comment by PatrykPaluch** [comment]
Cleaning app data worked for me (warning, you will need to login with password after this). 

1. Open dev tools (F12 or right click > Inspect)
2. Navigate to "Application" tab -> Storage -> Clear site data
3. Refresh page (F5). 

If you get blocked by debugger after opening dev tools then click "Deactivate breakpoints" button: ![image](https://github.com/user-attachments/assets/5c56e797-693b-47f1-832d-e112ef99be5a)

![image](https://github.com/user-attachments/assets/ef1cd260-0fc0-4f71-aaae-5fe2c6ba637c)

**Comment by boiiseuskera** [comment]
Still gets stuck in the loading screen though..

**Comment by boiiseuskera** [comment]
Even if I try with different browsers it does not load, maybe it's a computer problem? Anyone else with this issue?

**Comment by boiiseuskera** [comment]
Issue is solved, just had to reinstall the app and it loads perfectly

**Comment by quackadillyblip** [comment]
have the same issue

reinstalling does not work for me.

after i clear the storage, i can log in after restarting.
but then the app lags. i can barely set graphics to minimal and the app seems to render ok.
after i close the app and restart I need to redo the whole process again, as i'm again stuck at the loading screen.

I found this issue: 
![image](https://github.com/user-attachments/assets/4fb59175-dd42-4d8a-915c-5b9a4243a468)
