### ISSUE TITLE
Achievements Parser Error

### ISSUE THREAD

**Issue by Spentine** [o5k/tetrio-issues#1327]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Chrome 126.0.6478.185

### Describe the bug/issue

On some profiles' achievements page, only an error will appear.

### Reproducing

Visit someone's achievements page when the achievements json's `json.data[i].rt` is equal to 4 or 5 and `json.data[i].rank` is equal to 0.

### Expected behavior

The achievements page should load without error.

### Screenshots

![image](https://github.com/user-attachments/assets/8b5f30e7-2f7c-4d09-a634-8543ce22019a)

### Console logs

```
TypeError: Cannot read properties of undefined (reading '0')
    at CreateAchievement (achievements.js:108:54)
    at usermode.js:171:149
    at Array.map (<anonymous>)
    at Object.load (usermode.js:171:140)
    at async usermode.js:216:5
```

When `a.rank` is 0, it isn't a key in `PERCENTILELAX_CUTOFFS` nor `PERCENTILEVLAX_CUTOFFS`, so `cutoff` will be set to `undefined`.

### Additional context

When replacing some of the code in `ch.tetr.io/res/js/achievements.js` with

```js
const PERCENTILE_CUTOFFS = {
	// minpercentile, maxpercentile, mincount, maxcount
	[RANKS.DIAMOND]:  [0.00, 0.05,  0,  4],
	[RANKS.PLATINUM]: [0.05, 0.10,  5,  9],
	[RANKS.GOLD]:     [0.10, 0.30, 10, 29],
	[RANKS.SILVER]:   [0.30, 0.50, 30, 49],
	[RANKS.BRONZE]:   [0.50, 0.70, 50, 69],
	[RANKS.NONE]:     [0.70, 1.00,  0,  1],
};
const PERCENTILELAX_CUTOFFS = {
	// minpercentile, maxpercentile, mincount, maxcount
	[RANKS.DIAMOND]:  [0.00, 0.05,  0,  4],
	[RANKS.PLATINUM]: [0.05, 0.20,  5, 19],
	[RANKS.GOLD]:     [0.20, 0.60, 20, 59],
	[RANKS.SILVER]:   [0.60, 1.00, 60, 99],
	[RANKS.NONE]:     [-Infinity, Infinity, -Infinity, Infinity], // account for rank 0
};
const PERCENTILEVLAX_CUTOFFS = {
	// minpercentile, maxpercentile, mincount, maxcount
	[RANKS.DIAMOND]:  [0.00, 0.20, 0, 1],
	[RANKS.PLATINUM]: [0.20, 0.50, 2, 4],
	[RANKS.GOLD]:     [0.50, 1.00, 5, 9],
	[RANKS.NONE]:     [-Infinity, Infinity, -Infinity, Infinity], // account for rank 0
};
const ZENITH_CUTOFFS = {
	// minaltitude, maxaltitude
	[RANKS.DIAMOND]:  [   0,    1], // always show as full
	[RANKS.PLATINUM]: [1350, 1650],
	[RANKS.GOLD]:     [ 850, 1350],
	[RANKS.SILVER]:   [ 450,  850],
	[RANKS.BRONZE]:   [ 150,  450],
	[RANKS.NONE]:     [   0,  150],
};
```

the achievements menu works again. I simply added a new key that works for `RANKS.NONE`.

An alternate solution with these findings can be used instead.

**Comment by o5k** [comment]
Thank you for the extremely detailed issue report!! It's very much appreciated and helped us save time to work on other issues as well. This issue has been fixed on the ch site, and will be fixed ingame in a patch coming very soon.
The reason the game never anticipated percentiles over 100% btw is because the original counting code could not return such a result -- however, I was forced to rewrite counting code as a 3am frenzy ;_;
