### ISSUE TITLE
I didn't get season 1 badge

### ISSUE THREAD

**Issue by chocoland08** [o5k/tetrio-issues#1328]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome / 127.0.6533.73(the latest)

### Describe the bug/issue

Although I wasn't "?" rank, I didn't get season 1 badge. You can see I achieved "SS" rank 9 days ago in the screenshot.

### Expected behavior

.

### Screenshots

![image](https://github.com/user-attachments/assets/00f0bd2f-9d2c-47ed-8191-44d2147f36cd)

**Comment by o5k** [comment]
From my documents, you sadly just barely tipped over 100RD before the end of the season: 
![image](https://github.com/user-attachments/assets/913c0f19-e9ab-4f66-a5a7-625d0108050c)

Unfortunately, we cannot make exceptions in cases like these, so you must be treated as any other unranked player. That said, in a near update your previous season's results will show on Tetra Channel, so your SS-rank will still be publicly visible and isn't lost.

**Comment by chocoland08** [comment]
Before I achieve SS rank, I banned by AI's mistake, so my rd had reset over 100. I reduced it to get badge, but I cannot check how my rd high was. If I didn't ban by mistake, generally it would not be happen, so please give me the badge..
