### ISSUE TITLE
Classic randomizer

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#133]
### Is your feature request related to a problem? Please describe.
I want to play a random bag, but then I realize it often deals pieces in stupid order (well, duh, it's random).

### Describe the solution you'd like
NEStris had a randomizer that behaved like a Total Mayhem with a slight protection against repetition. As quoted:
> The first roll generates a value 0-7 and will accept and deal on any value other than the previous piece dealt or the dummy value of 7. The piece history is initially empty. If the first roll fails, it progresses to a second roll that generates a value 0-6 and deals that piece.

I'd imagine it should be easy to implement, considering there's several randomizer options already.
Plus it would be consistent with other options borrowing from other games (such as rotation systems).

**Comment by o5k** [comment]
Added in next patch!
