### ISSUE TITLE
Spectator Mode UI not appearing in custom lobbies

### ISSUE THREAD

**Issue by WoktopusGaming** [o5k/tetrio-issues#1332]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [x] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

TETR.IO DESKTOP v9

### Describe the bug/issue

In custom lobbies, you cannot exit spectator mode of a lobby without refreshing (F5 / CTRL+R) and, while doing so, it makes you exit the lobby you were in, which is annoying. To be clear, the spectator mode's UI isn't appearing at all.

In addition, is it normal that game countdown automatically starts after a game start? And for downloadable replays not being available for custom lobbies? I never had that happen before the update.

### Reproducing

1. Multiplayer > Room Listing
2. Select a lobby, any.
3. Play the game until you get eliminated / put yourself as a spectator (game not started) ***OR*** spectate using the button (game already started)
4. Game starts (3s countdown going off the second the game starts) or is already going, no UI for spectator mode

### Expected behavior

I expected to have the spectator UI to appear, in case I want to leave the mode, like in the Zenith Tower (previously Quick Lobby) or Royale.

### Screenshots

![image](https://github.com/user-attachments/assets/4b48745e-5acc-4359-ae31-4fc89cafd0d0 "Custom lobby which just started as spectator")

### Console logs

Console cannot log that issue.

**Comment by o5k** [comment]
Fixed in upcoming patch.
