### ISSUE TITLE
consistent tetra league connection issues with spool au-hakase

### ISSUE THREAD

**Issue by joelkoen** [o5k/tetrio-issues#1334]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

linux

### Browser and version

Chromium 126.0.6478.114 (Official Build) (64-bit) 

### Describe the bug/issue

spool au-hakase consistently crashes or the opponent disconnects when starting a Tetra League game. I have not had a single TL game when connected to hakase.

### Expected behavior

Spool server doesn't crash, I don't disconnect

### Screenshots

![Screenshot from 2024-07-28 11-48-30](https://github.com/user-attachments/assets/1ccc37a9-92c8-4908-a519-678eafc5153d)

![Screenshot from 2024-07-28 11-51-34](https://github.com/user-attachments/assets/53dd09f9-f101-489d-99bb-44e0e29181bf)

**Comment by RedshiftVelocities** [comment]
I'm experiencing similar issues on EU servers. Firefox 128.0.2 on Windows 10. I'll open a League game, I'll be connected to the opponent, but as soon as the timer reaches 0 my opponent will show as disconnected and the game will award me a win.

**Comment by RedshiftVelocities** [comment]
The problem appears to have fixed itself after I fully restarted Firefox.

**Comment by joelkoen** [comment]
spools seem stable now, osk said this has been fixed https://discord.com/channels/673303546107658242/1266610986312536155/1267527044267376833
