### ISSUE TITLE
Version 1.0.0 has boken finesse fault detection

### ISSUE THREAD

**Issue by eternal-sorrow** [o5k/tetrio-issues#1337]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Linux

### Browser and version

Firefox 128

### Describe the bug/issue

I'm accustomed to playing solo games with enabled "Retry on finesse fault". But now, after the update, I can't play. The game constantly detects false "finesse faults". Even for the simplest cases like "DAS to the side of a board and then hard drop" is sometimes detected a finesse fault. I even went to https://tetresse.harddrop.com/ to check if there is something wrong with my finesse - turns out there's not.

### Reproducing

1. Go to any of the solo games (40 lines or Blitz)
2. Enable any of the "Alert on finesse faults" or "Retry on finesse faults"
3. Start a game.
4. Play with perfect finesse
5. Get a lot of false "finesse faults" detected.

### Expected behavior

Only detect finesse fault when there actually was a fault.

**Comment by cheezeygeek** [comment]
Glad I'm not the only one experiencing this issue. It happens with the finesse tracker in zen mode too. Here's a more minimal way to reproduce it:

1. (Optional, makes it easier) Increase your DCD time
2. Go to zen mode, switch the display to "Efficiency"
3. DAS to the side of the board
4. Hard drop while still holding the movement key
5. Release the movement key before the DAS kicks in for the 2nd piece
6. Hard drop

The 2nd piece will be counted as a fault.

**Comment by eternal-sorrow** [comment]
This one seems fixed.
