### ISSUE TITLE
1-8 stacking badge error

### ISSUE THREAD

**Issue by baokhue2005** [o5k/tetrio-issues#1338]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Ubuntu 22.04.4 LTS

### Browser and version

Desktop client

### Describe the bug/issue

playing 40 lines all quads in column 2 or 9 doesn't give the 1-8 stacking badge

### Reproducing

https://tetr.io/#R:f5f300e6ca38
playing exactly like the 40-line replay won't give the badge

### Expected behavior

user khuepr123(me) receive the 1-8 stacking badge

### Console logs

bootstrap.js?hv=c84f44cf.4abc44b5d4ee.4e838bc69d72:2 Bootstrapping for hardver c84f44cf.4abc44b5d4ee.4e838bc69d72
VM191:34 webgl backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM191:34
VM191:34 cpu backend was already registered. Reusing existing backend factory.
t.registerBackend @ VM191:34
VM191:34 Platform browser has already been set. Overwriting the platform with [object Object].
t.setPlatform @ VM191:34
VM191:56 TETR.IO
VM191:56 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
VM191:56 Using the Desktop Client
VM191:56 Up to date. Local version 1.0.0-production | Commit c84f44cf@master (7/28/2024, 8:29:14 AM) | Server cycle 4abc44b5d4ee | Build 4e838bc69d72 (7/28/2024, 8:43:42 AM)
VM191:56 Loading Ceriad provider...
VM191:56 The method setUserId is registered more than once in "_paq" variable. Only the last call has an effect. Please have a look at the multiple Matomo trackers documentation: https://developer.matomo.org/guides/tracking-javascript-guide#multiple-piwik-trackers
window.console.error @ VM191:56
VM191:56 GTM loaded.
VM191:56 home-lb mounted, now 1 mounts
VM191:56 PixiJS 6.1.3 - WebGL 2
VM191:56 - Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tetrio-desktop/9.0.0 Chrome/122.0.6261.70 Electron/29.1.0 Safari/537.36 -CPU: 4-coreMemory: ~8 GBConnection: 1.6 Mbps, 250ms RTT [3g]
VM191:56 Renderer: ANGLE (Intel, Mesa Intel(R) HD Graphics 520 (SKL GT2), OpenGL 4.6)
VM191:56 InitialConnect > Obtaining Ribbon endpoint...
VM191:56 RAMP loaded.
VM191:56 InitialConnect > Obtained Ribbon endpoint /ribbon/gil and 26 spools, fallback available.
VM191:56 InitialConnect > Getting a spool...
VM191:56 InitialConnect > Spool > Spooling started
VM191:56 fun-hooks: referenced 'adpod' but it was never created
window.console.warn @ VM191:56
VM191:56 InitialConnect > Spool >    60+141ms ap-north-madoka [KR] v4 // 0.296875, 0.265625, 0.265625
VM191:56 InitialConnect > Spool >    49+142ms ap-north-homura [KR] v4 // 0.203125, 0.25, 0.265625
VM191:56 InitialConnect > Spool >    69+133ms ap-north-hina [KR] v4 // 0.046875, 0.078125, 0.046875
VM191:56 InitialConnect > Spool > Spooled ap-north-homura!
VM191:56 InitialConnect > Obtained spool ap-north-homura (ap-north-homura.spool.tetr.io) [KR].
VM191:56 Ceriad provider launched.
VM191:56 home-lb unmounted, now 0 mounts
VM191:56 multiplayer-lb mounted, now 1 mounts
833Third-party cookie will be blocked. Learn more in the Issues tab.
ib.adnxs.com/async_usersync?cbfn=queuePixels:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
(index):1 Access to fetch at 'https://btlr.sharethrough.com/universal/v1?supply_id=WYu2BXv1' from origin 'https://tetr.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
btlr.sharethrough.com/universal/v1?supply_id=WYu2BXv1:1 
        
        
       Failed to load resource: net::ERR_FAILED
VM191:56 multiplayer-lb unmounted, now 0 mounts
VM191:56 multiplayer-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 multiplayer-lb unmounted, now 0 mounts
VM191:56 ResumeRespool > Obtaining Ribbon endpoint...
VM191:56 ResumeRespool > Obtained Ribbon endpoint /ribbon/sakuya and 26 spools, fallback available.
VM191:56 ResumeRespool > Getting a spool...
VM191:56 ResumeRespool > Spool > Spooling started
VM191:56 ResumeRespool > Spool >    50+141ms ap-north-homura [KR] v4 // 0.296875, 0.296875, 0.28125
VM191:56 ResumeRespool > Spool >    52+143ms ap-north-madoka [KR] v4 // 0.25, 0.234375, 0.25
VM191:56 ResumeRespool > Spool >    62+134ms ap-north-nitta [KR] v4 // 0.046875, 0.078125, 0.015625
VM191:56 ResumeRespool > Spool > Spooled ap-north-homura!
VM191:56 ResumeRespool > Obtained spool ap-north-homura (ap-north-homura.spool.tetr.io) [KR].
VM191:56 sysroom-mpu mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 sysroom-mpu unmounted, now 0 mounts
VM191:56 multiplayer-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 multiplayer-lb unmounted, now 0 mounts
VM191:56 home-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 home-lb unmounted, now 0 mounts
VM191:56 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://tetr.io/res/font/cr.ttf
152The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
VM191:56 home-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 home-lb unmounted, now 0 mounts
VM191:56 solo-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 solo-lb unmounted, now 0 mounts
VM191:56 AmbientRespool > Starting ambient respool.
VM191:56 AmbientRespool > Obtaining Ribbon endpoint...
VM191:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/gil and 26 spools, fallback available.
VM191:56 AmbientRespool > Getting a spool...
VM191:56 AmbientRespool > Spool > Spooling started
VM191:56 AmbientRespool > Spool >    50+133ms ap-north-nitta [KR] v4 // 0.1875, 0.109375, 0.046875
VM191:56 AmbientRespool > Spool >    47+131ms ap-north-hina [KR] v4 // 0.015625, 0.0625, 0.046875
VM191:56 AmbientRespool > Spool >    56+141ms ap-north-madoka [KR] v4 // 0.1875, 0.1875, 0.21875
VM191:56 AmbientRespool > Spool > Spooled ap-north-hina!
VM191:56 AmbientRespool > Obtained spool ap-north-hina (ap-north-hina.spool.tetr.io) [KR].
VM191:56 AmbientRespool > Obtained new token, no significant ping advantage 488ms → 357ms.
VM191:56 AmbientRespool > Starting ambient respool.
VM191:56 AmbientRespool > Obtaining Ribbon endpoint...
VM191:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/imamiya and 26 spools, fallback available.
VM191:56 AmbientRespool > Getting a spool...
VM191:56 AmbientRespool > Spool > Spooling started
VM191:56 AmbientRespool > Spool >    45+141ms ap-north-homura [KR] v4 // 0.21875, 0.296875, 0.328125
VM191:56 AmbientRespool > Spool >    49+134ms ap-north-nitta [KR] v4 // 0, 0.046875, 0.015625
VM191:56 AmbientRespool > Spool >    95+131ms au-hakase [AU] v4 // 0.0625, 0.046875, 0
VM191:56 AmbientRespool > Spool > Spooled ap-north-nitta!
VM191:56 AmbientRespool > Obtained spool ap-north-nitta (ap-north-nitta.spool.tetr.io) [KR].
VM191:56 AmbientRespool > Obtained new token, no significant ping advantage 375ms → 365ms.
VM191:56 soloresults-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://tetr.io/res/font/cb.ttf
VM191:56 soloresults-lb unmounted, now 0 mounts
VM191:56 soloresults-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 AmbientRespool > Starting ambient respool.
VM191:56 AmbientRespool > Obtaining Ribbon endpoint...
VM191:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/chihaya and 26 spools, fallback available.
VM191:56 AmbientRespool > Getting a spool...
VM191:56 AmbientRespool > Spool > Spooling started
VM191:56 AmbientRespool > Spool >    45+144ms ap-north-homura [KR] v4 // 0.515625, 0.296875, 0.28125
VM191:56 AmbientRespool > Spool >    45+141ms ap-north-madoka [KR] v4 // 0.1875, 0.203125, 0.203125
VM191:56 AmbientRespool > Spool >    47+135ms ap-north-hina [KR] v4 // 0.15625, 0.078125, 0.03125
VM191:56 AmbientRespool > Spool > Spooled ap-north-homura!
VM191:56 AmbientRespool > Obtained spool ap-north-homura (ap-north-homura.spool.tetr.io) [KR].
VM191:56 AmbientRespool > Obtained new token, already on best available spool.
VM191:56 soloresults-lb unmounted, now 0 mounts
VM191:56 home-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 home-lb unmounted, now 0 mounts
VM191:56 home-lb mounted, now 1 mounts
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
ib.adnxs.com/ut/v3/prebid:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
VM191:56 AmbientRespool > Starting ambient respool.
VM191:56 AmbientRespool > Obtaining Ribbon endpoint...
VM191:56 AmbientRespool > Obtained Ribbon endpoint /ribbon/kotarou and 26 spools, fallback available.
VM191:56 AmbientRespool > Getting a spool...
VM191:56 AmbientRespool > Spool > Spooling started
VM191:56 AmbientRespool > Spool >    46+142ms ap-north-homura [KR] v4 // 0.21875, 0.296875, 0.28125
VM191:56 AmbientRespool > Spool >    45+132ms ap-north-nitta [KR] v4 // 0.0625, 0.015625, 0
VM191:56 AmbientRespool > Spool >    46+141ms ap-north-madoka [KR] v4 // 0.15625, 0.1875, 0.1875
VM191:56 AmbientRespool > Spool > Spooled ap-north-homura!
VM191:56 AmbientRespool > Obtained spool ap-north-homura (ap-north-homura.spool.tetr.io) [KR].
VM191:56 AmbientRespool > Obtained new token, already on best available spool.
74 log entries are not shown.

### Additional context

i think that the achievement creator (or the code) intended that ALL of the quads be in column 2 or column 9, but given the description it should be fine to do both

**Comment by ZaptorZap** [comment]
osk said earlier that Mr. Boardwide had to be **all Quads.** I imagine the same issue happened here. You cleared a single, so it wasn't strictly all "10 Quads". That's my hypothesis anyways.

Furthermore, the description uses the exclusive `or`, not `and`. I'm not sure how the game reacts to doing Quads in both 2 and 9, but either way, your assumption is illogical.

**Comment by o5k** [comment]
> I'm not sure how the game reacts to doing Quads in both 2 and 9, but either way, your assumption is illogical.

It must be all in column 2 OR all in column 9. Mixing the two is not allowed. In addition, they must be all quads. (final line count must be 40 exact)
