### ISSUE TITLE
Non-standard board widths (eg. 4-wide and 15-wide) don't clear lines properly

### ISSUE THREAD

**Issue by LittleLilyBun** [o5k/tetrio-issues#1339]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

KDE Neon 6.0 (Kernel 6.5.0-45)

### Browser and version

TETR.IO Desktop V8

### Describe the bug/issue

When playing with a custom board width, lines do not clear properly, and in the case of >10 wide boards, there are inaccessible lanes on the right side of the board.

### Reproducing

1. Create a custom solo game
2. Set board width to anything other than 10
3. Attempt to clear a line

### Expected behavior

Lines should clear and all lanes should be accessible.

### Screenshots

![image](https://github.com/user-attachments/assets/7f2b5d96-8618-4fd2-ab50-2e968c6d9ced)

https://github.com/user-attachments/assets/be8bf07a-14c6-4311-96ba-44541efaefe5

### Additional context

The issue occurs in both TETR.IO Desktop v8 and Firefox 128

**Comment by ZaptorZap** [comment]
If I understand properly, this is already fixed. Just waiting on a patch/server restart to apply it.

**Comment by LittleLilyBun** [comment]
Issue seems to be fixed after 1.0.1
