### ISSUE TITLE
API documentation needs update for user seach

### ISSUE THREAD

**Issue by s1072489** [o5k/tetrio-issues#1340]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Firefox 129.0b9

### Describe the bug/issue

When trying to search for a tetrio user by discord userid, only a 404 page is shown

### Reproducing

attempt to search for user with tetrio api eg. https://ch.tetr.io/api/users/search/825232373481865226

### Expected behavior

json response with tetrio user id + name

**Comment by ZaptorZap** [comment]
Yeah, much of the Tetra Channel API has been upended. I don't know the endpoint this was moved to either, but this most likely isn't a bug. The Tetra Channel needs to know _which service_ you're searching, as now TETR.IO supports 6(Discord, Twitch, Youtube, 𝕏(formerly Twitter), Steam, and Reddit). This isn't a bug—https://tetr.io/about/api/ needs to be updated.

**Comment by o5k** [comment]
The search endpoint has been readded. Please note that you must now prepend the Discord user ID with the string `discord:`.
