### ISSUE TITLE
Badges do not show up on profile when completed

### ISSUE THREAD

**Issue by aaaathehooman** [o5k/tetrio-issues#1344]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

Microsoft Edge 126.0.2592.113

### Describe the bug/issue

When the requirement for a badge is completed (e.g. 20 TSD) it does not show up in the badges on the profile page. Not sure if it works or not for multiplayer badges.

### Reproducing

1. Complete requirements for a badge
2. Go to profile page in the main menu

### Expected behavior

When the badge is completed, it shows up on the profile page

### Screenshots

![image](https://github.com/user-attachments/assets/ca56a355-fa65-4f5a-bbf7-21044da71c88)

![image](https://github.com/user-attachments/assets/eeb2c453-17ab-4e1c-b310-eff17c1ebfed)

### Additional context

when a badge is completed, it shows the achievement but not the badge on the profile page.

**Comment by ZaptorZap** [comment]
This is intended. Badges for Secret Grade, 20TSD, and All Clearing 10 times in 40L are no longer awarded. Existing badges will be kept to signify Alpha players' legacies.

You may instead choose **feature** these achievements on your profile. Visit the ingame Tetra Channel to do that:
![image](https://github.com/user-attachments/assets/8d83ed62-929d-490a-8f67-d8c9ac361734)

![image](https://github.com/user-attachments/assets/d8aae064-3903-4b87-9ffa-6d3ff0b2c9d9)

The option to feature an achievement is plastered at the top from that screen.

**Comment by aaaathehooman** [comment]
so this means that i missed the window to get the badges by a week -_-
