### ISSUE TITLE
Cannot set left d-pad key using Pokken Tournament DX Pro Pad

### ISSUE THREAD

**Issue by lpla** [o5k/tetrio-issues#135]
### Describe the bug/issue
While setting keys to use the Pokken Tournament DX Pro Pad, left key from the d-pad is not registered.

### Reproducing
1. Go to 'Config' in the main menu
2. Click on 'Move falling piece left'
3. Press left key in your controller and nothing happens.

### Expected behavior
Key gets registered like all other keys in the controller.

### Screenshots
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 17 17 37" src="https://user-images.githubusercontent.com/1533393/76334751-d21e5680-62f3-11ea-9e74-80bf39376cbe.png">

### Your setup
 - **OS and version**: macOS Catalina 10.15.3, MacBook Pro (15-inch, 2017)
 - **Browser and version**: Chrome 80.0.3987.132

**Comment by o5k** [comment]
Does the gamepad work on https://html5gamepad.com/ ?

**Comment by lpla** [comment]
Yep, it works and registers all positions of d-pad. Here are all positions of the d-pad registered by html5gamepad (center or no press, left, top-left, top, top-right, right, bottom-right, bottom, bottom-left):

<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 10 18" src="https://user-images.githubusercontent.com/1533393/76360056-921f9980-631c-11ea-8614-539b1c51bcab.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 10 23" src="https://user-images.githubusercontent.com/1533393/76360060-9350c680-631c-11ea-8550-d1490acce807.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 11 01" src="https://user-images.githubusercontent.com/1533393/76360061-93e95d00-631c-11ea-9952-eb31140e6c61.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 11 13" src="https://user-images.githubusercontent.com/1533393/76360062-9481f380-631c-11ea-9ca7-627aa2bde1ee.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 11 17" src="https://user-images.githubusercontent.com/1533393/76360063-951a8a00-631c-11ea-859f-b10270070d51.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 11 24" src="https://user-images.githubusercontent.com/1533393/76360064-964bb700-631c-11ea-8eca-72b001c2eaca.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 11 30" src="https://user-images.githubusercontent.com/1533393/76360067-96e44d80-631c-11ea-8ebf-c2fc877c25a0.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 11 34" src="https://user-images.githubusercontent.com/1533393/76360070-977ce400-631c-11ea-8177-a0bc26aef44d.png">
<img width="1698" alt="Captura de pantalla 2020-03-10 a las 22 11 39" src="https://user-images.githubusercontent.com/1533393/76360071-98157a80-631c-11ea-8d5a-d81bcc11c0ef.png">

**Comment by o5k** [comment]
that seems to only be activating one axis though, whereas i'd expect there to be 2?

**Comment by lpla** [comment]
Yes, Chrome is detecting the d-pad as a joystick with two axis. Safari, in the same test, is detecting the d-pad as individual buttons. See this screenshot in Safari pressing only left d-pad button:

<img width="1526" alt="Captura de pantalla 2020-03-11 a las 8 53 05" src="https://user-images.githubusercontent.com/1533393/76394396-bc517580-6375-11ea-9869-ef37657c97e0.png">

**Comment by lpla** [comment]
Firefox has the same issue as Chrome, I cannot set left d-pad in config. And it gets detected:

<img width="1392" alt="Captura de pantalla 2020-03-11 a las 8 59 15" src="https://user-images.githubusercontent.com/1533393/76394938-97a9cd80-6376-11ea-8a04-d71067f138fc.png">

**Comment by Wirtualnosc** [comment]
With chrome being an example, does any other axis than 9 actually activate? Similarly with Firefox and axis othern than axis 0.

**Comment by lpla** [comment]
Everything else stays at 0, as shown in the screenshots.

**Comment by o5k** [comment]
Seems to be a browser/gamepad issue

**Comment by lpla** [comment]
For the record, I retested with latest version and issue still happens. And gamepad works well in other programs like emulators. Browser shouldn't be an issue here as it recognises the d-pad directions well as previous screenshots shown, probably because it is a Generic HID Controller.

I don't know if anyone had issue with other kind of controllers which protocol could be similar.

**Comment by kreefonghong** [comment]
oh!  I am experiencing a similar issue!  I posted on reddit and discord and they said to come here:  

"Has anyone had success setting up the dpad on ps3/ps4 controllers on tetr.io?

Up on the dpad shows as negative axis 9, down and right both show as positive axis 9, left doesn't register at all. It's the same on both the app and the website.

The analogue sticks appear to work, but I find them too imprecise for tetris."

https://www.reddit.com/r/Tetris/comments/jrcm6f/cant_get_tetrio_to_recognize_dpad_inputs_on_ps3/?utm_medium=android_app&utm_source=share

Someone replied and said there's some kind of 3rd party app I can use.  I'll look around and see what I can find.
