### ISSUE TITLE
Can't change targeting mode in Quick Play and no targeting options show up

### ISSUE THREAD

**Issue by zbelios** [o5k/tetrio-issues#1351]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11 Pro

### Browser and version

Firefox 128.0.3

### Describe the bug/issue

When playing Quick Play, targeting modes do not work. They do not appear on the screen and pressing keys to change modes does nothing.

### Reproducing

1. Join a round of Quick Play through the menu.
2. When in-game, notice that the targeting options do not appear.
3. Try pressing keybinds for targeting modes; nothing happens.

### Expected behavior

That targeting modes would work and appear as options on the screen.

### Screenshots

![Screenshot_3](https://github.com/user-attachments/assets/927eb7c2-ec34-4f32-84fa-a918a5106eee)

### Additional context

Targeting modes work everywhere else except for Quick Play.

**Comment by visiblyisabelle** [comment]
Quick Play 2 doesn't have targeting modes.
