### ISSUE TITLE
Active Replay During Tetra League Match Will Play Over Match

### ISSUE THREAD

**Issue by Toafu** [o5k/tetrio-issues#1354]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Desktop Client

### Describe the bug/issue

When entering a Tetra League (TL) match while watching a Replay, the replay persists in the background during the match, obscuring the current game. If the Replay plays a new round during the TL match, it completely hides the Tetra League match behind it.
Once the round in the Replay ends, the controls reappear, allowing the user to navigate through the menus mid-TL match. However, the user loses control of their board.
When the current TL round ends, the menus disappear and the user can play as normal.

### Reproducing

1. Queue for Tetra League
2. Open any Replay
3. Get into a Tetra League match before the current Replay round ends.
- If the Replay round ends before the match is over, attempt to navigate around the menus

### Expected behavior

The Replay terminates upon MATCH FOUND and the Tetra League match plays as normal.

### Screenshots

![image](https://github.com/user-attachments/assets/d537a062-8f9b-47dd-bd13-be68fb991fac)
![image](https://github.com/user-attachments/assets/53ba312e-2cf4-4e31-b88b-7033e370f733)
![image](https://github.com/user-attachments/assets/365b360f-5c74-4465-b0a1-43467a0c65d7)
![image](https://github.com/user-attachments/assets/e2c4fd99-6333-4eb7-a987-fe5eba5509f1)
![image](https://github.com/user-attachments/assets/f203451c-960f-4db2-bda8-7bd9bd1cb370)

### Additional context

If the transition controls in the bottom left are set such that another round plays automatically, that round is overlaid on top of the current match, obscuring the Tetra League boards.

**Comment by o5k** [comment]
(This has been fixed.)
