### ISSUE TITLE
Handling limit in multiplayer

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#136]
### Is your feature request related to a problem?
- Some people might enjoy playing in a larger crowd, but their skill might be quite low. They might get overwhelmed by better players.
- Disabling hard drop doesn't guarantee that the soft drop won't act in a similar way; with maximum SDF and minimum lock delay, you achieve the same result. This might be especially important in games emulating NES style gameplay.

### Describe the solution you'd like
DAS, ARR and SDF limits for custom multiplayer lobbies. Inexperienced players could play there for more even fights, and some more setting demanding custom games might use those for a better quality gameplay.

**Comment by o5k** [comment]
Added in next patch!
