### ISSUE TITLE
Quick play player rendering lag

### ISSUE THREAD

**Issue by Rebtao** [o5k/tetrio-issues#1360]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

windows 11

### Browser and version

edge 127.0.2651.98

### Describe the bug/issue

The simplified player rendering is not working in quick play, adding lag for low end computers, also the option to hide other player in quick play is bind to minimal graphics setting which is not the case for most option and would allow the player to choose better graphics while using less cpu.

### Expected behavior

We should have the possibility to disable player rendering in quick play without using minimal setting and the simplified player thumbnail should be working in quickplay.

**Comment by o5k** [comment]
Added in next patch.
