### ISSUE TITLE
Friend List Scroll Malfunction While Spectating Quickplay

### ISSUE THREAD

**Issue by Sheeep77** [o5k/tetrio-issues#1363]
### Checklist

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Chrome 127

### Describe the bug/issue

While spectating a player in quickplay you are unable to scroll on your friends list. Rather, it scrolls down within quickplay (up or down the tower)

### Reproducing

1. Multiplayer
2. Quickplay
3. Click on any players currently playing to spectate
4. Open the side menu (tab for most)
5. Friends list
6. Scroll

### Expected behavior

It is expected that you're able to scroll down your friends list

**Comment by Sheeep77** [comment]
username: EmperorSheep

**Comment by o5k** [comment]
Fixed - F5 to receive the fix.
