### ISSUE TITLE
Invalid percentiles (>100%) appear in 'Country Rank' and 'Global Rank'

### ISSUE THREAD

**Issue by 035966-L3** [o5k/tetrio-issues#1369]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 11

### Browser and version

TETR.IO Desktop v9

### Describe the bug/issue

Invalid percentiles (101.52% and 100.18%) appear in 'Country Rank' and 'Global Rank'.

### Reproducing

1. Go to QUICK PLAY 2
2. Finish a game with an altitude of 0.1m
3. See the invalid percentiles

### Expected behavior

The percentiles should be between 0% and 100%.

### Screenshots

![pAPXf2R.png](https://s21.ax1x.com/2024/08/20/pAPXf2R.png)

**Comment by o5k** [comment]
This issue has been resolved.
