### ISSUE TITLE
Someone joining quick play reports as if they were joining your lobby

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#137]
### Describe the bug/issue
I had been checking out a blitz room, and decided I didn't like it and went back to the quick play lobby, when I got the strangest notification (below). I'm really not sure what happened so I can't help much. You can see it says that the player joined _my_ room, when I neither own a) quick play or b) the blitz room.

### Reproducing
I'm not sure exactly what caused it, but you can try this:
1. Go to a public room while the quick play countdown is going.
2. Leave, and rejoin quick play (the timer should still be going).
3. If somebody joins quick play/the room (?) you get the notification seen below.

### Expected behavior
It... shouldn't.

### Screenshots
[Here](https://i.imgur.com/7GT7nWj.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.66

**Comment by o5k** [comment]
Fixed in next patch.
