### ISSUE TITLE
Clutch Factor Achievement/Badge

### ISSUE THREAD

**Issue by gooeye** [o5k/tetrio-issues#1374]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

There's currently no record of how many matches have been clutched out on the match point.

### Describe the solution you'd like

To find out how clutch of a player one is, a badge / achievement that tracks the number of matches won in Tetra League on the match point can be added (i.e. In a best of 5, winning the 5th game would give you a +1 on the clutch factor badge).

### Describe alternatives you've considered

That is all, thanks!

**Comment by visiblyisabelle** [comment]
This was removed as it encouraged players to throw rounds for the badge.
