### ISSUE TITLE
Counter Clockwise Bug on I Piece

### ISSUE THREAD

**Issue by aydenbush** [o5k/tetrio-issues#1382]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Opera GX

### Describe the bug/issue

I tried to do a Mech TSD, There was a part where I need to place the I piece to the 4th column. I wanted to finesse 100% but the bug makes it impossible to achieve.

### Reproducing

1. Wait for an I piece
2. Rotate it Counter-Clockwise
3. The I piece will rotate Clockwise Instead of Counter-clockwise

### Expected behavior

I expect the I piece to go to 5th column when I press Counter-clockwise.

### Screenshots

![image_2024-09-07_215607089](https://github.com/user-attachments/assets/8a58986b-7e17-4e99-ac62-fd3e9d48623e)
![image_2024-09-07_215627450](https://github.com/user-attachments/assets/5788e198-46ca-40f2-a1d9-197d99275311)

**Comment by ZaptorZap** [comment]
Please move your mouse to the right side of the screen and re-enable SRS+. It sounds to me like it got deselected.
![image](https://github.com/user-attachments/assets/9e497907-f99a-43df-9b37-68d7c4185750)

**Comment by aydenbush** [comment]
Ohh I see. I didn't notice that, thank you!
