### ISSUE TITLE
Account deleted

### ISSUE THREAD

**Issue by XYLOSHD** [o5k/tetrio-issues#1393]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Opera GX (LVL 6)

### Describe the bug/issue

I have not touched this game for so long and want to play it back but it keeps saying account deleted. What happened I paid for it before

### Expected behavior

While trying to login, it says, "account deleted"

**Comment by ZaptorZap** [comment]
Our apologies, but this forum is not for account support. Please email `support@tetr.io`  with the username you're attempting to register with.

Deleted accounts are permanently reserved to prevent impersonation. This is intentional and we do not anticipate that to change soon.
