### ISSUE TITLE
Textures not loading properly

### ISSUE THREAD

**Issue by Fuguety** [o5k/tetrio-issues#1395]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

OperaGX

### Describe the bug/issue

So, I was playing Tetrio on class, and the internet is ass. When I booted the game on the browser, the textures almost didnt load, making this minimalistic look. I think this should be a option, pls see screenshot for more detalis.
 
PS: Ik that reloading the tab would fix it, but I wanted to let u guys know how cool it looked and maybe consider making it a feature? 0.0

### Reproducing

Disconect and connect while loading (I think)

### Expected behavior

Fully loaded pictures

### Screenshots

![image](https://github.com/user-attachments/assets/025645bb-2bc6-4159-9b8a-9e01904f5caa)

**Comment by ZaptorZap** [comment]
This doesn't seem to be a valid request or bug report in any regard. As you said, this is a deliberate fallback and it is working as intended. Skins are discussed at #359.
