### ISSUE TITLE
tetr.io to launch on multiple platforms

### ISSUE THREAD

**Issue by ellokey** [o5k/tetrio-issues#1406]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

players can find it difficult to play on keyboard, or don't have a device they can play TETR.IO on.

### Describe the solution you'd like

a release on other platforms. mobile would be easy, but console will be harder.

### Describe alternatives you've considered

encouraging players to use bluetooth keyboards/controllers, but that can be laggy, uncomfortable, and the board can be too small.

**Comment by visiblyisabelle** [comment]
not happening. use a wired controller if you're worried about lag.
