### ISSUE TITLE
Option to disable information about currenly playing track

### ISSUE THREAD

**Issue by ztx-lyghters** [o5k/tetrio-issues#1407]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I'm playing with the in-game music turned off, therefore I'd also like not to see any supposedly playing track titles appearing on the screen.

### Describe the solution you'd like

An option to disable any information about currently playing in-game music would be great.

### Describe alternatives you've considered

I don't see any way to disable it currently.

**Comment by ZaptorZap** [comment]
Fairly certain there's a legal risk associated, so this is probably not happening. Most of TETR.IO's soundtrack is by the royalty free [HURT RECORD](https://www.hurtrecord.com/about/terms.html). Their terms aren't strict, but ignoring attribution would pretty easily become a violation of them.

**Comment by ztx-lyghters** [comment]
> Fairly certain there's a legal risk associated, so this is probably not happening. Most of TETR.IO's soundtrack is by the royalty free [HURT RECORD](https://www.hurtrecord.com/about/terms.html). Their terms aren't strict, but ignoring attribution would pretty easily become a violation of them.

To be honest, I had that thought. Hopefully, something can be done. ~For example, forcing the music off, if the "currently playing" information is disabled~

**Comment by ZaptorZap** [comment]
Well, that would be jank. If you mute the ingame music I believe the attribution already isn't shown.

**Comment by ztx-lyghters** [comment]
> Well, that would be jank. If you mute the ingame music I believe the attribution already isn't shown.

That's the problem - it is being shown. I also don't see the option to "mute" the music, so I just lowered it to 0%. The music is still playing in the background, just without any volume, and track titles are being shown when the track changes. Did I miss something in the settings?

**Comment by ZaptorZap** [comment]
Then I'm afraid you are experiencing a bug of some kind. This works on Firefox, shown below: 

https://github.com/user-attachments/assets/1e1121bb-f3f4-4419-a8a0-0cb51c298513

I tried on Desktop and it similarly worked there too.

**Comment by ztx-lyghters** [comment]
> Then I'm afraid you are experiencing a bug of some kind. This works on Firefox, shown below:
> guess-.291.mp4
> 
> I tried on Desktop and it similarly worked there too.

Oh! That's weird! I had 0% volume instead of "mute" for some reason, I tried to re-apply it by moving the slider back and forth and now it does say "mute", the track titles are gone as well! The weird part is that I cannot reproduce the "0%" thing now.
In any case, thank you for your help!
