### ISSUE TITLE
Заблокировали аккаунт

### ISSUE THREAD

**Issue by Tearjerker1** [o5k/tetrio-issues#1410]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

yandex

### Describe the bug/issue

My account with the nickname Tearjerker has been blocked and I think this is a mistake. No one is playing on my account, just me. 
![ывывы](https://github.com/user-attachments/assets/10ee122c-c71f-474d-ba97-38fd9805fea5)

### Expected behavior

Надеюсь на ответ

**Comment by visiblyisabelle** [comment]
https://tetr.io/about/support/
