### ISSUE TITLE
Blank screen when you join quick play as it starts

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#142]
it isn't very reliable to reproduce (I wasn't able to when trying to reproduce on demand), but it happened to me and someone else a few times now so I guess it's worth throwing that in just in case

screenshot by NoFontNL
![image](https://user-images.githubusercontent.com/6901295/76461047-0e76b300-63d7-11ea-88f4-7f45545d54c9.png)

**Comment by o5k** [comment]
This might be fixed in the next patch, please let me know whether it is so I can close the issue then.

**Comment by o5k** [comment]
DIdn't hear from this, assuming fixed
