### ISSUE TITLE
ADs are LAGGING THE GAME 

### ISSUE THREAD

**Issue by mevcutonur** [o5k/tetrio-issues#1422]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

WINDOWS 10

### Browser and version

CHROME 

### Describe the bug/issue

Listen pal. I know you want your money and that's okay. The newly added ads cause a freeze when new ads load. 

### Reproducing

Open game.
Play 40 lines.

### Expected behavior

I expected a smooth gameplay

**Comment by wonsunil** [comment]
Don't just say it's not a supporter billing inducement, please delete the ad from the in-game session

**Comment by wonsunil** [comment]
LAGGING, which is caused by advertising, is cutting my score by a few thousand points and has even been demoted a few times. If not, please delete the ad in the middle of the game.

Just now, the rank was lowered due to the lag caused by the commercial

**Comment by wonsunil** [comment]
The lags caused by advertising occur slightly differently each time, shaking my senses.

This bug is a bug that should come first and foremost

Additionally, do you know that there are also bugs that keep changing the screen size whenever there is an advertising bug?

**Comment by vooenix** [comment]
Man...
Just use an adblocker or TETR.IO Desktop to turn off the ads.
For desktop client: If v9 lags, try to download v8 from https://tetr.io/about/desktop/history/
To turn off ads in-game in TETR.IO Desktop, go to Config, then click to TETR.IO Desktop. You will see "Disable Third-Party Advertisements" option. at bottom.

**Comment by mevcutonur** [comment]
Thanks dude... I actually couldn't find that setting

**Comment by wonsunil** [comment]
holy... Thank you for letting me know that there is an ad block in the settings
