### ISSUE TITLE
Old replays dragged into the game say "file load failed!"

### ISSUE THREAD

**Issue by Denn159** [o5k/tetrio-issues#1428]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Version 1.3.1

### Describe the bug/issue

I have custom game replays from 2021-2023. Whenever i try dragging them into the game it gives me a "file load failed" error. New replays work

### Reproducing

1. get any old replay
2. drag replay into game
3. error occurs

### Expected behavior

i expected it to work

**Comment by ZaptorZap** [comment]
This is expected. Replays from before [Beta](https://tetr.io/about/patchnotes/#chlog_BETA_1_0_0) are not supported. A remedy may exist some day in the future, but there are no concrete plans to address this in any capacity.
