### ISSUE TITLE
40L and Blitz issues

### ISSUE THREAD

**Issue by someonehere1234** [o5k/tetrio-issues#1429]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Windows 10

### Browser and version

Edge 131

### Describe the bug/issue

When I'm doing 40L sprint or Blitz, it tells me I'm having connection issues when I'm not, I can do QuickPlay or Tetra League just fine. 

### Expected behavior

I just did 40L sprint and it happened, went to Blitz to see if it had the same issues and it did. 

### Screenshots

![Screenshot 2024-11-26 162640](https://github.com/user-attachments/assets/bc427a2a-1c91-47f2-b794-5ac7918e227c)

### Additional context

I've tried refreshing the game, deleting the tab and creating a new one, yet the issue still persists.

**Comment by ZaptorZap** [comment]
Have you tried clearing your cookies/local storage? The server's most likely giving you a [403](https://en.wikipedia.org/wiki/HTTP_403) response, and this often fixes it for whatever reason.

**Comment by someonehere1234** [comment]
it worked thank you
