### ISSUE TITLE
切断したくなかったのに切断判定

### ISSUE THREAD

**Issue by NON-LETHAL777** [o5k/tetrio-issues#1431]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Google ChromeOS      130.0.6723.126（Official Build）

### Browser and version

Google chrome 130.0.6723.126（Official Build）

### Describe the bug/issue

重たくてテトラリーグ中にサーバーから切断されました。そして切断判定になりました。インターネット速度は非常に高速です。
具体的には、テトラリーグが始まって少しすると、固まって５分ほど待ったのですが一向に始まる様子がなくタブを閉じました。これはサーバーの不具合による問題だと思っています。

### Expected behavior

普通にテトラリーグを最後までやりたかったです。

### Screenshots

![Screenshot 2024-12-05 16 57 59](https://github.com/user-attachments/assets/4231f675-759f-4a5c-925c-fb3a786aff4d)

**Comment by ZaptorZap** [comment]
Our apologies, but this forum is not for generic connection issues. While it is true that the servers were experiencing a heightened load earlier, these issues, at least, pertaining to Tetra League, seem to have been corrected.

**Comment by NON-LETHAL777** [comment]
わかりました。返信ありがとうございました！

2024年12月5日(木) 21:46 Zaptor ***@***.***>:
