### ISSUE TITLE
Wider recognition of Quick Play mod combinations

### ISSUE THREAD

**Issue by 035966-L3** [o5k/tetrio-issues#1433]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this feature is not already requested.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am certain this is a **feature request**, not a bug.
- [X] I've **thought this feature through** properly.

### Is your feature request related to a problem? Please describe.

I used "Messy / Volitile / Holdless / Double Hole / Gravity" to play and reached Floor 3 but I just minted 5 achievements (the respective 5).

### Describe the solution you'd like

In my opinion mod combinations should be considered used not only in the cases where the player **exactly chose** the combination, but also in the cases where the combination became **a subset of** the player's choice. For example, the combinations "Deadlock" and "A Modern Classic" should be also considered used in the situation above.

### Describe alternatives you've considered

I suggest giving an update to former game records if this is taken.

**Comment by ZaptorZap** [comment]
I don't think this makes particular sense. You could just play Swamp Water Lite and immediately make every category obsolete as a casual player, to have an exaggerated stance. The point of these is that they are **curated challenges**. The moment you let people slap on any other mod they like it's no longer a fair playing ground in the respective leaderboards.

For example, you can already see All-Spin having a positive impact on most of Snowball Board's [world records](https://ch.tetr.io/achievements/54).
![image](https://github.com/user-attachments/assets/452a2d95-3c60-4170-a900-12f7c31a0dc1)
All-Spin would surely creep into nearly __every single category__ undaunted if it were to be valid, and that's just an experience some competitive players wouldn't be happy with.

In any case I've consulted the game designer over this and they are disinterested in implementing this request.
