### ISSUE TITLE
Email support

### ISSUE THREAD

**Issue by Mistera91** [o5k/tetrio-issues#1437]
Is email support really a thing ? I sent an email the 7th of December that didn’t get answered.
I also found these reddit threads : [thread 1](https://www.reddit.com/r/Tetris/comments/vxdo9h/tetrio_support_email/) and [thread 2](https://www.reddit.com/r/Tetris/comments/vi4hm7/tetrio_support_not_responding/), so it does look like it’s an old problem and that it affects multiple people.

**Comment by visiblyisabelle** [comment]
it's christmas, staff have lives outside of answering emails

please be patient
