### ISSUE TITLE
Room user action buttons exist after user leaves room

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#144]
### Description
There are room related user actions that can be done on users even when they aren't in the room. Once they enter and leave the room, you can click their name in chat to bring up the user profile. If you're a room owner, you will see that there are kick and ownership transferal related actions - even if the user isn't in the room anymore.

### Reproduction
1. Create a room
2. Let someone join and leave the room
3. Click the username that's left in chat

### Expected behavior
The buttons are either disabled or gone. Similar thing should happen when user leaves the room while you're looking at the profile.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/76575195-5caeb380-64b6-11ea-8fa3-b2a1f5a76a75.png)

**Comment by o5k** [comment]
The buttons don't work anymore, and this'd be kinda annoying to implement
