### ISSUE TITLE
Player can modify the starting bag of pieces when playing singleplayer rapidly, potentially giving them an advantage

### ISSUE THREAD

**Issue by canhill417** [o5k/tetrio-issues#148]
**Describe the bug/issue**
When you restart a game of singleplayer, the pieces in the bag automatically randomize. However, the player can see which pieces they will be given at the beginning of a round, and can randomize the bag randomly at a fast rate to manually randomize the bag until it is favorable to the player. This could be seen as an unfair advantage, as one could quickly randomize the bag until the pieces are favorable.  

**Reproducing**

1. Start a game of singleplayer (either 40-line or blitz)
2. During the countdown, press the restart button
3. The pieces in the preview will randomize every time the restart button is pushed.

**Your setup**
OS and version: Windows 10
Browser and version: Chrome 80

**Additional context**
N/A

**Comment by Wirtualnosc** [comment]
I'm pretty sure there's no advantage/disadvantage here to be looked at in first place, all it does is it makes life easier by just making the restart process faster if you actually get those - even if you decide to start the game, the player will find out what those pieces are anyway, and they might want to restart.

**Comment by o5k** [comment]
Only for the first bag though, one still won't know what order pieces 6 and 7 are until the game starts, and bag 2 (pieces 8~14) and bags onward are completely unknown.

How would you even propose fixing this?

**Comment by canhill417** [comment]
A. Makes All Clears and T-Spins easier to setup at the start of the game
B. Perhaps make the starting bag static until a game is actually played with them?

**Comment by Wirtualnosc** [comment]
And how would you determine when to scramble the bag again? As soon as game starts, a player can hit restart again. Even if you decide to not scramble by then, they can just quit and rejoin, or even refresh the page. If you look at tetris games, you can do a restart of next pieces anyway by quitting and starting another game. All this change does is make the restart waste a bit less time to a player.

Also personally, I think that forcing a bag upon players is a big no with some setups (there's already a github issue for disabling S and Z sequence at start and currently you don't have to worry about it too much by restarting the game).

**Comment by o5k** [comment]
> Perhaps make the starting bag static until a game is actually played with them?

sounds really frustrating

**Comment by canhill417** [comment]
Fair points are being made lmao. It would honestly really be a deterrent, but I would imagine that if one was gunning for a top score, it would be in their best interest to rapidly change the bag till it's in their favor. But my idea doesn't seem well recieved so it whatevs ¯\_(ツ)_/¯

**Comment by o5k** [comment]
i mean either people keep playing until they get a lucky bag and get a good score, or they keep playing good bags and get similar good scores

it's an advantage for everyone, and a feature added on purpose

removing it would only make it harder for people to get their full potential, and cause frustration along the way

thank you for reporting though!
