### ISSUE TITLE
Total wins, Consecutive wins, Matches played stats for multiplayer

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#15]
Perhaps? ![](https://cdn.discordapp.com/attachments/673305735811170305/675370362032357376/unknown.png)

**Comment by julf0** [comment]
Add some columns, like LPM/APM, LPS/PPS, Blocks placeds or something like that, would be good.

**Comment by mat1jaczyyy** [comment]
Lines sent for sure!

**Comment by o5k** [comment]
Added said record! Attacks sent/received will be added soon too.
