### ISSUE TITLE
Selected music stays the same after change between games

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#152]
### Describe the bug/issue
When a music theme is changed between games, it will switch its default selection to an old value when another game is finished.

### Reproducing
1. Select a music theme and finish a game of 40L
2. Now select a different music and finish another game of 40L
3. Look at currently selected music

### Expected behavior
A music from step 2. should be selected by default.

**Comment by o5k** [comment]
Fixed in next patch.
