### ISSUE TITLE
Config - Controls - second custom control

### ISSUE THREAD

**Issue by cbraukmann** [o5k/tetrio-issues#153]
### Describe the solution you'd like
I would like to have a second custom controls option.

I sometimes like to play with keyboard, but I also like to play with my switch controller. I need to change the controls everytime I switch between those.

### Describe alternatives you've considered
Maybe make the "guideline" and "wasd" controls adjustable like "custom" and add a reset button in the right top corner of "controls" - similiar to the reset button in the "handling" section.

**Comment by Wirtualnosc** [comment]
I'd imagine #146 addresses that, I guess the wording on that issue isn't too obvious

**Comment by o5k** [comment]
In a sense yes, youll be able to bind both keyboard and controller to a single input: ![](https://kagari.moe/:/2020-03-14_14-02-27.png)

**Comment by o5k** [comment]
Closing as duplicate of #146 - please reply if it is not.
