### ISSUE TITLE
The same key can be bound to every control

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#154]
### Describe the bug/issue
You can literally bind one key to _everything_. In solo games, that one key will act as hard drop, and if held, retry. In quick play/online games, it's completely and utterly broken. The key, for some reason, acts as if held down. It actively tries to forfeit the game and sends all the pieces to the right side (+softdrop). You constantly go out of focus due to chat being opened, targets are being chosen, and it's complete and utter hell.

### Reproducing
1. Go to config
2. Bind every control to one key
3. Join/start a game
4. ..._yikes_

### Screenshots
[Pic of settings](https://i.imgur.com/GtqtLyx.png)
[Absolute madness](https://i.imgur.com/zt6Tv27.mp4)
### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.66

### Additional context
None

**Comment by o5k** [comment]
Fixed in next patch.
