### ISSUE TITLE
Replay links can still be copied from expired replay files

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#158]
### Describe the bug/issue
Downloaded replays will retain the short ID used to generate links. This is fine until the replay gets removed on the server - afterwards, the link is invalid. However, the downloaded replay file will still retain that ID and will copy a replay link to clipboard when clicked.

### Reproducing
1. Pick your 10th recent game from tetra channel and download it (you can check at this stage that copied replay link works) - make sure the game isn't one of your PBs
2. Play another game of 40L/Blitz
3. Load the downloaded replay file
4. You can still see the replay ID and copy the link. Upon entering the link, the game will say that "no such game" exists.

### Expected behavior
Ideally, the replay ID should disappear from the result screen when it's outdated.

**Comment by o5k** [comment]
Fixed in next patch.
