### ISSUE TITLE
Leftmost playfields can't be clicked on in grid view

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#159]
### Describe the bug/issue
As a spectator, if I want to select leftmost playfields visible in a grid view, it's impossible due to the chat element covering those.

### Reproducing
Just spectate a game with more than 2 players. Try to click on leftmost playfield.

### Expected behavior
The leftmost playfield should be selectable.

**Comment by o5k** [comment]
Fixed in next patch.
