### ISSUE TITLE
Winner name not showing up after tab is unfocused in quick play/live game

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#160]
### Describe the bug/issue
Tested mainly in another tab, the end game animation (where the player's name and time survived fly in and the yellow circles play in the background) doesn't play after refocusing Tetr.io in the middle of the animation.

### Reproducing
1. Go to a live game (tested in quickplay)
2. After it's down to a few players, go ahead and switch to another tab.
3. Once the game over sound plays, switch back a few seconds later and see that the animation doesn't play.

### Expected behavior
The name and yellow circle animation should still appear.

### Screenshots/videos
[Here](https://i.imgur.com/tDzWq8M.mp4)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.66

**Comment by o5k** [comment]
This cannot be easily fixed because of how the animation is rendered (CSS animations), and above all, how browsers throttle webpages in the background to conserve processing power.
