### ISSUE TITLE
options to resize playing field/board

### ISSUE THREAD

**Issue by Chremster** [o5k/tetrio-issues#161]
coming from someone who also plays jstris, where the playing field is relatively smaller compared to tetr.io's, i dont feel comfortable when playing on a board thats so big. This is not a huge problem, as I can just resize my tab and everythings good, but i would feel way more immersed if i could play in fullscreen and have a small board at the same time. It would be great quality of life if you could add this in. 

Thank You!

**Comment by Raymonf** [comment]
It's actually too small for me :(

Please also consider the opposite way (zooming in) like Tetris Effect allows.

**Comment by o5k** [comment]
Added!
