### ISSUE TITLE
High garbage travel speed delay - attack sparks persist after game over

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#162]
### Describe the bug/issue
In a custom room with really high garbage delay, the attack sparks stick around after the game over animation plays.

### Reproducing
1. Go to a custom room and set the garbage travel speed to really high (the multiplier shown was just for a quick kill)
2. Send a bunch on lines; some to kill, and a few extras that won't reach the other player
3. When the animation plays, observe how the sparks continue to travel and persist after the game is done

### Expected behavior
The attack particles should dissipate once the game over animation is played.

### Screenshots/video
[Here](https://i.imgur.com/aXPFIqw.mp4)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.66

**Comment by o5k** [comment]
Fixed in next patch.
