### ISSUE TITLE
First game message about controls displays incorrectly when keys are unbound

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#163]
### Describe the bug/issue
When you get the welcome message showing you the controls, if you have unbound keys, then the message displays incorrectly. 

To me it appears that each element is a concatenated with `Array.join()`, but when certain elements are empty strings/whatever, the strange behavior occurs where unnecessary commas are inserted.

### Reproducing
1. Get a new account (if needed) and set controls to custom. Leave the 2 rightmost columns unbound.
       - Alternatively, you can set unbind the controls and trigger the event through whatever magic function.
2. Observe the error

### Expected behavior
Commas should only be inserted as necessary.

### Screenshots
[Here](https://i.imgur.com/FTVeviq.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.66

**Comment by o5k** [comment]
Fixed in next patch.
