### ISSUE TITLE
Use actual links for navigation

### ISSUE THREAD

**Issue by sirxemic** [o5k/tetrio-issues#166]
### Is your feature request related to a problem? Please describe.
Since Tetr.io is in the browser I often find myself wanting to use the browser's "navigate back" functionality, which currently does not work. I've also wanted to "middle-click" a few "pages" several times. Like open the "40 Lines" top 5 in separate tabs by middle-clicking.

### Describe the solution you'd like
I'd like to see almost all buttons that take the user to a different view to be links (actual `<a>`s - not `<div>`s or `<button>`s with extra functionality) to different pages. That way we can use browser navigation features (such as the back button and middle/command-click to open in a new tab) to navigate the menus. 

Of course clicking links shouldn't refresh the page, so the actual implementation would probably entail more than just using `<a>`s, and include capturing left-click events and using the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History_API).

I guess by implementing this you'd automatically fix #90.

**Comment by Jabster28** [comment]
Couldn't this also be achieved by just remapping the History API's back requests to the tetr.io back button that's in most of the menus?

**Comment by sirxemic** [comment]
@Jabster28 If I'm understanding what you're saying correctly... what you're suggesting there sounds like something that can only work *on top* of what I'm asking for. It does not work as an alternative.

**Comment by o5k** [comment]
Moving this off of the tracker - this is a game, not a website.

**Comment by sirxemic** [comment]
I completely understand that you're not gonna fix this since I can imagine implementing this requires a lot of work for only very little value gained. I respect your decision to move this off the tracker. But I just wanted to let you know I'm not treating the game as a website, but as a web game - that it's still a game in the browser, and this issue was about using things that the browser provides :)
