### ISSUE TITLE
Visible top row count can vary on strange effects

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#168]
### Describe the bug/issue
The amount of rows above playfield, where pieces can still be seen, vary depending on whether a piece was inserted by player (3) or not (2). In case a player inserts the piece, the following can refresh the view and remove the 3rd row for such piece:
- Getting attacked in multiplayer versus
- Resizing the window
- ??? (I'd imagine there are more situations that do this)

### Reproducing
1. Start a custom game
2. Build a tower on the side of the playfield, so that there's one block space left from the top of the playfield
3. Place an I piece vertically on that tower. Notice how all blocks for that piece are drawn
4. Resize the window. Now notice how the top block is cut off

### Expected behavior
I imagine the intended amount of rows that was supposed to be seen by a player was 2 in all cases - if so, then an I piece shouldn't draw the top block when placed on top of the playfield.

### Screenshots
Refer to the red arrow for the exact row I'm talking about
![image](https://user-images.githubusercontent.com/6901295/77021757-8f0d5480-697f-11ea-824e-0550e99374d0.png)

**Comment by o5k** [comment]
Fixed by Alpha.
