### ISSUE TITLE
Clearing multiple levels at once will increase level piece by piece

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#169]
### Description
When playing a custom game with very low level increment, a multi line clear that advances by more than one level will not advance as expected. It will only advance by one level and it will catch up level by level each time you place a piece.

### Reproducing
1. Create a game with static leveling and 1 line clear advancement for each level
2. Do some quads
3. You can notice that quads don't advance multiple levels at once. Instead, levels will advance one by one until the expected one is reached.

### Expected behavior
If a line clear is done which advances level by more than one, a correct level should be set immediately.

**Comment by o5k** [comment]
Fixed in next patch.
