### ISSUE TITLE
Custom Block skin

### ISSUE THREAD

**Issue by PatanYT** [o5k/tetrio-issues#170]
### Is your feature request related to a problem? Please describe.
I would really like to change my block skin but at the moment I don't see a solution to do so.

### Describe the solution you'd like
Maybe add a scroll down bar to choose some predetermined block skins.

### Describe alternatives you've considered
Or you could add an input bar, where we can enter a URL for a custom block skin. Kind of like how you did with the background.

**Comment by Wirtualnosc** [comment]
Already suggested, see #84
