### ISSUE TITLE
Undefined Blitz scores in Tetra News

### ISSUE THREAD

**Issue by Lekrkoekj** [o5k/tetrio-issues#171]
### Describe the bug/issue
All Blitz scores in the Tetra News list are listed as undefined. If you click on these scores it will show the correct score.

### Reproducing
1. Go to the Tetra Channel

### Expected behavior
It should show the right scores instead of undefined.

### Screenshots
https://i.imgur.com/sYBOj5U.png

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Microsoft Edge Chromium 82

### Additional context
-

**Comment by o5k** [comment]
Hotfixed - reload and this will be patched.
