### ISSUE TITLE
Save MP Room settings to a file, similar to Solo game settings

### ISSUE THREAD

**Issue by GlitchyPSIX** [o5k/tetrio-issues#173]
In addition to storing them, also load them for quick "own preset" loading

Useful for quick storing of settings for "canon rulesets" for other places, such as online tournaments.

(Additionally, "Importing" for Solo game settings)

**Comment by Wirtualnosc** [comment]
Already suggested; see #157
You can already import solo game settings (it would be pretty useless if you only could export...), drag the file into game window. A more obvious way would be useful, though...
