### ISSUE TITLE
Flopside boards overlap with NEXT pieces

### ISSUE THREAD

**Issue by o5k** [o5k/tetrio-issues#176]
When in 30+ rooms, boards on the right are too far on the left, need to rightalign these boards

**Comment by eight04** [comment]
![image](https://user-images.githubusercontent.com/1324510/77253147-7fe61980-6c93-11ea-9bca-642aede90e9c.png)
Like this?

**Comment by Wirtualnosc** [comment]
yes

**Comment by eight04** [comment]
![image](https://user-images.githubusercontent.com/1324510/77253177-a73ce680-6c93-11ea-9af4-19b1846a0e5c.png)

**Comment by o5k** [comment]
Fixed in next patch.
