### ISSUE TITLE
Aliasing lines after board rotation (high bounciness) 

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#178]
### Describe the bug/issue
It's another issue with spinning pieces- or rather, all of them. As the board shifts into place after being spun in the same way as #177, if you squint you can see lines traveling down between each square as it rotates. It might not be possible due to how diagonals work.

### Reproducing
1. Set to high bounciness
2. Make a T-spin setup and rotate the T in there a few times
3. As the board rotates back, look at the placed pieces and watch the "lines" being rendered

### Expected behavior
I'm not sure- the "lines" shouldn't be there. This might not be possible to solve.

### Videos
[Here](https://youtu.be/6fYCrfD_w6A)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.69

**Comment by szymonszl** [comment]
These appear to be simple [aliasing](https://en.wikipedia.org/wiki/Spatial_anti-aliasing) artifacts. While an anti-aliasing filter should be enough to solve it, they are usually quite computationally intensive, and quite a lot of people have enough problem getting tetrio to run smoothly as is. Still, if pixi.js has some kind of antialiasing filter included, that might be quite easy to fix, as long as the option is hidden behind a checkbox or only on higher graphic levels.

**Comment by o5k** [comment]
yep, that's aliasing

I'll look into seeing if I can get an AA filter on, but not sure

**Comment by o5k** [comment]
This is now better since Pixi v5 - unless LOW graphics is chosen.

**Comment by LayneTheEpic** [comment]
Alright, nice
