### ISSUE TITLE
Soft drop is slower in multiplayer?

### ISSUE THREAD

**Issue by eight04** [o5k/tetrio-issues#182]
### Describe the bug/issue

Soft drop is slower in multiplayer.

### Reproducing

1. Set SDF to 20 in the config.
2. Play 40 lines and press down.
3. Play multiplayer and press down.

### Expected behavior

The speed should remain the same.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Firefox Developer Edition 75.0b6 (64-bit)
 
I can also repro the problem in Chrome and Chromium Edge.

### Additional context

I feel like the speed changes according to FPS. I do observe serious FPS drop when clearing lines. Is it possible to display FPS on screen?

Another problem happening randomly that can be related: sometimes the mino teleports to the edge with a single keypress.

**Comment by o5k** [comment]
SDF is a factor of the current gravity. Different games have different gravity, so any SDF other than MAX will feel different depending on the current gravity.

**Comment by eight04** [comment]
Does it mean that gravity is higher in 40 lines?

**Comment by o5k** [comment]
IIRC multiplayer starts slower, but after a little bit, multiplayer is a lot faster.
