### ISSUE TITLE
You can highlight users and roles from QP to Discord

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#183]
Using <@id>, <@!id> and <@&id> will highlight users and roles on discord (while obviously continuing to look the same way it was typed in QP).

![image](https://user-images.githubusercontent.com/6901295/77253419-f95d1800-6c51-11ea-8db3-f9e123b94506.png)

**Comment by andrew12** [comment]
you can do channels too with <#id>

**Comment by Wirtualnosc** [comment]
so you can do emojis I'd say? full list of those id stuffs is here if interested https://discordapp.com/developers/docs/reference#message-formatting

**Comment by o5k** [comment]
it actually doesnt: [](https://kagari.moe/:/2020-03-22_16-37-19.png)

it shows as if it's highlighting, but the recipient never gets pinged... I use a field in the webhooks called `allowed_mentions` to do this.
