### ISSUE TITLE
Garbage visual effects in wrong location

### ISSUE THREAD

**Issue by UniQMG522** [o5k/tetrio-issues#185]
### Describe the bug/issue
Garbage visual effects in wrong location. Self-to-others garbage going towards left side of screen, other-to-others garbage spawning and disappearing on left side.

### Reproducing
1. Start quick play

### Expected behavior
Garbage visual effects go to intended boards

### Screenshots
Firefox:
![firefox_bYnlFgNKkY](https://user-images.githubusercontent.com/48872143/77261577-9e74f200-6c4c-11ea-92ba-03f23ac8dab6.png)

Chrome:
![chrome_awpB7PehML](https://user-images.githubusercontent.com/48872143/77261636-1cd19400-6c4d-11ea-80c7-e7d5ec69ad58.png)

### Your setup
 - **OS and version**: Windows 10 (v1809)
 - **Browser and version**: Firefox 74, Chrome 80

**Comment by o5k** [comment]
Looking into this, I think I fixed it but still testing

**Comment by o5k** [comment]
Hotfixed - reload to receive the fix.
