### ISSUE TITLE
Custom BGM support

### ISSUE THREAD

**Issue by ooa113y** [o5k/tetrio-issues#187]
Just like the custom background support that's already been implemented, allow for custom BGM via link to a supported file format (.ogg should work in any sane browser).

**Comment by LayneTheEpic** [comment]
Honestly, just mute the background music and play Spotify over it lol

I don't get why people are so obsessed over this

**Comment by LayneTheEpic** [comment]
I mean you don't have to close the issue, people are going to keep asking so it'll eventually get implemented regardless

**Comment by o5k** [comment]
This is not planned for now, because as LayneTheEpic says, it's _easier_ to just put on smth else in the background.
