### ISSUE TITLE
Game not properly understanding shift combo inputs

### ISSUE THREAD

**Issue by csq-curiosity** [o5k/tetrio-issues#188]
### Preliminary Note
This thread will describe the control scheme as two parts: movement and rotation. (Each does not necessarily describe the control scheme properly, but it shouldn't be too much of a problem to understand.) Movement refers to the "move left", "move right", "soft drop" and "hard drop". Rotation refers to the "rotate cw", "rotate ccw", "rotate 180" and "hold".

### Describe the bug/issue
- If one of the movement control settings is set to SHIFT, then all other movement inputs will be dropped if and as long as the shift input is sent.
- If one of the rotation control settings is set to SHIFT, then all other rotation inputs will be dropped if and as long as the shift input is sent.

### Example
- (Rotation) Assume the controls are set as COMMA(,), DOT(.), SLASH(/) and RSHIFT. If RSHIFT is pressed and held, all inputs from COMMA, DOT and SLASH will be dropped as long as RSHIFT is held.

### Expected behavior
It is expected that the game handles the input combinations that involve SHIFT correctly and do not cause input conflicts.

### Your setup
 - Windows 10
 - Chrome 80

### Additional context
- The game does not differentiate shift inputs; i.e. LSHIFT and RSHIFT is the same input as far as the game's concerned. Hence, this glitch should be replicated regardless of LSHIFT and RSHIFT.

**Comment by o5k** [comment]
Fixed in next patch.
