### ISSUE TITLE
T-Spin message shows up in wrong color

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#191]
reproduce by:
- start custom game with stupid spins
- make a spin of your desired color
- quit that game and start any game with t-spins only
- enjoy your custom t-spin message color
![image](https://user-images.githubusercontent.com/6901295/77494199-08ec8480-6e3d-11ea-9953-0a43c660d774.png)

**Comment by o5k** [comment]
Fixed in next patch.
