### ISSUE TITLE
Game Hangs when set 22+ lines on 22+ garbage cap lobby

### ISSUE THREAD

**Issue by NikoAndTails** [o5k/tetrio-issues#193]
### Describe the bug/issue
When a player is attacked in a 22+ damage attack, and the garbage cap is 22 or higher, the game will stop responding (but chat still works)

### Reproducing
1. Make private/public lobby
2. Set garbage multi to 100x (anything that deals 22+ damage in one hit)
3. Set Garbage Cap and Garbage Cap Max to 22 or higher.
4. Have one player send another player an attack that deals 22+ damage.
5. On receiving the attack, the player that got hit will immediately have their game hang.

### Expected behavior
... not freezing when that happens

### Screenshots
sorry I got off my PC and can’t grab a screenshot

### Your setup
 **Windows 10**
 **Chrome Latest Version**

### Additional context
I found this bug when making an OHKO lobby and people kept crashing whenever they got hit

**Comment by o5k** [comment]
Fixed in next patch.
