### ISSUE TITLE
Background images only work periodically

### ISSUE THREAD

**Issue by Solivisor** [o5k/tetrio-issues#194]
After playing for a little while, I noticed you could add a custom background image.
I added 2 and decided to leave it there for now, but just recently I added a total of 5, and none of them were loading/working. 
Now this had already been happening a little bit but only once did the background not load and i wasn't too picky about it. 
After 5 games one of the backgrounds work.
7 games after and the same background works.
But I'm wondering why the other ones aren't.

Now I don't know exactly what else to say because I'm not sure what information is useful and I'm not the smartest -w-

feel free to DM me or something if you have questions about this situation or need more information

Solivisor#6228

**Comment by o5k** [comment]
In the last update, the way backgrounds load has changed. Some hosts no longer work due to this.

Reupload your background to imagehosts like imgur or safe.fiery.me to fix.
