### ISSUE TITLE
Top out warning's next piece shows up even with next pieces disabled

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#196]
> [19:41] gizmo4487: When 0 next pieces are set, the top-out warning still displays the next piece
> [19:43] Tanarus: When the 'next' preview is turned off, you still get the red X's showing your next piece at the top of your field when it gets high.

![image](https://user-images.githubusercontent.com/6901295/77583345-d5f7ce80-6ed8-11ea-865f-5aaa8585595c.png)

**Comment by o5k** [comment]
FIxed in next patch.
