### ISSUE TITLE
You can top out several times during one stock use

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#197]
### Describe the bug/issue
You can top out several times during one stock use. With each top out, you will use more stocks (unless you have none, then it won't use any and you won't lose - but effects will still apply). The board will restart as many times as you have topped out, as well.

### Reproducing
1. Start a game with stocks
2. Create a tower on the board side
3. Top out repeatedly by DASing into it

### Expected behavior
You should be able to top out only once - perhaps by freezing player pieces while the stock animation plays.

**Comment by o5k** [comment]
Hotfixed.
