### ISSUE TITLE
DAS optimization techniques not achievable

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#2]
DAS seems to be entirely cancelled when a second movement key is pressed, which removes the ability to do many DAS optimization techniques.

Easy repro: DAS to right wall, don't release right. Move (tap) one tile left, then release left. The DAS from the still held right input should still be active and start moving based on ARR back to the right side. Currently, no movement happens afterwards and the piece is left 1 tile away from the wall, even though the movement key is still being held.

For other examples which aren't doable in tetr.io, see this [Hard Drop Wiki page on DAS optimization](https://harddrop.com/wiki/DAS_Optimization)

**Comment by o5k** [comment]
Fixed! This change will go in effect next server update.
