### ISSUE TITLE
Fin TSD - T piece SRS kick inconsistency

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#20]
When kicking a Fin TSD, issues can arise and make fins near impossible in multiplayer due to higher gravity.

https://youtu.be/k_mWecOp9bI

As seen in this video, when rotating the piece counter-clockwise (to kick it upwards), it can sometimes automatically drop down to the lower tile without ever being positioned at the upper tile (see 41.000 IGT in the video). This seems to be tied to the gravity, making this kick much harder to do in multiplayer than it should be.

What's expected to happen is something a lot more like this:

https://youtu.be/SOI2xeXsc_k

In PPT, the piece will always kick to the upper tile and the sub-pixel Y value (or gravity timer, depending on the implementation method) will reset, allowing the piece to hover as if it was just dropped into this position.

To mitigate stalling forever, the game employs a check which checks if 15 rotation or movement inputs have been done since the last time the piece reached a new minimum Y tile value. If it exceeds 15, and the piece is currently standing on the ground, it will automatically lock.

**Comment by o5k** [comment]
ok, either I fixed this or I broke half of the kicks system, let's find out in the next patch ^^;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by mat1jaczyyy** [comment]
Seems fine to me! 👍
