### ISSUE TITLE
40L: Display the number on the game board itself

### ISSUE THREAD

**Issue by Cublex** [o5k/tetrio-issues#200]
### Is your feature request related to a problem? Please describe.
I'm used to The Important Number (example: combo counter) being on the playfield or incredibly easy to see, and _small number on side_ isn't that easy.

### Describe the solution you'd like
Take the lines you have left to clear, and put it on top of the board. Should probably make it either translucent or behind the pieces, but still visible. Also, make it togglable, because I can see this being unpopular.

### Describe alternatives you've considered
The bar on the right does do the trick, but it's easily unnoticable.

### Additional context
woo issue 200!

**Comment by o5k** [comment]
Added!
