### ISSUE TITLE
Some punctuation in usernames gives an "invalid authorization token" message or other errors

### ISSUE THREAD

**Issue by Volleo6144** [o5k/tetrio-issues#206]
### Describe the bug/issue
Putting certain usernames into the username field (before the "anonymous or register?" popup) can cause an "invalid authorization token" message, which is kind of worrying (I hope there isn't some sort of XSS here).

### Reproducing
1. Type in some usernames (`volleo6144?` and `exists/exists` both lead to unexpected behavior)
2. Click "Join"
3. n/a

### Expected behavior
The standard "username may only contain letters and numbers" message pops up.

### Actual behavior
Varies. In `volleo6144?`'s case, a separate message saying "invalid authorization token" appears; in `exists/exists`'s case, the loading screen persists indefinitely.

### Screenshots
<img width="1792" alt="see bottom right" title="see bottom right" src="https://user-images.githubusercontent.com/38385509/78052528-e24eb200-7344-11ea-974f-b17bca29f9a0.png">
<img width="1792" alt="the loading screen persists indefinitely" title="infinite loading" src="https://user-images.githubusercontent.com/38385509/78052588-f397be80-7344-11ea-860e-f540b367ca15.png">

### Your setup
 - **OS and version**: macOS 10.15
 - **Browser and version**: Firefox Developer Edition¹ 75.0b11 (64-bit)

### Additional context
After digging in the developer tools a little, I noticed that this happens because the username is sent to the server in a URI with too little escaping (spaces will become `%20`, but most punctuation won't be escaped). `volleo6144?` returns a 401 with a valid JSON response, but `exists/exists` returns a 404 with some HTML instead, which causes the loading screen to persist indefinitely upon attempting to parse it as JSON. I imagine there are other things you can cause too.

¹: this just means that devtools are more extensive than normal Firefox as far as I can tell

**Comment by o5k** [comment]
Fixed in next patch.
