### ISSUE TITLE
Unsaved Rules Appear Over Other Custom Room Rules

### ISSUE THREAD

**Issue by Xelitik** [o5k/tetrio-issues#207]
When rules aren't saved in your custom room, they appear over the rules of another custom room. Minor visual bug.

1. Create a custom room and modify rules
2. Leave your room WITHOUT saving the changed rules
3. Enter another person's room
Video reproducing the bug: https://youtu.be/NCFS5OKepD0

Custom rules of the room should be displayed / Unsaved rules should be discarded once leaving your room.

Windows 10 on Firefox Broswer

**Comment by o5k** [comment]
FIxed in next version.
