### ISSUE TITLE
Attack miscalculation?

### ISSUE THREAD

**Issue by Rizky92** [o5k/tetrio-issues#209]
### Describe the bug/issue
I discovered overloaded values of attack. Either receive or send. It happened today during quick play session. Probably some miscalculation? It also causes my browser to go heavily lagged.

### Reproducing
1. Go to 'Multiplayer'
2. Click on 'Quick play'
3. Start a session
4. Wait for the attack, or send.

### Expected behavior
The attack should be calculated correctly

### Your setup
 - Windows 10
 - Chrome 80.0.3987.149

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by ArztVielfrass** [comment]
I think this was because of April Fools, I mean stupid spins are on by default and damage is amped by 100x. This will probably end after a few days(I hope)

**Comment by o5k** [comment]
![](https://kagari.moe/:/evil.png)
