### ISSUE TITLE
Display FPS setting

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#21]
A nice diagnostic to have in general. Might help with identifying #19

**Comment by o5k** [comment]
There actually is one, but it's only on development builds. You can, however, enable Chrome's native FPS meter under Developer tools -> More tools -> Rendering -> FPS meter. (The development build one is a worse metric)

![Image](https://kagari.moe/:/2020-02-09_14-32-00.png)

**Comment by mat1jaczyyy** [comment]
Not a nice solution because the console has to be constantly open... it's better if detached, but still a bit messy. Probably the best though

**Comment by o5k** [comment]
I'll add the FPS meter from development builds into production too, then. It can be toggled with F8.
