### ISSUE TITLE
Fix NRS Left Bias

### ISSUE THREAD

**Issue by Xelitik** [o5k/tetrio-issues#211]
NRS is based off the NES game if im not mistaken. In games using Nintendo rules, pieces three blocks wide would spawn in the middle biased towards the right instead of the left as in guideline.

Issue: NRS has blocks spawn towards the left despite them spawning towards the right on the NES.

Expected Behavior: Pieces should spawn biased towards the right.

(Not sure where this should go so i put it into bugs)

**Comment by Volleo6144** [comment]
isn't it the opposite on GB tetris though?

**Comment by o5k** [comment]
Fixed in next patch.
