### ISSUE TITLE
Adapt to portrait aspect ratios

### ISSUE THREAD

**Issue by 22darwin** [o5k/tetrio-issues#213]
I'd like to inform you about how the game minimizes when you start playing the game using only half the screen (and other fractions). I sometimes just play sprint and blitz while watching a video and I have to either change the settings (which is not quickly accessible) or just making the video relatively small on the screen.

I understand that this a minor request and may be addressed last but I hope you do address this eventually. 

few solutions I'd suggest are:
1. Don't resize the page when I resize the window, this is how jstris does it. I don't need to see the whole page if I'm really binge watching something else on screen
2. Have the settings easily accessible without exiting, (although I can't imagine the ui)
3. Have it adjust just to the height, you wouldn't really expect anyone to play with a minimized

Also I'd like to say I can just zoom in like on normal windows (two finger stuff on laptop, etc.).

**Comment by o5k** [comment]
Closing as this would be addressed when a mobile mode would be created.
