### ISSUE TITLE
Better Music Adjust UI

### ISSUE THREAD

**Issue by Xelitik** [o5k/tetrio-issues#215]
Using Mouse Scrolling feels awkward when trying to change only one of the volumes. There is also an extra "bar" of volume on that is not visible and looks like it's silent when it is really on the lowest setting. It's also pretty common to accidentally scroll the wheel and mess up your volume settings.

What I suggest is a music adjust button that you hold down to bring up the music UI with 3 options: Music, SFX, and Master volume. It would also be nice to have a mute button for each of the three options In order to keep your settings if you want to temporarily disable in-game music.

At the very least, please make the music only modifiable when holding down a music adjust button.

**Comment by o5k** [comment]
Closing as you remade it in #216. Next time, please use the edit feature.
