### ISSUE TITLE
Non-monospace for some UI elements (kerning)

### ISSUE THREAD

**Issue by Tenchi2xh** [o5k/tetrio-issues#217]
### Is your feature request related to a problem? Please describe.

The main font used for the UI is monospace, however that doesn't always work out; the monospace kerning on the I's and Y's especially can visually hurt the design, and look quite janky

### Describe the solution you'd like

An alternative font that looks the same but has proportional kerning instead of monospace. Some of the narrow versions currently used is fine though, thanks to the spacing being present around all letters.

### Mockup example 1

Current font:
![image](https://user-images.githubusercontent.com/4116708/78373443-e3911080-75ca-11ea-977c-b2489d857b6b.png)

Kerning manually fixed (notice the LIVE looks much better, and the username):

![image](https://user-images.githubusercontent.com/4116708/78373327-c2302480-75ca-11ea-8750-db56fc0ad299.png)

### Mockup example 2

Current font:

![image](https://user-images.githubusercontent.com/4116708/78373675-336fd780-75cb-11ea-8d51-85f6b75a9e99.png)

Kerning maually fixed (compare "multiplayer", "quick", "listing", "pick"):

![image](https://user-images.githubusercontent.com/4116708/78374415-1be51e80-75cc-11ea-8455-e85b11315c78.png)

I would argue that this second screenshot looks more professional. More screens display a similar jankiness but they are harder to quickly mock up in photoshop

(for an easier 'before' and 'after' you can open the images in tabs and quickly switch tabs to see the differeces)

**Comment by o5k** [comment]
The kerning on the uppercase I has already been fixed in the next patch, which isn't out yet but will be soon:
![](https://kagari.moe/:/2020-04-03_17-56-58.png)

Any other characters you think should be rekerned?

**Comment by Tenchi2xh** [comment]
Oh brilliant! Usually the other guilty letter for monospace is Y since it has a lot of empty space on both sides.

Maybe also L when combined with T: LT
