### ISSUE TITLE
Invisible Blocks

### ISSUE THREAD

**Issue by AbsurdPotato1** [o5k/tetrio-issues#219]
I went into a custom game with default setting and the blocks on the play screen, hold, and next were all invisible. When I hard drop, The outline of the block flashes for a second or so. After going into the next game, it was back to normal.

### Reproducing
1. Fullscreen
2. Go to a multiplayer game in room listing (not sure if this is necessary, it's just what i did).
3. "Ctrl + w" to close the tab  (also not sure if necessary).
4. Reopen tetr.io
5. Go into a custom game with default settings and the bug should be there (didn't always happen, just that one time).

I expected to see blocks that were visible.

![Screenshot (254)](https://user-images.githubusercontent.com/63165559/78458990-a2e8d400-766a-11ea-9195-1280fb0329a6.png) (flashing blocks are there due to hard dropping quickly)
![Screenshot (251)](https://user-images.githubusercontent.com/63165559/78458996-b09e5980-766a-11ea-9a55-1ffd75fcb448.png) (at the beginning of the game).

### Your setup
 - Windows 10
 - Version 80.0.3987.163 (Official Build) (64-bit)

### Additional context
I had been playing for a bit (I have no console logs).

**Comment by o5k** [comment]
I've seen multiple people have this issue, but I can't seem to reproduce it myself. If anyone has console logs (or better yet, a way to reliably reproduce on my machine), please let me know

**Comment by AbsurdPotato1** [comment]
I'm not 100% I did this, cause I don't remember if this is right, so don't take my word for it, but I might have just turned on pro mode and alert on fitness fault in 40 lines, finished the 40 lines games, went into battle mode, and went to custom. Not sure if this is related, and again, not sure if this is the time when I did this.

**Comment by o5k** [comment]
Can't reproduce at all :/

**Comment by AbsurdPotato1** [comment]
hi
