### ISSUE TITLE
Tetra League start battle animation could be more fluid

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#225]
### Is your feature request related to a problem? Please describe.
I know its a small thing to gripe about, but everything just feels so cool and epic and then the two backgrounds just kinda... bump into eachother - then slide away, really obliterating the mood.

### Describe the solution you'd like
make that feel as cool as the music playing, really nail that im either gonna beat the shit out of my opponent, or they're gonna beat the shit out of me

nah but for real, instead of have the backgrounds fly into eachother at what seems like a set speed, maybe make it exponential?
or maybe more screenshake during their collision.

also when the backgrounds exit i think they should slide off into their respective sides off of eachother.

### Describe alternatives you've considered
i can't change animations myself sorry

### Additional context
The backgrounds look kind of out of place being entirely a solid color and not a gradient to black like how a lot of the game is..

**Comment by o5k** [comment]
not entirely sure what to do about this lol, let me know if you come up w/ smth
