### ISSUE TITLE
visualize rotation points

### ISSUE THREAD

**Issue by LastExceed** [o5k/tetrio-issues#226]
This would be particularly helpful for beginners, but even as an intermediate player (sub 1min 40L) i still sometimes have problems understanding why rotations (especially I/S/Z spins) do or do not work

The idea is to add a visual reference to the current piece (and its shadow) like this:

![asd](https://vignette.wikia.nocookie.net/tetrisconcept/images/3/3d/SRS-pieces.png/revision/latest?cb=20060626173148)

Make it a user option since pro players probably dont need/want this

**Comment by o5k** [comment]
Not planned due to how the engine works, making this spaghetti to implement.

**Comment by KonSola5** [comment]
Is the spaghetti-coding still an issue for implementing this?
It's been over 3 years, so things might have improved over the time.
