### ISSUE TITLE
Music select menu stays when getting matched

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#231]
1. Enter matchmaking
2. Before you get matched, open a selection menu that offers music (works with both "About" jukebox thing, as well as 40L/Custom music selection. I'm not sure about other menus similar to those, but I'd imagine it's the same)
3. Wait until you get matched
4. ???
5. The menu stays open until you finally decide on an option to pick
I'm pretty sure it should close as soon as you get matched

**Comment by o5k** [comment]
Fixed in next patch.
