### ISSUE TITLE
Profile card looks weird when beeing a supporter

### ISSUE THREAD

**Issue by Founntain** [o5k/tetrio-issues#232]
### Describe the bug/issue
Already posted it on Discord, but also wanted to create a GitHub Issue for that.

When beeing a supporter and you have not League matches played the profile card looks really weird, it fixes itself if you played one match.

### Reproducing
1. Open a Profile that has league matches played
2. Delete the tetra league matches played div
3. See error

### Expected behavior
See Screenshots

### Screenshots
![](https://x.founntain.de/kWLiKfDa.png)

**Comment by o5k** [comment]
Fixed in next patch.
