### ISSUE TITLE
See XP Bar on the top right next to the level

### ISSUE THREAD

**Issue by Founntain** [o5k/tetrio-issues#233]
The idea to show the current XP in the top right? Maybe next to the level badge, oder below as a small bar (3 or 5 pixel) Something simple, if it shouldn't take much space. Cause I really don't like to hover over the Badge to see my progress so far. Its something small, but would be a neat small addition

**Comment by Wirtualnosc** [comment]
I've heard that some people also requested seeing exact XP amount - it's currently only possible through Tetra Channel.

**Comment by Founntain** [comment]
> I've heard that some people also requested seeing exact XP amount - it's currently only possible through Tetra Channel.

Where do I find it in the Tetra channel? You mean the leaderboards? Not really helpful because I need to be in the top 100. And I don't want to know the total amount. I want to see how much I need to lvl up. A bar is fine. Just to tell me it really fast. Without hovering over it.

**Comment by Wirtualnosc** [comment]
It does say the total amount, but it's true you need to be in top 100 of players with most XP, hence why I've added that comment - even keeping amount as a tooltip when you hover over the bar would be fine.

**Comment by o5k** [comment]
There is no space in the ingame UI for this. Expect this for the seperate Tetra Channel website, instead.
