### ISSUE TITLE
Starting a Tetra League match while in 40L will show "FINISHED" when either side wins

### ISSUE THREAD

**Issue by GlitchyPSIX** [o5k/tetrio-issues#234]
Upon winning or losing a game in Tetra League, the "FINISHED" dialog from 40L will show up if before getting matched with somebody you were playing 40L.

To reproduce, start a 40L game while waiting for matchmaking, then lose or win a ranked game after being matched.

**Comment by o5k** [comment]
Huh, which one? I can't seem to reproduce this

**Comment by GlitchyPSIX** [comment]
My mistake, I had overlooked something.
