### ISSUE TITLE
Allow scrolling down more than 100 in leaderboards

### ISSUE THREAD

**Issue by trudnorx** [o5k/tetrio-issues#237]
Could also add options like find player name, page numbers, show only friends, etc.
Ideally leaderboards should be limitless and include an infinite amount of players I think.

**Comment by o5k** [comment]
League leaderboards have been bumped to 999 in next patch. Extended leaderboards would be shown on a planned standalone site.

**Comment by trudnorx** [comment]
I'd rather have it on the game, I think the design is pretty neat and a paging function would be nice in there.

**Comment by trudnorx** [comment]
Looks like Tetra League leader board now shows more than 100 but other leaderboards like XP, Blitz, etc. still don't, it'd be nice to have all of them bumped to 999.

**Comment by o5k** [comment]
Closing as this is on the track for Tetra Channel site.
