### ISSUE TITLE
Tetra League points should depend on how many matches you win/lose

### ISSUE THREAD

**Issue by trudnorx** [o5k/tetrio-issues#239]
Like if you win by 7-0, you should get more points than if by 7-1

**Comment by o5k** [comment]
This would make tiebreakers really anticlimactic

**Comment by Tenchi2xh** [comment]
Indeed, imagine having the battle of your life, going all the way to 6-6, super tense, boom Tetris for Jeff, you win !

You get +4 TR

**Comment by trudnorx** [comment]
Well, several other games incorporate this feature and nobody complained. Personally I think it'd be more fun.

**Comment by LayneTheEpic** [comment]
Maybe instead of with winning, we do something similar with losing (if not already). If you lose 2-3 you obviously performed decently, so you should only lose, say, ~50 TR compared to a few hundred.

**Comment by trudnorx** [comment]
Establishing a different principle for winning and losing would go against the principles of Elo/Glicko system and introduce inaccuracies.

**Comment by o5k** [comment]
Yeah, desyncing won and lost TR would throw the Glicko system out of whack. It's meant for zero-sum games after all.
