### ISSUE TITLE
Profile ranking can differ from leaderboard ranking

### ISSUE THREAD

**Issue by lifeofchrome** [o5k/tetrio-issues#247]
### Describe the bug/issue
When players have the same or similar TR ratings in Tetra League, each of their profiles can show the same ranking. This can also happen on the versus screen when a match starts.

### Reproducing
Easiest way to reproduce this:
1. Find a TR tie in the Tetra League ranking leaderboard
2. Click on each player's profile
3. Each of their rankings in the Tetra League section are the same

### Expected behavior
The rankings should be the same as in the Tetra Channel leaderboard

### Screenshots
![image](https://user-images.githubusercontent.com/8226943/78861048-6c5be200-79f9-11ea-81a7-d6c72f8340a4.png)
![image](https://user-images.githubusercontent.com/8226943/78861062-77af0d80-79f9-11ea-93e0-12edb27681e0.png)
![image](https://user-images.githubusercontent.com/8226943/78861078-81d10c00-79f9-11ea-8b48-b683416a90e4.png)
![image](https://media.discordapp.net/attachments/673305614318960671/697665522267062352/j9Mo2fAt.png)

### Your setup
Chrome OS 81.0.4044.72

### Additional context
I initially reported the bug here: https://canary.discordapp.com/channels/673303546107658242/673305614318960671/696909986550382632
Garbo posted a screenshot showing an example of the bug here (also in the screenshots section): https://canary.discordapp.com/channels/673303546107658242/673305614318960671/697665524280197141

**Comment by o5k** [comment]
Fixed in next patch.

**Comment by lifeofchrome** [comment]
There still seems to be an issue:
![image](https://user-images.githubusercontent.com/8226943/78934671-f2673f80-7a70-11ea-9564-9c1a00057f9f.png)
![image](https://user-images.githubusercontent.com/8226943/78934692-fbf0a780-7a70-11ea-8e4c-84b08c4390c9.png)
