### ISSUE TITLE
Option to auto-unfocus chat after sending message during game

### ISSUE THREAD

**Issue by Tenchi2xh** [o5k/tetrio-issues#248]
### Is your feature request related to a problem? Please describe.

During a game, I like to start by saying "glhf" or sometimes do a quick comment between matches (in league). To do so, I press my key bind to open chat (enter), type my message, press enter to send, but then I quickly have to reach for the mouse to click outside of the chat to re-focus the game before it starts.

### Describe the solution you'd like

An option to automatically unfocus the chat after sending a message during a game.

**Comment by Tenchi2xh** [comment]
I had an inkling something was wrong because when I send a message, the chat UI kind of blinks, so I changed my key binding for "Open Chat" to something else, and now the chat automatically unfocuses when sending a message

So the real issue is: when the key binding for "Open Chat" is bound to the Enter key, the chat closes and re-opens instantly

**Comment by o5k** [comment]
Fixed in next patch.
