### ISSUE TITLE
Resizing window after forfeiting game causes previous board state to reappear

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#25]
Repro:
1. Start a 40Line game
2. Exit via ESC, wait for board shrinking animation to complete
3. Resize window, easiest done by maximizing

Result:
![image](https://user-images.githubusercontent.com/13300194/74102313-c39d1d80-4b42-11ea-9b77-31f335df9ff9.png)

Windows 10, Chrome 80

**Comment by o5k** [comment]
Fixed in next patch.
