### ISSUE TITLE
Handling RD according to win/loss streaks

### ISSUE THREAD

**Issue by trudnorx** [o5k/tetrio-issues#250]
https://tetris.wiki/Tetr.io says:
"RD decreases every time the player plays a Tetra League game, and slowly increases over time."

Assuming this is a complete and accurate description, I think there's a better way to go about things. The problem with the current system is after playing a lot you get "frozen" and the system doesn't react well to skill changes.

It would be better to use a system similar to StarCraft II: if you win or lose more than 1 games in a row, your RD increases since you're performing better/worse than expected (50/50). The longer your streak is, the more your RD increases. The more you return to a normal lack of streaks, the more your RD decreases.

**Comment by Tenchi2xh** [comment]
The RD stuff is all precisely calculated and follows this paper:

![image](https://user-images.githubusercontent.com/4116708/78969295-e0d07700-7b06-11ea-84b3-75f2912990c3.png)

(http://www.glicko.net/glicko/glicko2.pdf)

It's already famous as a rating algorithm (like in chess) for being more reactive to skill than ELO, the classical system typically used

I don't think it's wise to mess up with the maths of how RD is calculated, it might just as well kill the whole system. Alternative is make a whole new system from scratch.

Btw Starcraft 2 doesn't have any RD, RD is specifically from the glicko system. They use a proprietary one called MMR, and they do have automatic decay; if you don't play for a while your MMR will linearly decrease.

**Comment by o5k** [comment]
Unless the current system shows major issues, I'd rather not fiddle with the formulas. Glicko-2 is used as-is in a lot of competitive settings and performs quite well there. RD is an integral part of that Glicko-2 system.

**Comment by trudnorx** [comment]
@o5k The only reason I say it is because I've been very frustrated when playing games with Glicko-like systems due to this exact problem. Yes, Glicko-2 can perform quite well as far as everything else is concerned, but I don't think there's any evidence that it handles this particular aspect well at all. On the opposite, this problem has been mentioned as being endemic to Glicko-2.

If you play very actively, your RD decreases, and even if your skill is increasing very quickly, the system doesn't reflect that fast enough, which is frustrating. StarCraft II's way, which could be introduced here with a slight modification, is far better at handling that problem. If you're winning or losing a lot of matches, it realizes the system is predicting your skill wrongly, and increases the system's uncertainty value regarding your skill level, allowing you to start facing tougher opponents more quickly and increasing the amount of points you gain/lose for each match.
