### ISSUE TITLE
sonic drop when using ARS

### ISSUE THREAD

**Issue by tohumaster69420** [o5k/tetrio-issues#251]
as someone who likes to play tetris the grand master 3, i like to use ARS when playing. so when i tried to play tetr.io solo mode with ARS, i was quite annoyed at the exclusion of the sonic drop, as i noticed it was replaced with the hard drop. this put me off my game quite a bit as i was used to being able to control the blocks after using a sonic drop, something you can't do with hard drop

**Comment by Wirtualnosc** [comment]
I'd argue it's just better to have it as a separate option, to allow for sonic drop outside ARS as well; see #203

**Comment by o5k** [comment]
Duplicate of #203 .
