### ISSUE TITLE
Custom game's countdown interval setting is ignored upon retrying

### ISSUE THREAD

**Issue by Volleo6144** [o5k/tetrio-issues#255]
### Describe the bug/issue
If you press the "R"/retry key on a custom game with a non-default countdown interval, that setting will be ignored.

### Reproducing
1. Go to "Custom Game"
2. Change the "Meta > Countdown Interval" setting to something noticeably different from default
3. Start the game
4. (...)
5. Hold R to retry

### Expected behavior
The countdown interval setting would be used again after restarting.

### Screenshots
![Well, we're going to be here awhile...](https://user-images.githubusercontent.com/38385509/79048030-e51c9300-7bdf-11ea-8131-99b42181bf8f.gif)

### Your setup
- macOS 10.15.5 beta
- Firefox 76.0b3

### Additional context
I'm not sure there's much to say about this one. I didn't check all the other custom game settings.

**Comment by o5k** [comment]
Fixed in next patch.
