### ISSUE TITLE
Option to configure delay after joining Tetra League

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#257]
### Is your feature request related to a problem? Please describe.
Not quite.

You know when you join Tetra League and immediately join a match? I was wondering if you could add a buffer time before this happens in case you want a 30 second warm up or to get ready/whatever.

### Describe the solution you'd like
A checkbox and slider, like I quickly coded [here](https://i.imgur.com/yoYDWRB.png)

### Describe alternatives you've considered
Just... waiting to join Tetra League. However you might end up waiting much, much longer in order to find a worthy opponent.

**Comment by o5k** [comment]
Changing the way the matchmaker functions on a client-by-client basis is not planned.
