### ISSUE TITLE
Finding Tetra League match right as a solo game starts breaks it

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#258]
### Describe the bug/issue
When you go and join Tetra League and start playing a solo game, if you get matched right as the board is coming down you get some _really_ weird behavior. The menu starts flashing up (which it already when you get matched in-game regardless 👀), the board is spazzing, it's fun

### Reproducing
Above

### Expected behavior
The board should shrink back and explode into particles, with the into scene overlaying.

### Screenshots
Since this is such a rare occurrence, it's really hard to video it

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 80.0.361.111

**Comment by o5k** [comment]
Hotfixed.
