### ISSUE TITLE
i keep getting dced but i dont think its an internet issue, ive been on ethernet connection but this prompt keeps showing up. What do u thikn

### ISSUE THREAD

**Issue by MOZARdotJPG** [o5k/tetrio-issues#259]
### Describe the bug/issue
I keep getting disconnected but i dont believe the internet connection's the issue as i've said i am connected via ethernet port.

### Reproducing
1. I play the game
2. Game runs normally for like the first two minutes
3. Out of nowhere I get this same prompt telling me something abt my grace period being up

### Expected behavior
Expected to keep playing the game lmao.

### Screenshots
![02EF9624-368B-4D24-994A-A9708D5B6E13](https://user-images.githubusercontent.com/63534676/79063130-53da1900-7cd2-11ea-8a41-a51617a153fb.jpeg)

### Your setup
 - Windows 10, also tried on my Macbook same problem occurs*: [e.g. Windows 7]
 - Chrome version 80.0.3987.163

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by LayneTheEpic** [comment]
Needs info? I can't reproduce and doubt OSK can either
Try on a different Wifi network ex. a friends' house

**Comment by o5k** [comment]
How fast is your internet?

**Comment by LayneTheEpic** [comment]
Ethernet makes me think that it's not *that* slow but definitely try Internet somewhere else.

**Comment by alex-ong** [comment]
Ethernet doesn't mean your connection is fast; it just means the connection between your computer and the router is fast.

**Comment by JasonBaby87** [comment]
Post your OOKLA result

**Comment by o5k** [comment]
I'll see if I can do some fallback magic to make it resend the event in case it gets dropped. However, if your internet gets delayed so far it builds up a 15s delay there's nothing I can do!

**Comment by o5k** [comment]
Ok, it should be better now (perfect is impossible, but yknow). Let me know if it keeps happening!

**Comment by EsteeSia** [comment]
tetrio really is a bitch every time it disconnect me from the server they count it as surrendering and my ranking goes down wtf
