### ISSUE TITLE
Controller disconnected warning

### ISSUE THREAD

**Issue by Tenchi2xh** [o5k/tetrio-issues#260]
If no controller is detected and the current key bindings include controller buttons, the game could show a warning

This mistake can happen quite easily since menu navigation is done with the mouse – if it was done with the controller as well the user would realize something is wrong way before entering a match (I once entered a league match while my controller was disconnected, and the bluetooth takes a long time to connect so I had piled up at least 4-5 pieces already)

**Comment by o5k** [comment]
Added in a recent patch.
