### ISSUE TITLE
Wrong notification pops up when getting kicked from room

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#261]
When you get kicked from a room and confirm the dialog, a notification briefly pops up about "Installing required update" - but there's no update to be installed in first place.

Speaking of that, I've never saw that notification show up on actual updates...

**Comment by LayneTheEpic** [comment]
I've only seen something similar when first joining Tetra League and it wants to update

**Comment by o5k** [comment]
Fixed in next patch.
