### ISSUE TITLE
ARS - S-piece does not have correct offsets

### ISSUE THREAD

**Issue by simonlc** [o5k/tetrio-issues#263]
### Describe the bug/issue
In ARS, the S-piece should rotate like this:
![S-piece rotation](https://i.imgur.com/zsfFbr8.png)

Instead the S-piece rotates like this: https://gfycat.com/sphericalelderlyankolewatusi

**Comment by simonlc** [comment]
This page has indepth information about ARS. https://tetris.wiki/Arika_Rotation_System

**Comment by o5k** [comment]
Fixed in next release.
