### ISSUE TITLE
Some internet pages makes the controller not detected by tetr.io

### ISSUE THREAD

**Issue by Raoul1808** [o5k/tetrio-issues#269]
### Describe the bug/issue
Having an internet tab/source that uses gamepad makes the gamepad no longer detected by tetr.io

### Reproducing
1. Load a tab with a gamepad viewer (my case was with https://gamepadviewer.com/ )
2. Reload tetr.io page

### Expected behavior
The controller should work in-game

### Your setup
 - Windows 10
 - Firefox 75.0

### Additional context
I noticed this happens both on a browser tab and as a browser source in OBS (Streamlabs OBS in my case).
You can play with the controller while the browser tab/source is running, but you need to first close that tab/source, then reload Tetr.io, then re-open (or re-enable) the browser tab/source.

**Comment by o5k** [comment]
This is due to how browsers and controllers work - only one tab may use one controller at the same time.
