### ISSUE TITLE
Chat key during match no longer works

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#27]
Pressing the chat key during a match unfocuses the game, but doesn't bring up chat

**Comment by mat1jaczyyy** [comment]
Actually, seems like it does open and is functional, but is invisible?

**Comment by o5k** [comment]
This seems to be because I broke the "do not display chat ingame" toggle, so chat would be disabled for some randomly

However, if chat is disabled, the Chat key should not do anything, so I fixed that, and will go live next patch
