### ISSUE TITLE
Falling blocks flash / flicker in spectator mode with many players

### ISSUE THREAD

**Issue by mcpower** [o5k/tetrio-issues#272]
### Describe the bug/issue
In Quick Play (or a match with many players?), spectating a user results in their falling blocks flickering every few frames. The ghost also flickers with the block. The problem seems to go away once more people get eliminated.

### Reproducing
1. Spectate a Quick Play match (or a match with many players?)

### Expected behavior
Falling blocks fall normally

### Screenshots
Video of the issue: https://mcpower.me/u/055/tetrio-flicker.mp4

Here's two frames of that video showing the problem:

![tetrio-flicker_00 00 00 483](https://user-images.githubusercontent.com/6015058/79682419-679ef580-8265-11ea-898f-9851973a3d19.jpg)

![tetrio-flicker_00 00 00 500](https://user-images.githubusercontent.com/6015058/79682420-6b327c80-8265-11ea-9222-12b7b37e2825.jpg)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chrome 80.0.3987.163. Persists on Chrome Canary (84.0.4119.0) and Firefox 75.0.

### Additional context
Tested on:

> Local version 2.3.0-production | Commit 29eef03 (4/19/2020, 11:07:09 AM) | Server cycle ryC0NSxbU | Build bsXL6S76w (4/19/2020, 11:57:43 AM)

**Comment by o5k** [comment]
Sadly I cannot reproduce this, are you on WebGL2? (Check console)

**Comment by mcpower** [comment]
Yes, I get `PixiJS 5.2.1 - WebGL 2` in my console.

It could be because my graphics card drivers are out of date (GeForce GTX 1060 6GB, 436.30). I'll try updating them and seeing whether the bug persists…

**Comment by o5k** [comment]
Is this fixed now? Or does switching to WebGL 1 fix it?

**Comment by mcpower** [comment]
Fixed now using WebGL2.

Here's my console logs as of writing, in case there's a future regression:

```
Up to date. Local version 2.4.0-production | Commit a639281 (4/25/2020, 10:59:44 AM) | Server cycle C40Nj2PpV | Build USYKFt1bM (4/25/2020, 11:11:32 AM) | PID 5303
PixiJS 5.2.2 - WebGL 2
- Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36 -
CPU: 12-core
Memory: ~8 GB
Connection: 10 Mbps, 50ms RTT [4g]
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
```
