### ISSUE TITLE
Other boards are inconsistently layered relative to player board while spectating

### ISSUE THREAD

**Issue by mcpower** [o5k/tetrio-issues#273]
**This is a *very minor* visual bug that is only noticeable when Board Bounciness is set to a high value, and only affects spectating.**

### Describe the bug/issue
While spectating, other players' boards are inconsistently layered relative to the currently spectated player's board. Some other players' boards are displayed on top of the spectated player's board, while some are displayed below it.

### Reproducing
1. Set Board Bounciness to 200%.
2. Spectate a game with 3+ players in it.

### Expected behavior
Other boards are either all displayed on top or all displayed below the spectated player's board.

### Screenshots

![image](https://user-images.githubusercontent.com/6015058/79741099-03069800-8344-11ea-93a8-0174887b34ea.png)

This does not persist in-game - other boards are consistently displayed on top of the player's boards.

![image](https://user-images.githubusercontent.com/6015058/79741119-0ac63c80-8344-11ea-9441-42a47ed0655c.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chrome 81.0.4044.113

### Additional context
Browser log:

```
Up to date. Local version 2.3.0-production | Commit 29eef03 (4/19/2020, 11:07:09 AM) | Server cycle ryC0NSxbU | Build bsXL6S76w (4/19/2020, 11:57:43 AM) | PID 16323
PixiJS 5.2.1 - WebGL 2
```

**Comment by o5k** [comment]
Reordering game boards like this is difficult and expensive CPU-wise... So wontfix for now
