### ISSUE TITLE
Custom background crashing Sprint

### ISSUE THREAD

**Issue by BurningPain** [o5k/tetrio-issues#274]
### Describe the bug/issue
Setting up custom background caused sprint to crash. Once I started sprint, I got only black screen with no board/background

### Your setup
 - **OS and version**: Windows 8.1
 - **Browser and version**: Chrome 81

### Additional context
![image](https://user-images.githubusercontent.com/43996537/79907994-cc4f8100-841a-11ea-908a-7f4bf76e952c.png)

**Comment by o5k** [comment]
Try a different imagehost?

**Comment by BurningPain** [comment]
Different imagehost didn't do anything. I tried multiple hosts and none of them loaded. Btw if I just inserted the link and tried to play it would crash. If I reloaded the website and tried to play I could but the background wouldn't load

**Comment by o5k** [comment]
Cannot reproduce the crash - seems to be caused by CORS, try say, imgur
