### ISSUE TITLE
"Disconnected from server" shout lacks image on server restart

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#278]
### Describe the bug/issue
When the server restarts, one of the shouts in the corner says "disconnected from server". It lacks a valid image source/alt, and I wasn't able to snag what it refers to inside dev tools sadly.

### Reproducing
1. Have server restart (you get disconnected)
2. Look at the shouts in the bottom corner
3. See error

### Expected behavior
The image should show

### Screenshots
[Here](https://i.imgur.com/LtK8XwA.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Chromium-Edge 81.0.416.64

**Comment by o5k** [comment]
The image doesnt show because the server is down by the time it tries to pull the image. I could cache it beforehand but that's kinda silly
