### ISSUE TITLE
The ghost piece is barely visible. A way to customize it or making it more visible would be nice.

### ISSUE THREAD

**Issue by Xenos456** [o5k/tetrio-issues#279]
I can barely see the ghost in 40 lines with the default backgrounds/black background, and I messed around with various settings. My solution was to use a custom background and having the opacity set to around 50%.

![image](https://user-images.githubusercontent.com/25555828/80269051-737e2380-867a-11ea-8c8f-be8c05a80699.png)

This image above shows how it looks like at 100% transparency, some backgrounds have the ghost more visible to others. My suggestion for an improvement is to add an option to make the ghost piece more visible by default.

**Comment by LayneTheEpic** [comment]
If we could add a slider to configure ITS opacity as well...
Or maybe a dynamic ghost piece that's color is the inverse of the background, to stand out. Who knows?

**Comment by meppydc** [comment]
A colored ghost piece might help as well.

**Comment by Xenos456** [comment]
I've also noticed, when reaching the top of the board, the board turns red and the ghost piece becomes invisible as well.
![image](https://user-images.githubusercontent.com/25555828/80290894-be4d7900-8716-11ea-93f4-968c663e7c26.png)

**Comment by LayneTheEpic** [comment]
Isn't that counter intuitive though @meppydc? If you're placing an O piece against a yellow background that doesn't help

**Comment by JasonBaby87** [comment]
I guess one way to make the ghost piece always clear is using images with two colours. Just like how adding black outline to white subtitle text makes it pretty much always distinguishable from the background (with enough opacity though...)

**Comment by TSTman** [comment]
> Isn't that counter intuitive though @meppydc? If you're placing an O piece against a yellow background that doesn't help

In my case, the ghost piece is difficult to see due to using 100% grid visibility, and colored ghost pieces would absolutely help.

![Ghost piece is difficult to see when using 100% grid visibility](https://user-images.githubusercontent.com/13359756/80337928-5b440b00-8818-11ea-8f40-032e03753dd8.png)

If you use yellow backgrounds and you don't want colored ghost pieces, maybe it should be an option to disable or enable.

**Comment by o5k** [comment]
Custom opacity for the ghost piece is planned for relatively soon, as a video option. Colored ghosts will be a feature introduced together with skins (e.g., the game will ship with a default "colored ghost" skin)

**Comment by o5k** [comment]
Added in next patch!

**Comment by TSTman** [comment]
Way better, thanks!
