### ISSUE TITLE
Improve League Post-Match Messaging

### ISSUE THREAD

**Issue by Xelitik** [o5k/tetrio-issues#281]
I keep on accidentally leaving a conversation in league because it is different than quick play and custom rooms (In which I would instinctively hit NEXT to continue chatting, it instead makes me leave the room in League). Instead of putting the chat on the results screen, make the NEXT button on the league results screen take you to the chat then have an EXIT button to take you to the league screen.

**Comment by o5k** [comment]
Sounds like very annoying UX. Right now the two mimic oneanother in that:

Multiplayer rooms: `lobby` -> `ingame` -> `results` -> `lobby`

League: `lobby` -> `ingame` -> `results` -> `lobby`

where `lobby` is a main screen from which a game could start at any moment (e.g. a room, or a matchmaking queue)

Adding a second step to get back into the lobby would be like having 2 pages in the results screen of a normal lobby, so to say.
