### ISSUE TITLE
Disable music

### ISSUE THREAD

**Issue by RyanCarrier** [o5k/tetrio-issues#282]
### Is your feature request related to a problem? Please describe.
I hate background music in games, if I want music I'll listen to my own, and there is no volume option either...

### Describe the solution you'd like
Ability to select no music, or disable music, or audio slider for music/sfx

### Describe alternatives you've considered
Ability to select no music, or disable music, or audio slider for music/sfx

**Comment by Tenchi2xh** [comment]
You can already a volume option in the config page:

![image](https://user-images.githubusercontent.com/4116708/80304813-ceb63000-87b8-11ea-9a15-a9268f6269aa.png)

You can also do it while in game, if you scroll the mouse wheel during a match you can separately reduce the volume of the BGM or SFX
