### ISSUE TITLE
B2B indicator doesn't show up when switching a player to spectate

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#284]
### Describe the bug/issue
The B2B indicator doesn't show up when switching between players as a spectator. It will only show up when it has to update (higher B2B streak or it being broken).

### Reproducing
1. Join QP as spectator (or as a player and top out during a game)
2. Switch from any different player to a player that currently is on a B2B streak

### Expected behavior
The B2B streak should show up as soon as the switch happens.

**Comment by o5k** [comment]
Fixed in next patch.
