### ISSUE TITLE
Fast-restart on solo-modes

### ISSUE THREAD

**Issue by robertlandlord** [o5k/tetrio-issues#286]
One of the things I run into is that tetr.io takes approximately 5-10 seconds between each try of 40 second mode. Sometimes, I want to restart quickly (without having to hold down the escape button, then press back into solo mode)

Possible solution: Similarly to some other tetris clones, one option may be to press escape and have a separate screen for options like "restart, quit, etc". that way, it would be less tedious to have another try.

**Comment by JasonBaby87** [comment]
Enable stride mode and press the restart button

**Comment by robertlandlord** [comment]
Wow I had no idea this existed. Thanks
