### ISSUE TITLE
js memory leak

### ISSUE THREAD

**Issue by UniQMG522** [o5k/tetrio-issues#287]
### Describe the bug/issue
Memory usage grows without bounds between games.

### Reproducing
1. Play multiple matches
2. Watch memory grow

### Expected behavior
Memory usage doesn't grow indefinitely. 

### Screenshots
![firefox_8ST9wZh77D](https://user-images.githubusercontent.com/48872143/80366969-167f9a80-883f-11ea-8e61-f0be8a2962f9.png)
Game disconnected and auto-refreshed due to lag from having devtools + memory dump open, but without devtools open it grows indefinitely. Memory dumps taken at one-game intervals in quick play, mix of spectating + playing.

### Your setup
 - **OS and version**: W10 
 - **Browser and version**: Firefox 76

### Additional context
Some other users have had issues with high memory usage ([for example here in #tetra-league, reports chrome with total browser memory upwards of 1.5gb](https://discordapp.com/channels/673303546107658242/696095920248455229/704267172284989460))

Possibly related: #37

**Comment by o5k** [comment]
Fixed in next patch.
