### ISSUE TITLE
Random disconnecting

### ISSUE THREAD

**Issue by steve4ino** [o5k/tetrio-issues#292]
### Describe the bug/issue
Playing any multiplayer game results in a disconnect after a few minutes although I don't have a problem with my internet on any other sites

### Reproducing
Playing any multiplayer game results in a disconnect.

### Expected behavior
Not to be randomly disconnected

### Screenshots
![image](https://user-images.githubusercontent.com/63077213/80597195-6a48da00-8a1f-11ea-9e51-67b12418ebf6.png)

### Your setup
 MacOS 10.14.1
Chrome Version 81.0.4044.122 (Official Build) (64-bit)

**Comment by o5k** [comment]
This is an internet issue. Next patch will reduce Tx cost, but this error is caused by your internet falling far behind.

**Comment by rwzhang1** [comment]
late response but I discovered I encountered this problem because I was having 0 upload speeds with download speeds being normal. So do a speedtest to check your internet is actually working normally
