### ISSUE TITLE
Make the config far more seperated (if that makes sense?)

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#293]
### Is your feature request related to a problem? Please describe.
literally just look at the video section, its absolutely massive, we could sincerely use some more sub-categories for easier understanding and finding of certain settings

### Describe the solution you'd like
have a few more sub-divisions under the video settings that make it easier to find things

such as maybe a "board settings" that would contain stuff like the board size and grid opacity maybe some other things

"Piece settings" that would be like hearing the next piece, colored shadows, stuff like that

some other stuff as well obviously but those are just examples that i'd like to see for ease of use

**Comment by Neeko-iko** [comment]
you could also make a whole new section called "Gameplay" which would be helpful as well

**Comment by o5k** [comment]
Added in next patch!
