### ISSUE TITLE
Quick play broken

### ISSUE THREAD

**Issue by UniQMG522** [o5k/tetrio-issues#295]
### Describe the bug/issue
Quick play broken, apparently admin panel also broken. Unable to send garbage in quick play, quick play board layout is broken. Disconnects due to "No data received".

> *(From Darksidez910#7092 in #issue-report)*
> Some MAJOR bugs have been occurring tonight, mostly affecting quickplay. 
> - Player count is consistently breaking in quick play, often alternating between 0 and the actual 
amount
> - Lobbies are also breaking almost EVERY OTHER GAME.. It makes it so you have 0 gravity increase after a certain point, and it makes it impossible to send damage and you always have a clean board besides what you place
>  - It is also struggling to load in profiles, often times never loading after minutes of waiting 
>  - Also Admin Panel has broken many times tonight. 
> - Visually boards are also breaking 
> - It also locks you on a black screen after every game

### Reproducing
1. Enter quick play

### Expected behavior
Quick play should not be broken.

### Screenshots
While playing:
![image](https://user-images.githubusercontent.com/48872143/80673039-15c74e00-8a63-11ea-9038-c98520198987.png)
While waiting:
![image](https://user-images.githubusercontent.com/48872143/80672893-b5d0a780-8a62-11ea-9f29-a9f8c1da61e5.png)

### Your setup
 - **OS and version**: W10
 - **Browser and version**: Chrome 81, Firefox 76

**Comment by UniQMG522** [comment]
Quick play appears to be working fine now, current steps to reproduce insufficient.

**Comment by o5k** [comment]
Somehow a user appeared with username `null`. Not sure how this happened, will keep monitoring. A fix has been applied, but we'll see :/
