### ISSUE TITLE
Holding input during Tetra League countdown causes some subsequent inputs to be dropped

### ISSUE THREAD

**Issue by professor-l** [o5k/tetrio-issues#299]
### Describe the bug/issue
If I hold a directional input during the countdown at the beginning of a Tetra League match, each subsequent input, if it is said input's first time being pressed, is ignored only once.  After all inputs have been triggered and ignored, everything proceeds normally.

### Reproducing
1. Enter a Tetra League match
2. Say something in chat (I like to wish my opponents good luck, and I *think* this is necessary to reproduce the issue)
3. Hold a directional input (right or left) *before* the countdown ends
4. Keep said input held until after the game starts and the first piece shifts to the edge of the playfield
5. Continue playing - each input, *including the one that was held at the beginning*, will now be ignored precisely once.  All subsequent inputs are registered as normal, as far as I can tell, with the exception of the first **of each type**.  This includes CW and CCW rotation, hard and soft drop, left/right shifts, and hold.  I assume it includes 180 degree rotations as well, though I don't use them and have not tested this.

### Expected behavior
Inputs to register normally for subsequent pieces

### Screenshots
N/A

### Your setup
 - **OS and version**: Windows 10 Home (version 1903, build 18362.778)
 - **Browser and version**: Firefox version 75.0

### Additional context
Nothing out of the ordinary in the console.  My keybindings are as follows:
```
J - Move piece left
L - Move piece right
K - Hard drop
Space - Soft drop
E - Rotate CCW/left
F - Rotate CW/right
C - Hold
D - Rotate 180 (I never use it)

T - Chat
```

Happy to answer comments with questions if you want more context or info.  I am not able to *consistently* trigger this bug on any games in the match other than the first.  It can happen, but I don't know why it does or doesn't.  However, on the first game in a match, following the above steps, I am able to consistently reproduce it.  I also am almost always holding left, not right, at the beginning of games because I like my first piece against the left wall (it's probably an NES habit), though I am fairly confident the issue is reproducible with either directional input.

**Comment by o5k** [comment]
Fixed in a recent patch.
