### ISSUE TITLE
Solo modes can't be reset during game start countdown

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#3]
It's a bit annoying to wait in 40 Line on an SZ start, especially if a specific opener is used a lot. It should be possible to hold reset during the countdown to reset early.

**Comment by mat1jaczyyy** [comment]
Might get more or less automatically solved if #1 is solved in a way which extends the game engine into the countdown timer

**Comment by o5k** [comment]
Fixed in upcoming patch!
