### ISSUE TITLE
Kicks sometimes don't work

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#30]
Config:
![image](https://user-images.githubusercontent.com/13300194/74106216-fce68500-4b64-11ea-8aba-05981dddbb10.png)

Game settings:
![image](https://user-images.githubusercontent.com/13300194/74106219-0374fc80-4b65-11ea-90b1-c9477763909e.png)

Repro:
1. Hold Softdrop key during countdown
2. When the first piece spawns, it should immediately go to the floor due to our settings.
3. Without releasing softdrop, attempt to rotate the piece.

No rotation occurs and no rotation sound either. The piece should rotate and floorkick. Works with all pieces apart from O (since it doesn't kick). Tapping movement first and then rotating, still no rotation occurs even though movement does occur.

This has been observed in multiplayer but a bit inconsistently, this repro should work 100% of the time

**Comment by o5k** [comment]
Fixed in next version (hopefully)
