### ISSUE TITLE
Keyboard Cursor goes off screen if navigate buttons are held down

### ISSUE THREAD

**Issue by clxxiii** [o5k/tetrio-issues#302]
### Describe the bug/issue
If you hold down a navigation button, the screen doesn't scroll with the keyboard cursor

### Reproducing
1. Go onto any menu that is longer than one page
2. Hold down a navigate button.
3. The screen will move with the first hit, as it repeats, the screen doesn't scroll.

### Expected behavior
The screen should scroll down to follow the outline as the navigate button is held.

### Screenshots
[Video](https://drive.google.com/open?id=1A2hl8QHcJrmiSZWnsdPWoi3WrvBaR_aK)

### Your setup
 - **OS and version**: Windows 10 Version 1909
 - **Browser and version**: Microsoft Edge Version 81.0.416.68 (Official build) (64-bit)

**Comment by o5k** [comment]
This is due to how browsers handle smoothscroll for this, sadly
