### ISSUE TITLE
make smaller text not look like spongebob mocking meme

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#304]
### Is your feature request related to a problem? Please describe.
This is the first time it's happened, and i sincerely appreciate the banner at the top saying this

but small text looks like the spongebob mocking meme with how much the size of each letter fluctuates so much.

it makes it far harder to read than it needs to be.

### Describe the solution you'd like
the font should either be changed to an entirely different font, or straight up reworked.

### Additional context

![image](https://user-images.githubusercontent.com/45524401/80937309-6bfcff80-8d89-11ea-93d2-497448deb88f.png)

**Comment by Tenchi2xh** [comment]
Looks like the antialiasing of your OS doesn't work super well
Here's how the same banner looks like on mac:

![image](https://user-images.githubusercontent.com/4116708/80938628-2a487500-8dda-11ea-9c25-a25680c8241c.png)

Maybe the font requires better [hinting](https://en.wikipedia.org/wiki/Font_hinting) ? It's a part of the font that helps the renderer align better to the pixel grid when in low res

**Comment by o5k** [comment]
yep, i forgot to rehint the glyphs i changed
woops

should be better in next patch!
