### ISSUE TITLE
search box continues to search after searching

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#307]
### Describe the bug/issue
After searching once the text box to search stays active

### Reproducing
1. Go to Tetra Channel
2. Search anybody
3. Type something and search again (use backspace to clear the search)

### Expected behavior
After searching once the text box to search shouldn't become active

### Screenshots
![image](https://user-images.githubusercontent.com/45524401/81138633-911f7880-8f17-11ea-8927-ee61ac15b1f2.png)

### Your setup
 - Windows 10
 - Chromium Edge 81.0.416.68

**Comment by Neeko-iko** [comment]
another way to clear this up would be if you pressed anything on the keyboard the user you searched would disappear and the box could still be left active (preferably it'd reset after searching)
which might be preferred

**Comment by o5k** [comment]
Fixed in next patch!
