### ISSUE TITLE
ARS Colors Do Not Match Colored Ghosts

### ISSUE THREAD

**Issue by ZaptorZap** [o5k/tetrio-issues#308]
### Describe the bug/issue
Simple dimple title.
### Reproducing
Here's your steps:
Make sure colored ghosts are on.
Start a custom game, of either single player or multiplayer variety.
Change the kick table to ARS.
### Expected behavior
Colored ghosts should be the same color as the piece it's signifying. In ARS, the colors are switched, but the ghost colors are not.
### Screenshots
Here's a [video,](https://youtu.be/1Y0bJ_leVgk ) showing the disconnect between the two, 
### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Firefox 75

**Comment by o5k** [comment]
Fixed in next patch!
