### ISSUE TITLE
Quick play lobby is getting stuck

### ISSUE THREAD

**Issue by Xloade** [o5k/tetrio-issues#31]
Quick play lobby getting is stuck with message "currently ingame"

osk's prediction:
→ worker dies for Unknown reason (This is bug 1)
→ worker reports a netsplit, server removes all players in the room
→ said players are not removed because unlike disconnects, the entire game object is gone because the worker died
→ the referee never gets to know that the netsplit games have ended (This is bug 2)
→ the referee assumes there is still an ongoing match

**Comment by reolat** [comment]
Frontend shows this screen

![image](https://user-images.githubusercontent.com/11707351/74163556-d7b84c00-4c22-11ea-88bc-424aebaf68a1.png)

**Comment by o5k** [comment]
Bug 2 is hopefully fixed. I added logging so next time we should be able to see what caused everyone in the room to DC...
