### ISSUE TITLE
my chat only see bottom part..

### ISSUE THREAD

**Issue by tello911** [o5k/tetrio-issues#316]
### Describe the bug/issue

I can only see bottom part of my chat..
like
--LOL--
I can see word LOL but only below -- level..

but scrolling the chat is fine..
### Reproducing
2. Click on '...'
3. Scroll down to '...'

### Expected behavior

Idk is it normal.. but I expected to see fully my word.. 
### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Can you post a screenshot?

**Comment by tello911** [comment]
Well, its alright right now.. but idk how to delete the issue in github..
thanks for your consideration..

**Comment by tello911** [comment]
![Capture](https://user-images.githubusercontent.com/65243549/81760954-38457680-94fb-11ea-8497-7f5a87340735.PNG)

well, at the bottom left the chat is not fully shown.. well, sometimes maybe good.. sometimes maybe shit..

**Comment by tello911** [comment]
well, if this is not a bug.. I am really sorry.. but I think it's better to put a little space so I can see what I want to write better.. or maybe my mouse is faulty.. idk much about technology..

**Comment by LayneTheEpic** [comment]
Is your browser zoomed in? Press Ctrl+ - (minus) to see if that helps

**Comment by tello911** [comment]
Well, it's not helping me.. because it only works wrong sometimes.. but
usually it's fine.. I think I am gonna close this issue since most of the
time it's fine.. and I can still play it good..
