### ISSUE TITLE
API for account stats

### ISSUE THREAD

**Issue by JaibreyonLourens** [o5k/tetrio-issues#317]
an API for your account stats you can request so you can use that info for example streaming so that updates automatically

**Comment by gizmo4487** [comment]
> an API for your account stats you can request so you can use that info for example streaming so that updates automatically

This already exists! Send a request to https://tetr.io/api/users/me with the header "Authorization: Bearer (token goes here)"

**Comment by JaibreyonLourens** [comment]
Ok thanks, where can you request the token?

**Comment by gizmo4487** [comment]
> Ok thanks, where can you request the token?

If you are on Chrome, press F12, go to the Application tab, and select "Local Storage". On Firefox, press F12, go to the Storage tab, and select "Local Storage". Your token will be listed under "userToken".

**Comment by JaibreyonLourens** [comment]
Ok thanks a lot, last question how do you make the request because I did it how you sai but I still get the error i did it like this https://tetr.io/api/users/me Authorization: Bearer (token) but it failed

**Comment by gizmo4487** [comment]
> Ok thanks a lot, last question how do you make the request because I did it how you sai but I still get the error i did it like this https://tetr.io/api/users/me Authorization: Bearer (token) but it failed

What programming language or tool are you using? We could probably take this conversation to the TETR.IO Discord server.

**Comment by JaibreyonLourens** [comment]
sure my discord is jai013
