### ISSUE TITLE
"Hotfix" for not being able to spectate ongoing games

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#319]
Currently, the game just displays "Quick Play - Good luck!" or the room settings menu while ingame. If you could add a small widget that displays how many people are left that'd be nice. Later once you can hop into the ongoing game this can be removed.

**Comment by csq-curiosity** [comment]
Duplicate of #202. This one's a little more comprehensive in that it also includes game time, and score counts for FT2+ games.

**Comment by LayneTheEpic** [comment]
I see, thanks for letting me know, I'll probably close this issue
