### ISSUE TITLE
ARR 0

### ISSUE THREAD

**Issue by julf0** [o5k/tetrio-issues#32]
Jstris speedplayers would like this added, might not be beginner-friendly

**Comment by Xloade** [comment]
until it's added you can modify it in venerable where it's being saved. Not sure about chrome but in firefox it's under dev tools > storage > local storage. It's not very user friendly way tho.

**Comment by o5k** [comment]
no, unlike other settings, Handling values cannot be modified outside of what the config shows, if you think you're playing any different now that you switched it to 0 using said method, you're enjoying placebo

**Comment by o5k** [comment]
The game is very high-power as is, so I feel adding more tools will make it impossible for newcomers to play. Need opinions...

**Comment by o5k** [comment]
Considering the difference betwen .1 and 0, I've decided to add ARR 0. It'll be here next patch.
