### ISSUE TITLE
Can't open Tetra Channel tab from log-in screen, but can from About page

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#323]
^ that

You can see it [here](https://youtu.be/5hVVrjBcSiI)

Until it's ready you should make some sort of notification when it's clicked :p

**Comment by csq-curiosity** [comment]
![cs](https://user-images.githubusercontent.com/62501780/82105716-b69e5480-9757-11ea-94b3-fa9338166bc8.PNG)

It does notify me when I click on it. (I use Chrome 80). Maybe you right-clicked to open in new tab/window or something?

**Comment by LayneTheEpic** [comment]
The about page, that is- if you check the video you'll see it's the same tab

**Comment by o5k** [comment]
This is temporary, so eh
