### ISSUE TITLE
Music loads slowly

### ISSUE THREAD

**Issue by ryanbraganza** [o5k/tetrio-issues#324]
### Describe the bug/issue

I noticed when playing games, there wouldn't be any music at the start of the game. Looking at the network traffic, it is just loading slowly. However, if it was randomly picking a song that had been played before during that session, it would play immediately.

I've played enough tetrio games that I've heard all the songs before, so I expected them all to have been cached, but it looks like they're served with max-age=0 which could be increased.

### Reproducing
1. View response headers for e.g. https://tetr.io/sfx/tetrio.ogg

### Expected behavior
Since the song files are not likely to change, they should have a longer max-age (e.g. a week or even more)

### Your setup
 - macOS 10.15.4
 - Chrome 81

### Additional context

It looks like the files are served from Express. For the static files a CDN might improve performance and reduce hosting cost.

**Comment by o5k** [comment]
Fixed in a recent patch.
