### ISSUE TITLE
Black Screen on first time launch

### ISSUE THREAD

**Issue by SenorLing** [o5k/tetrio-issues#329]
I found tetr.io a few hours ago and played on the web version.
So I installed the desktop version and when I launch the desktop, it shows me the tetr.io start screen then after it freezes.
I can click onto something that leads me to https://tetr.io/about/privacy/ and https://tetr.io/about/
And when I try change the size of the window it just cuts to a black screen.

**Comment by SandblastFloflp** [comment]
I can report the exact same issue, even after a reboot.
Since specs are usually useful :
OS : Windows 10 version 1909 (or 18363 according to dxdiag)
Processor : Ryzen 5 3600X
Graphics : GeForce RTX 2070
I can provide more if needed.

**Comment by SenorLing** [comment]
I found a solution to the problem.
On the loading screen hold f4 for 4 seconds and that will cause the game to reboot and it worked for me.

**Comment by o5k** [comment]
Should be fixed now if F4 is held.
