### ISSUE TITLE
Game doesn't take your config info

### ISSUE THREAD

**Issue by tungster24** [o5k/tetrio-issues#331]
This mostly just is an import problem so I don't think I need to post my specs but whatever

Windows 10 64 Bit, Intel Core i7-8550U CPU (1.80-1.99GHz) 16 GB Ram (Discord downloaded)

Edit: Elaborating: I downloaded the offline version, and my controls weren't imported

pls fix thank in advance

**Comment by o5k** [comment]
The game does not store config serverside. An issue report already exists for this
