### ISSUE TITLE
The tetr.io cilent 

### ISSUE THREAD

**Issue by MarshmelT** [o5k/tetrio-issues#332]
### Describe the bug/issue
The tetramino could just be below the grid.

### Reproducing
1. Go to 'tetr.io desktop cilent'
2. Click on '40 lines or biltzs'
3. error could happened sometimes when you place a piece

### Expected behavior
the tetramino would be below the grid.

### Your setup
 - Windows 10 and the tetr.io desktop cilent
 

![bug_1 1 1](https://user-images.githubusercontent.com/65790684/82712120-e26e8c80-9cb9-11ea-87db-3223a151ab53.jpg)

**Comment by Hubza** [comment]
you're.. you're supposed to fill the template... not just...

**Comment by MarshmelT** [comment]
> you're.. you're supposed to fill the template... not just...
