### ISSUE TITLE
tetris piece below the grid

### ISSUE THREAD

**Issue by MarshmelT** [o5k/tetrio-issues#333]
### Describe the bug/issue
The tetramino could just be below the grid.

### Reproducing
1. Go to 'tetr.io desktop cilent'
2. Click on '40 lines or bilts'
3. error could happened sometimes when you place a piece

### Expected behavior
the tetramino would be below the grid.

### Your setup
 - Windows 10 and 64 bit operating system
 

![bug_1 1 1](https://user-images.githubusercontent.com/65790684/82712120-e26e8c80-9cb9-11ea-87db-3223a151ab53.jpg)

**Comment by o5k** [comment]
Fixed.
