### ISSUE TITLE
Discord Rich Presence Elapsed is incorrect...?

### ISSUE THREAD

**Issue by AleksaDjordjic** [o5k/tetrio-issues#334]
### Describe the bug/issue
Discord Rich Presence elapsed shows the time from when you start a match, I'm not sure if it was intended to be like that but it would a bit more informative if it actually showed the time from when the countdown ended and the match actually started rather than from when the start button was clicked...

### Reproducing
1. Start a match, singleplayer, multiplayer, either
2. Open Discord
3. View your rich presence

### Expected behavior
When the countdown ends, elapsed time on Discord should start counting

### Screenshots
![image](https://user-images.githubusercontent.com/33227154/82712806-2dbc7700-9c89-11ea-86de-0366292129e2.png)

### Your setup
 - **OS and version**: Windows 10 Pro 1909
 - **Browser and version**: TETR.IO Desktop v2

**Comment by o5k** [comment]
The Rich Presence time shows the amount of time spent in a specific mode, not the current timer. This is intentional.
