### ISSUE TITLE
UI glitching when fullscreening the window during gameplay

### ISSUE THREAD

**Issue by SoSheolH** [o5k/tetrio-issues#335]
### Describe the bug/issue
Whenever the window is fullscreened during any game, the grid goes below the boundary by two squares and to the right by one, and the UI showing which pieces are coming next overlaps with itself.

### Reproducing
1. Start a match in any mode with the default window size.
2. Click on the fullscreen button on the window when the countdown begins or any other time during the game.

### Expected behavior
Everything on screen to correctly stretch with the size of the window.

### Screenshots
![image](https://user-images.githubusercontent.com/65791451/82713015-7839f580-9c81-11ea-841e-739eb3a0afe5.png)

### Your setup
 - Windows 10 Pro Build 18363, 64 bit OS

**Comment by o5k** [comment]
Fixed (and duplicate).

**Comment by SoSheolH** [comment]
(not a duplicate technically, the other post talking about blocks below the grid was only by a couple of pixels, this is the actual grid going below alongside other things not mentioned there)
