### ISSUE TITLE
MULTIPLAYER VERSUS BLITZ

### ISSUE THREAD

**Issue by aggbhh** [o5k/tetrio-issues#344]
I think that you can do a **VS Multiplayer Blitz Mode** which will work like this: It will be like blitz who gets the most score divided by their lv wins! If you didn't understand, here's some numbers and stuff!

score = score (i mean, yeah)
lv =  level
total_blitz = score / lv

For Example:
Player a's level in tetr.io is 15.
he scored 18000.
his total_blitz is 1500.

Hope You understood and will work on this!

-aggbhh

**Comment by o5k** [comment]
Player level ≠ skill, so 2 players might have similar skill, while one is at player level 2 and the other is at player level 700. Sounds like it'd attract a lot of smurfs...

**Comment by o5k** [comment]
Race and timed modes are generally planned.
