### ISSUE TITLE
Piece controls and menu controls appear to cause errors

### ISSUE THREAD

**Issue by LayneTheEpic** [o5k/tetrio-issues#349]
![This](https://user-images.githubusercontent.com/50891500/83472943-71b43680-a456-11ea-9a0d-4e99ce348f68.PNG)
(I cropped to make issue more obvious)

### Describe the bug/issue
Honestly surprised no one's reported it... if a piece manipulation control (eg. left arrow) is the same as that of a menu control (also left arrow), they both appear in red. They shouldn't interfere (though it does function, it's not pretty D:<)

### Reproducing
1. Bind some menu control to the same as a piece of manipulation control
2. w h y

### Expected behavior
The errors should only appear within their 'categories'

**Comment by o5k** [comment]
Fixed in next patch.
