### ISSUE TITLE
Secret Grade Detection Bug

### ISSUE THREAD

**Issue by Omio** [o5k/tetrio-issues#36]
### Describe the bug/issue
Secret Grade disregards the 20th row, and shouldn't.

### Reproducing
1) Build Secret Grade solid to at least S9.
2) Fail to put the block above the GM hole to actually make GM.
3) Still succeed to "do the thing"???

### Expected behavior
Failure should be returned in this case, and the achievement fails.

### Additional context
Request to place in issue-tracker by osk.

**Comment by o5k** [comment]
Fixed in next update.
