### ISSUE TITLE
Disappearing Tetrimino (I piece)

### ISSUE THREAD

**Issue by AbsurdPotato1** [o5k/tetrio-issues#365]
### Describe the bug/issue
I was in tetra league and I held right with an I piece and it went to the edge and seemed to continue going off screen (disappeared).
### Reproducing
No idea how to reproduce but tetra league and I piece (vertical) is what i did.

### Expected behavior
I expected the I piece to stop at the edge.
### Screenshots
No screenshots 
### Your setup
Windows 10
Chrome 76

### Additional context
Was immediately kicked for hacker looking display with 21 discrepancies in the last frame.
I was also using a kinda laggy device.

**Comment by o5k** [comment]
Hotfixed.
