### ISSUE TITLE
Settings should be associated with an account

### ISSUE THREAD

**Issue by Denton-L** [o5k/tetrio-issues#367]
### Is your feature request related to a problem? Please describe.
Sometimes I switch between different computers or between the browser and desktop version of TETR.IO. If I change my settings, I have to change them on all the clients that I use.

### Describe the solution you'd like
When settings are changed, they should be associated with an account, not in the local storage for a client. That way, settings can carry over when I log into another client.

### Describe alternatives you've considered
Exporting and importing settings via a JSON file or something? It'd work for single-computer client use but it'd still be annoying because I'd have to save this file across all the computers I use.

### Additional context
N/A

**Comment by ZaptorZap** [comment]
Please take a look at #7, which was dropped for #245, making this a practical duplicate of an invalid suggestion.

**Comment by Denton-L** [comment]
Thanks.
