### ISSUE TITLE
Pressing enter doesn't submit password form

### ISSUE THREAD

**Issue by HellRok** [o5k/tetrio-issues#38]
### Describe the bug/issue
Just a small issue, when setting my email address it asked for my password and pressing enter after typing it in didn't submit, I had to manually click the submit button

### Reproducing
1. Go to config
2. Click on Account
3. Click save on email (Doesn't need to be changed)
4. Type a password
5. Press enter

### Expected behavior
I expect this to submit the form

### Screenshots
![passwordreset](https://user-images.githubusercontent.com/6147202/74596963-72db7680-50a6-11ea-82a5-0e790fa22766.png)

### Your setup
 - Fedora 31
 - Chrome 80.0.3987.106 (Official Build) (64-bit)

**Comment by o5k** [comment]
Fixed in next patch.
