### ISSUE TITLE
Multiplayer player listing animation plays the animation on all items

### ISSUE THREAD

**Issue by o5k** [o5k/tetrio-issues#39]
?????? but not for me LOL ?????????

**Comment by Wirtualnosc** [comment]
Ok so I can confirm this happens on Opera 66.0.3515.72 but not Firefox 73.0; seems to be browser dependent.

**Comment by Neeko-iko** [comment]
as an Opera GX user I can confirm it is with probably all versions of Opera available.
I never paid it any mind because quite frankly i thought it was just intended - happens in other games browser or not.

**Comment by o5k** [comment]
Can anyone test on Chromium 66? I have 67 myself, maybe 67 handles it fine but 66 does not

**Comment by o5k** [comment]
I've potentially fixed this, but am not sure yet. 0.5.0 will include the patch, please check if it still occurs then!

**Comment by Wirtualnosc** [comment]
Still happens on opera 67.0.3575.31

**Comment by o5k** [comment]
Cannot reproduce on:

* Opera **67**
* Chromium **79 and 80**
* Firefox **78 and 56**

To be clear, I'm talking about an issue where the animation when someone enters a room glitches out and plays for all players in the list, as opposed to just the one entering/leaving.

If anyone can reproduce, please let me know.

**Comment by Wirtualnosc** [comment]
Doesn't happen on Opera 67.0.3575.53 anymore (browser bug?)

**Comment by Wirtualnosc** [comment]
Nevermind, it actually happens, but only sometimes. It is __probably__ related to player name items that are offscreen. When there are none offscreen, the bug doesn't happen

**Comment by o5k** [comment]
Am able to reproduce it now, thanks for the suggestion.

Seems to still be a browser issue (incorrect reaction to overflowing elements in an RTL container, typical Chrome) but will see if I can work around it.

**Comment by o5k** [comment]
OK, have fixed it. Will go live next patch!
