### ISSUE TITLE
Word filtering

### ISSUE THREAD

**Issue by alex-ong** [o5k/tetrio-issues#41]
### Is your feature request related to a problem? Please describe.
Some words should be in a public ban list, such as Nigg@ etc.

### Describe the solution you'd like
Integrating something like https://pypi.org/project/profanity-filter/ should be simple enough.

### Additional context
It should probably be server side since scriptkiddies could find a way to send bad words to the server

**Comment by o5k** [comment]
There already is a profanity filter..?

**Comment by alex-ong** [comment]
Just realised that there is already a filter.
