### ISSUE TITLE
KeepassXC tries to autofill non-visible fields

### ISSUE THREAD

**Issue by reolat** [o5k/tetrio-issues#42]
### Describe the bug/issue
While in menu, KeepassXC (my password manager) tries to autofill the username, password, password(repeated) and register form and shows an icon even though the fields are not visible. The icons fade away when a game starts.

### Reproducing
1. Download and Setup KeepassXC and the Browser extension
2. Visit the main menu after login

### Expected behavior
The Icons are not visible.

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**:  80.0.3987.106 with KeepassXC-Browser Version 1.5.4

### Screenshots
![image](https://user-images.githubusercontent.com/11707351/74635301-0627b100-5166-11ea-8257-9e165c80df6e.png)
![image](https://user-images.githubusercontent.com/11707351/74635329-15a6fa00-5166-11ea-96fd-7e278ea087c1.png)
![image](https://user-images.githubusercontent.com/11707351/74635357-1e97cb80-5166-11ea-919a-abbe10322de5.png)

### Additional Infos
I have observed, that the Icons fade away once the game adds the class "ingame" to the body. I manually added the class using chrome's inspector and saw the same behavior (icons fade away).
I found out that the following css triggers the behavior:
```css
.ingame .oob_modal {
    display: none;
}
```

### Suggested Solve
Add `display: none` to all .oob_modals when they are not visible (so probably to the selector `.oob_modal.hidden`). `Opacity: 0` is not enough for my(and maybe others too) Password Manager to mark it as "not visible"

**Comment by Wirtualnosc** [comment]
I can confirm that Opera browser's built-in manager asks for password save only when the game starts; happened to me the first time after I made an account.

**Comment by o5k** [comment]
Fixed in next patch.
