### ISSUE TITLE
0G isn't really 0G

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#44]
As mentioned during discussion:
> [19:17]  osk: ye, 0g makes it default to something and idk what
> [19:17]  osk: 0.15
> [19:17]  osk: because idk i was lazy and made it a very simple check, so 0 becomes 0.15
> [19:18]  osk: either use 0.0001 or -1

I'd consider this a bug for following reasons:
- 0G is faster than some values higher than it, such as 0.0001
- Intuitively 0G should mean no gravity in first place
- There is a different default value for custom games already filled in (0.02).

**Comment by o5k** [comment]
Fixed in next patch.
