### ISSUE TITLE
gravity issue when going above level 115 

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#45]
### Describe the bug/issue
gravity alternates between 0 and 20 every other level
116 is 0
117 is 20
118 is 0 etc.

### Reproducing
1. go to custom game
2. set goal as none
3. play until level 116

### Expected behavior
gravity should still be 20

### Your setup
windows 10
firefox 73.0

### Additional context
not found by me, found by oshisaure while in a call - stats are theirs as well.

**Comment by o5k** [comment]
This has been fixed in the coming patch.
