### ISSUE TITLE
targeting attackers

### ISSUE THREAD

**Issue by NikoAndTails** [o5k/tetrio-issues#46]
### Describe the bug/issue
if you target attackers and your attacker dies, it targets nobody as long as nobody else attacks you

### Reproducing
1. target attackers
2. have someone attack you
3. they die
4. attempt to deal damage, as long as nobody else attacks you, the damage goes nowhere

### Expected behavior
should find a new target in some arbitrary way

### Screenshots
none

### Your setup
windows 10
chrome

### Additional context
no

**Comment by o5k** [comment]
Fixed in next patch.
