### ISSUE TITLE
Some UI text gets autoselected during gameplay

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#47]
### Description
UI text gets autoselected during gameplay. This includes:
- KO list in the upper right corner
- KO popups during the game that inform you of who you KO'd/who KO'd you
- Screen that shows who's the winner with their survival time
- I think I had this issue with pre-game room title text (such as "Quick Play"), but I cannot recall that one too well at the moment.

### Reproduction
Unknown. Seems to happen randomly during gameplay.

### Expected behavior
Text shouldn't be selected.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/74778483-9879a300-5293-11ea-8558-c5ef350ae3fb.png)
![image](https://user-images.githubusercontent.com/6901295/74778550-b810cb80-5293-11ea-86e5-67d9a04ecc52.png)

### Your setup
Arch Linux 5.5.4-arch1-1 on x86_64 PC, using Firefox 73.0

**Comment by o5k** [comment]
Fixed in next patch.

**Comment by Wirtualnosc** [comment]
it's still a thing please reopen
![image](https://user-images.githubusercontent.com/6901295/75073628-bf351500-54f1-11ea-8c3e-157182ab30ef.png)

**Comment by o5k** [comment]
ok i fixed it for real now
