### ISSUE TITLE
Targeting options can still be used during 1v1

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#50]
### Description
Targeting options for games with more than 2 players can still be used during 1v1 play. This happens with both bigger lobbies reduced to 2 players through regular play, as well as just 2 player lobbies. Using them will cause the target option switching sound effect to play, while no visual confirmation happens.

### Reproduction
- Start 1v1 match with someone
- Press one of the targeting keys (1-4)

### Expected behavior
Nothing happens upon pressing targeting option keys.

### Your setup
Arch Linux 5.5.4-arch1-1 on x86_64 PC, using Firefox 73.0

**Comment by o5k** [comment]
Fixed in next patch.
