### ISSUE TITLE
Some regular T-Spins are detected as T-Spin Minis

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#54]
### Description
Some T-Spin Minis should be detected as regular T-Spins. That includes T-Spins with line clears.

### Reproduction
Make a T-Spin or T-Spin Single (T-Spin Double already works fine) that has a 1-block gap below where T piece would drop.

### Expected behavior
A T-Spin (Single) should be detected, instead of a mini.

### Your setup
Arch Linux 5.5.4-arch1-1 on x86_64 PC, using Firefox 73.0

### Additional context
Replay which shows the problem: https://cdn.discordapp.com/attachments/673305614318960671/679488399681650748/undefined4.ttr
This also happens with less trivial T-Spins; if someone can give a better list of such which don't work, it would be appreciated.

**Comment by o5k** [comment]
wow, the old T-Spin detection code was a total mess...

...fixed in next patch ^^;;;;
