### ISSUE TITLE
You can change your attack pattern while in chat

### ISSUE THREAD

**Issue by Lekrkoekj** [o5k/tetrio-issues#55]
### Describe the bug/issue
You can change the attack pattern when you're in chat while still alive in a match.

### Reproducing
1. Go to Quick Play
2. Open chat while you're alive in a match
3. Press 1, 2, 3, or 4
4. You will see that these numbers appear in chat and that the attack pattern changes

### Expected behavior
The expected behavior that the attack pattern shouldn't be able to be changed while in chat.

### Screenshots
https://i.imgur.com/gHtpbbc.gifv

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Microsoft Edge 82 (on the Canary build)

### Additional context
I don't have anything else to add.

**Comment by o5k** [comment]
Fixed in next patch.
