### ISSUE TITLE
Piece count and Level displays are overlapping each other

### ISSUE THREAD

**Issue by FrDarky** [o5k/tetrio-issues#57]
### Describe the bug/issue
The Piece/PPS count and Level display are shown on the exact same position, and are overlapping each other.

### Reproducing
1. Create a Custom Games with the "Use Levelling", "Display Level" and "Display Piece Count" parameters active
2. Start the custom game
3. Both displays are overlapped

### Expected behavior
One of the displays should be put above the other one to make them both clearly readable.

### Screenshots
![bug](https://user-images.githubusercontent.com/32299781/75070067-c7418480-54f2-11ea-90e0-ebb8219c1041.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Firefox Developer 74.0b6

**Comment by o5k** [comment]
Fixed in next patch.
