### ISSUE TITLE
When cycling through players in grid layout, previous active player is re-loaded

### ISSUE THREAD

**Issue by alex-ong** [o5k/tetrio-issues#58]
### Describe the bug/issue
Pressing left/right on spectate results in a temporarily blank fields. This is only in "always simplify other players windows" mode

### Reproducing
1. I'm using the option for low quality grid layout
2. I'm pressing the left/right buttons on spectate to view next player
**3. Player field is changed from the big boi to the small boi, but this results in a blank field temporarily**

### Expected behavior
Either something smart like the`big boi` field is displayed until the `little boi` is loaded, or some trickery where the `big boi` field glides to the `little boi` position and it loads a `small boi` in the background

### Screenshots
![](https://i.imgur.com/1GGdc9I.png)

### Your setup
 - **OS and version**: Win10
 - **Browser and version**: Chrome 80.0

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Fixed in next patch.
