### ISSUE TITLE
With muted sounds, audio still loads causing buzzing.

### ISSUE THREAD

**Issue by tetris28** [o5k/tetrio-issues#62]
Not really a bug, more like a suggestion maybe. But I generally play all my PC tetris games with muted sounds so can listen to spotify or whatever. In tetr.io, when I have all sounds set to zero volume. The sound assets still load throughout the games causing a buzzing noise whenever a track is loaded or switches songs. Perhaps you could just have it not load at all in this case instead of loading a sound with zero volume.

**Comment by o5k** [comment]
I can't really do this, because then issues would arise when you up the volume later on.
