### ISSUE TITLE
NaN as displayed time

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#64]
### Description
In custom games, you can have time displayed as NaN.

### Reproduction
Set a custom game with time field left empty as in following screenshot
![image](https://user-images.githubusercontent.com/6901295/75391926-eec59200-58e2-11ea-9654-bfa8c93ca65c.png)

### Expected behavior
A NaN time shouldn't be displayed. When no value is passed for time field, it should either use a default value or disable user from starting a game.

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/75392026-1c124000-58e3-11ea-84dd-7b9d861c981e.png)

**Comment by o5k** [comment]
Fixed in next patch.
