### ISSUE TITLE
key customizing error

### ISSUE THREAD

**Issue by qwerty197350** [o5k/tetrio-issues#67]
### Describe the bug/issue
My piece rotating clockwise key is numpad 8. 
When I playing games on multiplayer or solo,  if i press numpad 8 ,then current piece harddroped and next piece rotated clockwise. Other customized keys work well.
### Reproducing
1. Go to '...' config tap
2. Click on '...'  controls custom tap and customize keys.  
The same problem occurs when the numpad 8 key functions differently.
4. Play game, See error

### Screenshots
![image](https://user-images.githubusercontent.com/61526266/75402651-bb1d5300-5948-11ea-9302-c6a56b5b7da0.png)

### Your setup
 - **OS and version**: [e.g. Windows 7] Windows 10
 - **Browser and version**: [e.g. Chrome 76]  chrome 80.0.3987.122 64bit

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)
TETR.IO
tetrio.js:23 Please be careful when pasting anything in the console. Attackers may be out to steal your login information.
tetrio.js:23 Up to date. Local version 0.5.0-production | Commit 2802fa6 (2020. 2. 27. AM 7:17:31) | Server cycle 5HF5p4otU | Build mZxswuVHx (2020. 2. 27. AM 7:18:21) | PID 26145

**Comment by o5k** [comment]
Controller issue was fixed. As for the numpad, ensure Num Lock is pressed.

**Comment by qwerty197350** [comment]
[123.zip](https://github.com/o5k/tetrio-issues/files/4259921/123.zip)
I think it hasn't been fixed yet.
If Num Lock is disabled(Num Lock light is offed), there is no movement when i press any numpad key

**Comment by o5k** [comment]
well yeah thats how numlock works

**Comment by qwerty197350** [comment]
If Num Lock is abled, Numpad 8 doesn't work well
I have attached the video above 123.zip
The same problem is happening right now.

**Comment by o5k** [comment]
try with a different keyboard? it's working for me
