### ISSUE TITLE
Total games played don't update when leaving quickplay early

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#68]
### Description
Total online games played, as shown in user profile, won't update if you leave quickplay before a match ends, even if you manage to lose before that happens.

### Reproduction
1. Go to quick lobby with at least 3 players
2. Top out
3. Leave quick lobby while the other 2 players are still playing

### Expected behavior
Total online games played number should be updated to count the game you just played.

**Comment by o5k** [comment]
i just noticed, you also dont get XP for it when you leave early

**Comment by o5k** [comment]
Fixed in next patch.

**Comment by o5k** [comment]
wakey wakey

SHould still assign XP, and just update the user's top-right XP count whenever any data including it is received

**Comment by o5k** [comment]
Fixed in next patch!
