### ISSUE TITLE
Have attacking options show actual bound keys

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#69]
### Description
It can be confusing at first to know which attacking option is bound to what, since they all still show numbers next to names during gameplay. Having them show just names might be a better idea, since those keys can be mapped in options now.

### Solution
Get rid of digits next to targeting options during gameplay. This solution might make players new to tetr.io not aware of how to change strategies, though.

### Alternative
Have targeting keys ingame show actual bound keys instead of digits from 1 to 4. This might be harder to implement though, since the game would have to handle longer key names (such as "Enter" or "Caps Lock").

### Additional context
Key remapping section could reflect those changes (since they are named as "Targeting strategy X" and that might not show context very well), however I'm not sure if that's necessary since those strategies are shown in order at bottom of the screen. I'd probably be fine with either.

**Comment by o5k** [comment]
Added in next patch!
