### ISSUE TITLE
Settings don't persist across setups

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#7]
Switching browsers had me notice all my settings got dropped. These should be carried over to other sessions by storing them on the server. If the reasoning is intentional (for example, due to graphics settings), at the very least pull the last known configuration when starting a new, unknown session.

**Comment by trudnorx** [comment]
One problem with this is if you're using a private window to play none of the settings get saved. Also, it may be seen as best to carry your gameplay preferences like ARR, DAS, over devices.

**Comment by o5k** [comment]
Closing in favor of #245
