### ISSUE TITLE
Browser key events are still handled when mapping keys

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#70]
### Description
Browser events (such as scrolling down on Space key, scrolling on arrow keys etc) are still handled during key mapping in config.

### Reproduction
Go to options and define any custom key as "Space".

### Expected behavior
The browser shouldn't scroll (or in fact handle any other events when keys are being mapped by user).

### Your setup
Happens on Firefox 73.0.1 on Arch Linux

**Comment by o5k** [comment]
Fixed in next patch.
