### ISSUE TITLE
Prevent S/Z spawns before L/J/T/I

### ISSUE THREAD

**Issue by LastExceed** [o5k/tetrio-issues#71]
###Problem:
In the beginning, if you get a S or Z tetromino before a single L, J, T or I spawned, you are forced to build an overhang, which is annoying. Sometimes you can dodge the problem using hold, but that doesn't work when you get both S and Z in the beginning (or when playing no-hold)

###Solution:
The easiest way to fix this would be skipping all S and Z tetrominos in the generated spawn chain until the first L/J/T/I appears.

###Alternative:
Since the above solution potentially results in a slightly uneven supply of tetrominos in the beginning, another approach could be to just re-roll the random seed whenever this problem occurs. However this might be cpu expensive and doesn't solve it for custom matches with custom seed.

**Comment by DanKruse731** [comment]
This would benefit sprint mode for sure. I always end up restarting if I get S & Z at start.

**Comment by alex-ong** [comment]
It would benefit single player modes but what if you spent years learning bird openers in multiplayer? I mean it makes sense for sprint that's about it

**Comment by Wirtualnosc** [comment]
Yeah, I'm also against it. The only game mode I can see it being useful is indeed 40L, but even then it's playable for some players. I don't believe any other games do such randomizer tricks either.

**Comment by o5k** [comment]
i mean whats the issue with hitting R when you get an SZ start in 40L? you're gonna tap R 500 times anyway lol

there are games that do this IIRC, but not all

**Comment by alex-ong** [comment]
Unrelated but holding r for an entire second while in 40L is annoying and it should instant restart. Gotta grind my attempts in.

**Comment by o5k** [comment]
I've decided this is currently not needed. One can easily keep hitting `R` until the bag is not an SZ start. In multiplayer, everyone gets said bag, so it's not a disadvantage.
