### ISSUE TITLE
Event grace period ended for event of type attack

### ISSUE THREAD

**Issue by bmjeon5957** [o5k/tetrio-issues#74]
### Describe the bug/issue

CONNECTION ERROR
the server has disconnected you.
REASON: event grace period ended for event of type attack

please check your internet connection. if this seems to be an error, please report it

SOCKET ID: -240UE_ka_nOHOb8AAF7

### Reproducing
Play game, about 50% the time it just happens.

I live in South Korea so poor connection could be suspected.

I play other games on far gateway too, like California gateway (from south korea), but i have never experienced any severe ping spikes.

### Expected behavior
-

### Your setup
 - Windows 10
 - Chrome 80.0.3987.122

**Comment by o5k** [comment]
yeah, that means you had over 30 seconds of lag, little i can do there. I looked through server logs and it seems to 100% be a connection issue (sometimes this can pop up if a server issue happens, but my logs do not show such a thing and there were many others online on the same node)
