### ISSUE TITLE
Instant column selection

### ISSUE THREAD

**Issue by alex-ong** [o5k/tetrio-issues#75]
### Is your feature request related to a problem? 

Finesse and typomino players are requesting this. Might not be beginner friendly.
[Link](https://youtu.be/TGW4j7LRBJk)

### Describe the solution you'd like
The key per piece and esoteric input method community's would like it if you supported their non standard feature as a core input method in the game. It would invalidate all leaderboards and your engine doesn't support the input method at all but you should bow down to the vocal minority.

Pressing q should put the teleport the piece in column 1. W in column 2 etc. This is the same thing as DAS but slightly powerfuller, just like 180° rotations.

### Describe alternatives you've considered
I've tried using macros however it's not the same behavior, just like 180° spins aren't.

**Comment by alex-ong** [comment]
The game is very high-power as is, so I feel adding more tools will make it impossible for newcomers to play. Need opinions...

**Comment by alex-ong** [comment]
The lack of a proper column teleporting function is a bit off-putting for anybody who used it and is transitioning from Finesse to tetr.io. While it would be slightly more difficult for those who don’t use column teleport  to fight those who do, it really doesn’t make such a huge difference that it’ll matter a whole bunch imo. It doesn’t matter if a 3 PPS player has access to teleport compared to a .5 PPS player. The .5 PPS player will lose regardless. Unless we divide the new players and the more experienced players, the experienced ones are always gonna be beating the newer ones. The feature is gonna be accessible to everyone so everyone is free to learn stupid shit. On the other hand without teleport it makes the transition from games with teleport difficult. Improving is one of the things that make Tetris fun and learning teleport is adding another layer to that too. Overall I think that it would help more to just add the teleport instead of ignoring it in order to shelter those who can’t be bothered to learn it

**Comment by alex-ong** [comment]
How do you feel 180 should be implemented? Two rotations in a direction, or an entire new set of kicks?

**Comment by alex-ong** [comment]
Personally I would prefer the way that Finesse dealt with teleport but that’s specifically my preference. But if we consider those that are used to teleport I feel like the majority would be coming off of Finesse anyway. While I did say that it isn’t necessary to worry about the minimal advantage given by a teleport. It’d still be nicer on the other side of the argument to make them limited in double binds (e.g. I piece far left only works as e rather than q w or e) so that it doesn’t provide an even bigger gap.

**Comment by alex-ong** [comment]
How do you feel Teleport should be implemented? Pressing move left or move right that many times, or setting the pivot column of the piece?

**Comment by alex-ong** [comment]
> How do you feel Teleport should be implemented?

**Comment by alex-ong** [comment]
My argument is that tetrio is not Finesse. tetrio is a clean game with very good core guideline gameplay and it is free from confusing (though admittedly fairer(?)) game mechanics. E.g. tetrio doesn't have fractional garbage or send to all.

There are two key implementations of teleport as mentioned before
a) Press left and right a bunch for you
b) Set column

Personally i find teleport even more confusing thing than even DAS pipelining, double DAS counters and DAS tapback. They add fake depth to the game (just adding more depth to the game isn't always good). From a balance perspective they don't really affect anything, probably only esoteric bad stacks.


My reasons for no (a):
When you have walls you'll press against the wall multiple times. Piece won't go where you expect

My key reasons for no (b):

This is not Finesse
Teleporting is confusing
There isn't a guideline implementation, so every game does it differently
Even if it was decided to (b), now we have another problem which is which set of teleport to use. Left? Center? Right aligned? What about o and I piece?

On the other hand, Firm drop and Instant DAS/ARR are already enabled (albiet recently...) so you could argue that Teleport is along the same vein.

**Comment by alex-ong** [comment]
This is a pretty important thing I feel.. The reason TETR.IO stays guideline is so that people have a lot of already-known techniques to learn. There's many videos on how kicks work, lots of articles about optimizing speed etc. Since teleport isn't standardized like that, it's a bit harder for me to add, because the implementation would cause confusion.

I'm also unsure what moves exactly it would allow. I guess it can fix mistakes, but other than that I'm worried of then having to nerf Perfect Clears, due to them becoming even more accessible to pros.

I'm very much on the fence here. It's something a lot of players want and request, but ultimately I'm unsure if it would improve the quality of the game.

**Comment by alex-ong** [comment]
In my experience of using teleport I end up using them only when attempting to salvage some mistake I've made. Using teleport as a macro for two or more piece shifts will have practically no impact in general game play because the time saved is not large enough to make up the difference in thinking speeds of different skill levels. The biggest reason I'm for teleport is because I find them even cooler than DAS even if they aren't worth more. Personally I am of the opinion that having more options available, even if hidden or buried, are better in anything including Tetrio.

**Comment by alex-ong** [comment]
The thing with teleport is that many players, including myself are coming from playing Typomino or Finesse very avidly and have become used to teleport. This not only affects your mindset as you're playing, knowing that certain mistakes are able to be fixed with teleport that wouldn't be possible without them, but also affects muscle memory and speed. This makes it quite awkward to switch between tetr.io and Finesse or Typomino and may turn some players off from the site because their control scheme is being switched from what they are used to.

**Comment by alex-ong** [comment]
Finesse, Typomino and keytris have different shift tables. If teleports with a new shift table in tetr.io were implemented, whichever shift table you choose you are screwing over the other two's "muscle memory and speed"

**Comment by alex-ong** [comment]
In that case wouldn’t it be easier to just implement the kick tables for all of them and let that be an adjustable setting? I mean easier on the player base not on osk. Sorry osk, this solution involves more work on ur side but in my eyes it’ll appeal to the majority of people in that case. If that were the case then what other objections do you have?

**Comment by alex-ong** [comment]
Sure, that's what jstris does, you can change shift tables (e.g. there's a troll one with o-spins) in rule settings. Though again this seems like additional complexity to a "clean" game. But shift tables are per room (not per player). I feel like shift tables is like entry delay - enforced by room, whereas das/arr etc are player specific.

**Comment by alex-ong** [comment]
I say just use the Finesse table because I believe its the most popular client with 180s right now.

**Comment by alex-ong** [comment]
I think the obvious solution here is to make it a room option with multiple kick tables (finesse has 4 options, Typomino has 3 and keytris has 4) to choose from, defaulting to macro-like behaviour in order to stay compatible with existing leaderboards

**Comment by alex-ong** [comment]
In finesse harddrop is pressed after teleporting and rotations can also in incorporated. Should we include that also?

**Comment by alex-ong** [comment]
In Typomino, harddrop can be activated automatically after rotation. Should we implement that also?

**Comment by KSean222** [comment]
Did you go through all that effort just to show your dislike of 180? Let's flip that around: Why should CCW exist? I mean, most Tetris players won't use it (the casual players), that makes the competitive players a "vocal minority". Is it because it exists in guideline? Well, tetr.io is its "own game", so it doesn't need to consider that. Not all Tetris variants have CCW: Loads of browser games don't consider it, and as such many have never used it. In any case, you can just use a macro to press CW three times, it's basically the same thing. You can counter the lack of certain rotates by just stacking better. Have a TST that's impossible to complete because of no CCW? Just don't build it that way, or convert it into something else. The game shouldn't have to make things easier for you just for the "vocal minority" who use CCW. Having CCW would make misdrops too easy to fix, too.

**Comment by alex-ong** [comment]
Hi KSean222,

Thank you for your kind words. However i did not show dislike of 180 at any point. I was simply raising that Instant Column Selection is an excellent feature in many games (even jstris through javascript macros) that should definitely be implemented.

I find it offensive that you are interpreting my well written arguments as some form of sarcastic remarks.

You also seem to be discussing CCW rotation; please raise a new issue for this, so that people can discuss it there. (My personal stance is that CCW should also be banned)

So it should be 
* Clockwise rotation
* 270 degree rotation
* NO CCW since 270 degree rotation is strictly better
* 180 degree rotation
* Column selection
* No DAS or ARR, since Column Selection is strictly superior
* No Hard drop since you can just use a soft drop macro
* No Preview since only a vocal minority use them (like you said, casual players don't use previews)
