### ISSUE TITLE
Matches between two unranked players at high TR are FT3

### ISSUE THREAD

**Issue by Speedphoenix** [o5k/tetrio-issues#755]
### Checklist (issue will be disregarded & closed if incomplete!)

- [x] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [x] I am using the **newest version** of TETR.IO.
- [x] I know **how to reproduce the issue**.
- [x] I am using a **supported browser** or the Desktop Client.
- [x] I am not using anything that **modifies game code** (e.g. TETR.IO+).
- [x] I am certain this is a **bug**, not a feature request.

-----

### Describe the bug/issue
When players don't play tetra league for a while they become unranked, if two such players face off it will be a FT3 match, rather than what is appropriate for their current TR

### Reproducing
1. Reach S- rank or higher
2. Wait until you become unranked from inactivity
3. Play a Tetra League match against someone who also followed the previous steps
4. The match will be FT3

### Expected behavior
A FT5 match or similarly applicable depending on TR

### Screenshots
Replay: https://tetr.io/#R:ILSWZrPzD

Note that this game made me get the rank, and I had ?? displayed until this.
![image](https://user-images.githubusercontent.com/22801009/130843264-144d3eed-a072-4682-bcd1-d9710cdf3d79.png)
![image](https://user-images.githubusercontent.com/22801009/130843309-7d602bb2-7c3d-4356-80d0-ce62989c3eb7.png)

### Your setup
 - **OS and version**: Windows 10
 - **Browser and version**: Desktop Tetr.io version 6.0.9

**Comment by deedeeen** [comment]
nvm; the first-to count is already altered, haha.
