### ISSUE TITLE
The Game Does Not Work

### ISSUE THREAD

**Issue by doktorocelot** [o5k/tetrio-issues#788]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Arch Linux

### Browser and version

Brave, a fast, private and secure web browser for PC, Mac and mobile.

### Reproducing

Steps to reproduce the behavior.

**Comment by sayit358** [comment]
very nice

**Comment by Cabbage-Roll** [comment]
ass teams mode

**Comment by o5k** [comment]
![](https://kagari.online/kasumi_chiho.png)
