### ISSUE TITLE
Attacking option key names overflow their containers

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#79]
### Description
If you bind a key with a longer name than just a single letter, it will overflow the container it's supposed to be in during ingame.

### Reproduction
Bind one of attacking strategies to up arrow key or whatever long name key you have on your keyboard, then start a 3+ player game.

### Expected behavior
Key name for attacking option shouldn't overflow its' container.

### Screenshot (look at the bottom)
![image](https://user-images.githubusercontent.com/6901295/75493525-f6a03780-59b1-11ea-9bf1-a7615d1ad582.png)

### Your setup
Firefox 73.0.1

**Comment by o5k** [comment]
Fixed in next patch.
