### ISSUE TITLE
Tetra League Finish Page Glitch!

### ISSUE THREAD

**Issue by KyraCoding** [o5k/tetrio-issues#790]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome Os Version 93.0.4577.107 (Official Build) (64-bit)

### Browser and version

Google Chrome (Automatically up to date w/ Chrome Os)

### Describe the bug/issue

I don't know if it's just my Chromebook, but whenever I finish a tetra league game,
I cannot see my new rank/placement under
Tetra League Standing.
Also, I cannot even scroll in the chat.
I can see the chat, but only the first line.

### Reproducing

1. Finish any tetra league game. (You don't have to win or lose, just don't forfeit.)
2. Done!

### Expected behavior

I don't know, see what I have always been able to see?!

### Screenshots

![Screenshot 2021-10-13 12 57 51 PM](https://user-images.githubusercontent.com/76573108/137179906-6e4cff7c-1f2c-413d-94ab-1b5fbd678ba7.png)

### Console logs

I'm on a school-issued Chromebook; I will give you the logs soon!

### Additional context

My screen dimensions are 1366 x 768.
My Chromebook is an Acer Spin 311.

**Comment by o5k** [comment]
zoom out a bit (`ctrl` `-`)
also hide the bookmarks bar, it's empty so why is it set on (`ctrl` `shift` `B`)
