### ISSUE TITLE
Last character of Hangul strings is repeated

### ISSUE THREAD

**Issue by alex-ong** [o5k/tetrio-issues#81]
### Reproducing
Write any hangul string. After pressing enter, it will write two strings; the original + the last character of it.

### Screenshots
![](https://i.imgur.com/Lvas8QM.png)

### Your setup
 - **OS and version**: [e.g. Windows 7]
 - **Browser and version**: [e.g. Chrome 76]

### Additional context
Add any other context about the problem here. Browser logs are helpful (press F12, and go to the Console tab to view said console)

**Comment by o5k** [comment]
Can confirm weirdness also occurs with Japanese IME - enter immediately submits text and does not wait for IME

**Comment by o5k** [comment]
Fixed in next patch.
