### ISSUE TITLE
Key bindings overflow from their container in config screen

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#82]
### Description
Key binding names can overflow the little rectangle containers they're in. This can happen if the name of the key is very long.

### Reproduction
1. Make sure your keyboard has a key with very long name (there could be emulators maybe??)
2. Bind it to any action

### Expected behavior
The key name shouldn't overflow from the container. It should either resize the container or cut off the key name (perhaps by adding an ellipsis - there's a CSS property for that IIRC).

### Screenshots
![image](https://user-images.githubusercontent.com/6901295/75592421-2ca8ee80-5a7a-11ea-81f5-73414b35d690.png)

**Comment by o5k** [comment]
Fixed in next patch.
