### ISSUE TITLE
Attacking options show up early in quick lobby

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#83]
### Description
Attacking options show up early, during the 3 second countdown in lobby before game screen appears. They're very well visible if you bind them to a key with a long name (see #82). You can also switch between attacking options during that countdown.

### Reproduction
1. Do steps in #82 but instead bind that key to attacking options
2. Join quick play lobby and wait until the short "3 second" countdown starts

### Expected behavior
No attacking options should appear during that time and an user shouldn't be able to switch between them during that time.

### Screenshots
Look at the bottom behind the bar
![image](https://user-images.githubusercontent.com/6901295/75592701-e43e0080-5a7a-11ea-8d71-267a0efd6411.png)

**Comment by o5k** [comment]
Fixed in next patch.
