### ISSUE TITLE
Xp not being rewarded?

### ISSUE THREAD

**Issue by KyraCoding** [o5k/tetrio-issues#845]
### Checklist

- [X] I've **checked both [open and recently closed issues](https://github.com/tetrio/issues/issues?q=is%3Aissue)** to ensure this issue is not already reported.
- [X] I am using the **newest version** of TETR.IO.
- [X] I am using a **supported browser** or the Desktop Client.
- [X] I am not using anything that **modifies game code** (e.g. TETR.IO PLUS).
- [X] I am certain this is a **bug**, not a feature request.

### OS and Version

Chrome Os Version 93.0.4577.107 (Official Build) (64-bit)

### Browser and version

Google Chrome (Automatically up to date w/ Chrome Os)

### Describe the bug/issue

I don't know if this has been occurring before, but ever since the 4mil player landmark (Congrats btw), in Zen, after playing, XP is not awarded. Now, XP is awarded for modes such as 40 Lines and Blitz. Also I don't know if Quick Play ever awarded XP, but I'm not getting XP either.

### Reproducing

Simple!
Play zen for around a minute, forfeit, and tada! The XP meter does not increase. (Hovering over the level shows the same percentage.)

### Expected behavior

XP to increase

### Screenshots

Coming soon!

### Console logs

Also coming soon. (Inspect is disabled on my Chromebook; Will get on my home computer soon!

**Comment by ZudoB** [comment]
You've reached the daily cap on Zen XP. Play some different modes.

**Comment by theknightD2** [comment]
Really? I haven't played much zen today

**Comment by ZudoB** [comment]
There is a fixed limit on how much XP you can gain in Zen. The XP multiplier means you'll gain XP four times as fast, so you'll hit that limit in a quarter of the time it'd normally take.

There's no limit to XP gain in multiplayer, 40L or Blitz, so consider playing those modes instead.
