### ISSUE TITLE
Arrow keys for selecting users while spectating?

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#85]
### Is your feature request related to a problem? Please describe.
I don't like switching between my mouse and kb as much as you'd believe

### Describe the solution you'd like
enable whatever the user uses as left or right for the falling tetramino and use that for selecting between different players, maybe harddrop and/or hold key for grid view?
rotation could be used the same as left/right if you wanted to include them as well.

**Comment by o5k** [comment]
Added in next version!
