### ISSUE TITLE
Gravity interacts oddly with pieces on the ground

### ISSUE THREAD

**Issue by MinusKelvin** [o5k/tetrio-issues#88]
Gravity ticks while the piece is on the ground. This results two odd effects:
1. Lock delay is actually `1/gravity + lock delay` frames long
2. Moving a piece that has already undergone the `1/gravity` part of lock delay off of the terrain causes it to instantly fall one tile. This makes S/Z climbing impossible at high gravity, as well as is the true cause of #20.

### Reproducing
Case 1:
1. Create a custom game with lock delay 1 and low gravity
2. Wait for the piece to touch the floor
3. Observe that it takes much longer for the piece to lock than 1 frame

Case 2:
1. Create a custom game with high lock delay and low gravity
2. Place a piece to create a cliff, then wait for the next piece to touch the top of the cliff and for `1/gravity` frames to pass (there's actually a sound effect for this)
3. Move the piece off of the cliff and observe that the piece instantly falls one tile

### Expected behavior
Case 1: 1 frame after the piece touches the floor, the piece locks.
Case 2: After moving the piece off the cliff, `1/gravity` frames should pass before the piece falls. Even if the piece is moved back onto the cliff, once it is moved off again, `1/gravity` frames should still have to pass before the piece falls (in other words, gravity should reset when the piece touches the ground).

This is based on how games like Puyo Puyo Tetris and Tetris 99 work. Jstris handles gravity in a way that results in inconsistent oddities similar to the ones I'm reporting here, but due to Jstris' much lower gravity they generally do not manifest in normal gameplay.

**Comment by o5k** [comment]
...I think I fixed this properly now, but please test it out once the patch is in.
