### ISSUE TITLE
Spectate option for full rooms in Multiplayer

### ISSUE THREAD

**Issue by mat1jaczyyy** [o5k/tetrio-issues#9]
Suggested by Wumbo on Discord. Spectating full rooms is a nice addition as matches could be streamed with commentary etc

**Comment by o5k** [comment]
This is definitely planned for before Alpha!

**Comment by mat1jaczyyy** [comment]
Quickplay should also be spectated if entered while a game is ongoing

**Comment by o5k** [comment]
> Quickplay should also be spectated if entered while a game is ongoing

This will be very difficult, that's something for later (Beta or so)

**Comment by o5k** [comment]
This has been added in the coming 0.5.0 patch!
