### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by KSean222** [o5k/tetrio-issues#90]
### Is your feature request related to a problem? Please describe.
https://webaim.org/techniques/keyboard/

### Describe the solution you'd like
Perhaps support either using TAB for navigation, or use dedicated keybinds for menus.

**Comment by o5k** [comment]
Added in a recent patch!

**Comment by vaaski** [comment]
how can I start a multiplayer match without using my mouse?
I cannot tab to it (even with tab unbound) and I cannot reach it with arrow key navigation.

> ![image](https://user-images.githubusercontent.com/17879327/135085718-faa663ee-8cb8-4345-80c8-ae8220508af3.png)
> referring to this button
