### ISSUE TITLE
grid Sound effects be like

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#91]
### Describe the bug/issue
grid sound effects repeat even though nothing changes

### Reproducing
1.   join any game with more than like 4 people idk who cares
2.   spam softdrop or harddrop 
3.   notice how the sound constantly plays even though nothing changes? whacky wild ik

### Expected behavior
Nothing

### Additional Comments
bruh im tired

**Comment by Neeko-iko** [comment]
sorry step 1.5: die.

**Comment by o5k** [comment]
Fixed in next patch.
