### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by KSean222** [o5k/tetrio-issues#92]
### Is your feature request related to a problem? Please describe.
It gets a bit boring when waiting for someone to join a room. Typically, I just leave the tab open, but then I risk someone joining the room, waiting, and then leaving because of inactivity.

### Describe the solution you'd like
Notifications for when someone joins a room and more.

### Describe alternatives you've considered
JStris also sets the title of the tab. You could also play a chime, though the chime is less accessible.

**Comment by o5k** [comment]
Added in next patch!
