### ISSUE TITLE
Separate option for showing background effects

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#93]
### Is your feature request related to a problem? Please describe.
I like the background effects, but setting background visibility to 0 disables them all. I'd like to see them without a background.

### Describe the solution you'd like
Have a separate ON/OFF or slider option for background effects.

### Screenshots
A background visibility of 0% with effects fully shown (worked around by setting a fully black background):
![image](https://user-images.githubusercontent.com/6901295/75631023-49af0000-5be7-11ea-96f2-babff060286e.png)
Currently, you cannot set these settings separately. Background visibility of 0% results in having no background effects:
![image](https://user-images.githubusercontent.com/6901295/75631030-5b90a300-5be7-11ea-96af-d95b6eb122f9.png)

**Comment by o5k** [comment]
Using a black background image should be OK with this, yes?

**Comment by Wirtualnosc** [comment]
Well yes. I think I kinda missed the point though... The reason I keep background off is because seeing these effects is not as easy otherwise. Maybe I'm just begging for better visibility of those in first place, or a separate slider for that... That being said, I don't have strong opinion on this so if it's a problem to change then just leave stuff as is.

**Comment by o5k** [comment]
Setting a black background works better here than having yet another slider in the options I feel
