### ISSUE TITLE
Board background visibility slider/checkbox

### ISSUE THREAD

**Issue by Neeko-iko** [o5k/tetrio-issues#94]
### Is your feature request related to a problem? Please describe.
bro imagine how cool it'd be to see the backdrop behind the game itself, that's really it tbh idk what else to say

### Describe the solution you'd like
toggle on/off or slider for background visibility (the black behind the board)
0% being there is no black, it'll just show the backdrop behind it
100% being default + what it is now

**Comment by o5k** [comment]
Added in next version!
