### ISSUE TITLE
Tetra channel replays are slower than actual games

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#96]
### Description
Submitted replays are a bit slower than actual games (by a bunch of milliseconds). This not only results in different replays on both result screens, but also different end times shown for 40L.

### Reproduction
1. Start a game of 40L and finish it
2. Note the time shown in the end result screen. You can download the replay as well
3. Go to Tetra Channel and check your most recently played 40L game
4. The time shown there is different. The downloaded replay will be different as well

### Expected behavior
Both times and replays should be identical.

### Screenshots
Result screen
![image](https://user-images.githubusercontent.com/6901295/75729999-721c2480-5ce3-11ea-811f-ac392dd651ab.png)
Tetra channel
![image](https://user-images.githubusercontent.com/6901295/75730021-7cd6b980-5ce3-11ea-97d5-21badaaffb08.png)
You can see it's the same game since they both have the same replay ID.

**Comment by o5k** [comment]
Fixed in next version.
