### ISSUE TITLE
Other piece spins are shown as T-Spins in result screen

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#97]
### Description
Other piece spins are shown as T-Spins in result screen. Each piece spin will add up to the corresponding T-Spin counter in the end results. For example, if you manage to do an O-Spin Double, it will be added in the end results as T-Spin Double.
This doesn't apply to I-Spin Quads (as these don't have a corresponding field in the result screen). These results will also add up with regular, non-clear spins.

### Reproducing
1. Start a custom game with "Topping out is OK" and spins set as "Stupid"
2. Do a bunch of piece spins and piece spin clears
3. Top out
4. Look at T-Spin counters in the end result screen

### Expected behavior
T-Spin fields in end result screen should only count T-Spins.

**Comment by o5k** [comment]
Fixed in next version.

**Comment by Wirtualnosc** [comment]
idk if it's intended to stay but as my beautiful painting shows there's still one trace left
![image](https://user-images.githubusercontent.com/6901295/75818858-8880b980-5d91-11ea-9df2-a7088180b921.png)

**Comment by o5k** [comment]
oops i forgot the overview

**Comment by o5k** [comment]
Hotfixed - reload to see.
