### ISSUE TITLE
Counters ingame don't match the ones in result screen

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#98]
### Description
Piece count at the end of the game doesn't match piece count shown in result screen. It seems like the final piece isn't incremented during screen switch.

### Reproduction
Start a 40L or custom game and finish it (make sure to not finish by topping out). Make sure to look at piece count both ingame and in result screen.

### Expected behavior
The ingame piece count should be incremented correctly to match the one in result screen.

**Comment by o5k** [comment]
Fixed in next version.

**Comment by o5k** [comment]
Reopening, as the fix caused a regression:

**Now the timer is 1 frame ahead lole**

**Comment by o5k** [comment]
Fixed in next patch.
