### ISSUE TITLE
Tetra channel music in main menu on invalid replay

### ISSUE THREAD

**Issue by Wirtualnosc** [o5k/tetrio-issues#99]
### Description
If you try to open a link with invalid replay ID then tetra channel music plays in main menu.

### Reproduction
Use invalid replay link like this one https://tetr.io/#R:1337HAXxx

### Expected behavior
Normal main menu music should be played.

**Comment by Wirtualnosc** [comment]
This also happens if you repeatedly switch between main menu and tetra channel menus. If you stop at main menu, you can get tetra channel to play there instead. Same with quickplay music

**Comment by o5k** [comment]
Both fixed in next version.
